#!/bin/bash -x
if [ $# -ne 3 ] || [ $2 != "-np" ] ; then
    echo "An example of usage: job si -np 4"
    exit 101
fi

material=$1
mpis=$3
nfpgw=$HOME/ecalj/SRC/exec

$nfpgw/lmfa $material >& lmfa
mpirun -np $mpis $nfpgw/lmf $material >& llmf
$nfpgw/../../GetSyml/getsyml.py $material |grep syml
$nfpgw/job_band $material -np $mpis

$nfpgw/job_ham $material -np $mpis
gnuplot -p bandplot_MLO0.isp1.glt
$nfpgw/lmfham2 $material --job=0
$nfpgw/lmfham2 $material --job=1
gnuplot -p bandplot_MLO.isp1.glt
gnuplot -p bandplot_MLO.isp2.glt
