#! /bin/bash
# keep head part -----------------
for ddd in $@
do 
    echo $ddd
    pushd .
    cd $ddd

    for xxx in `find . -name VXCFP.chk`
    do
    echo $xxx
    head -1000 $xxx > $xxx.head
    rm $xxx
    done
    for xxx in `find . -name "normchk.*"|grep -v head`
    do
    echo $xxx
    head -1000 $xxx > $xxx.head
    rm $xxx
    done
    
    for xxx in v_xc evec VCC PLN WVR WVI EVU EVD PPB BAS fort BAS VXCFPV PPOVL DATA4GW gwa gwb gw1 gw2 gw3 PHI HVCCIN CPHI CphiGeig GEIG mixm mixsigma sigma vxc moms Vcoud EPS0inv Core evec vxc WVI WVR
    do
    echo 'cleaning--- ', "$xxx*" '----------------------'
    find . -name "$xxx*"
    rm -f `find . -name "$xxx*"`
    done
    popd
done
rm -f mlog* stdout* eibze* mlog* rcxq* x0icount* norm* mix*

exit

rm -f VCC*
rm -f PLN
rm -f WVR
rm -f WVI
rm -f PPB*
rm -f BAS*
rm -f fort.*
rm -f HVCCIN
rm -f PHI*
rm -f EV*
rm -f CPH*
rm -f VXCFP
rm -f VXCFPV
rm -f PPOVL
rm -f DATA4GW*
rm -f gwa.*
rm -f gwb.*
rm -f gw1.*
rm -f gw2.*
rm -f gw3.*
rm -f vxc.*
rm -f EPS0inv
rm -f Vcoud
