[default]
launcher = "mpirun"
launcher_args = ["-np {nprocs}"]
env = {}

[impi]
launcher = "mpirun"
launcher_args = ["-np {nprocs}", "-ppn {npernode}"]
env = {"OMPI_MCA_coll_hcoll_enable" = "0"}

[ohtaka]
launcher = "srun"
launcher_args = ["-n {nprocs}"]
env = {}

[mic]
launcher = "srun"
launcher_args = ["-n {nprocs}"]
env = {}

[kugui_gpu]
launcher = "mpirun"
launcher_args = ["-np {nprocs}", "-npernode {npernode}", "--bind-to none"]
env = {}

[es_gpu]
launcher = "mpirun"
launcher_args = ["${NQSV_MPIOPTS}", "-np {nprocs}", "-npernode {npernode}", "--bind-to none", "-x LD_LIBRARY_PATH"]
env = {}
