#!/usr/bin/env python3
import sys
#import string
import os

def compareqpu(qpu1,qpu2,printsw):
	pr = (printsw==1)
	oxx= qpu1.split('\n') 
	oyy= qpu2.split('\n')
	errmax=0.0
	for ix in range( max(len(oxx),len(oyy))):
		iline=oxx[ix]
		ilin2=oyy[ix]
		if ix==5:
			if pr: print (iline)
		if ix>=6:
			if pr: print (iline[0:32],end='')
			try:
				for iw in range(4,17,1):
					w1=float(iline.split()[iw])
					w2=float(ilin2.split()[iw])
					if (iw >=15) & pr : print( '%9.5f' % (w1-w2),end='')
					if (iw <=14) & pr : print( '%6.2f' % (w1-w2),end='')
					if( abs(w1-w2)>errmax ): errmax=abs(w1-w2)
					#errmax=errmax + abs(w1-w2)
				if pr: print()
			except:
				if pr: print(iline)
	return errmax

############### main ###################################
try:
	print ("   Readin two files =     ", sys.argv[1], sys.argv[2])
except:	
	print ("   usage: dqpu QPU1 QPU2")
	sys.exit()

qpu1 = open(sys.argv[1],'rt').read()
qpu2 = open(sys.argv[2],'rt').read()

#print sys.argv
if '--print' in sys.argv : 
	printsw=1
else:
	printsw=0
#print 'printsw=', printsw
errmax = compareqpu(qpu1,qpu2, printsw)
#errmax = compareqpu(qpu1,qpu2, printsw=0)
	
	
if(errmax<1.1e-2):
	print ('   Comparison OK!  Difference sum=',errmax,' <1.1e-2 between:   ' + sys.argv[1]+ '   and   ' + sys.argv[2])
	sys.exit()
else:
	errmax = compareqpu(qpu1,qpu2, printsw=1)
	print() 
	print ("   Readin two files =  ", sys.argv[1], '  ',sys.argv[2])
	print( '   Error! Difference>1.1e-2 between:   ' + sys.argv[1]+ '   and   ' + sys.argv[2], ' :  max(abs(QPU-QPU))=',errmax)
	print( '   (But small diff can be not a problem. It can be due to a minor machine-depenence.)')
	sys.exit(-1)
	

