#!/usr/bin/env python3
import argparse
import numpy as np
import sys

def compareqpu(qpu1, qpu2, printsw, ecut, etol):
    pr = not printsw
    oxx= qpu1.split('\n') 
    oyy= qpu2.split('\n')
    errmax = np.zeros(13)
    for ix in range( min(len(oxx),len(oyy))):
        iline = oxx[ix]
        ilin2 = oyy[ix]
        if ix == 5:
            print (iline)
        if ix >= 6:
            str = iline[0:32]
            try:
                w1 = np.array(list(map(float, iline.split()[4:])))
                w2 = np.array(list(map(float, ilin2.split()[4:])))
                if all(w1[i] == 0 for i in range(2)) or all(w2[i] == 0 for i in range(2)):
                    continue
                eqp1 = w1[6] #Index 6 -> eQP
                eqp2 = w2[6]
                if (eqp1 > ecut) or (eqp2 > ecut):
                    continue
                errmax = np.maximum(errmax, np.abs(w1 - w2))
                str = str + ''.join(
                    f'{(v1-v2):8.3f}' if i < 10 else
                    f'{(v1-v2):5.2f}' if i == 10 else
                    f'{(v1-v2):10.5f}' if i == 11 else
                    f'{(v1-v2):13.5f}'
                    for i, (v1, v2) in enumerate(zip(w1, w2))
                )
                if pr: print(str)
            except:
                if pr: print(iline)
    str = ' '*17 + 'Max difference='+''.join(
        f'{v:8.3f}' if i < 10 else 
        f'{v:5.2f}' if i == 10 else
        f'{v:10.5f}' if i == 11 else
        f'{v:13.5f}' for i, v in enumerate(errmax)
    )
    print(str)
    return errmax[6]

############### main ###################################

parser = argparse.ArgumentParser()
parser.add_argument('QPU1', type=str, help='QPU or QPD file')
parser.add_argument('QPU2', type=str, help='QPU or QPD file')
parser.add_argument('--ecut', type=float, default=1000, help='energy cutoff from Fermi level')
parser.add_argument('--etol', type=float, default=0.011, help='eQP difference tolerance')
parser.add_argument('--noprint', action='store_true', default=False, help='print flag')
args = parser.parse_args()

qpu1 = open(args.QPU1,'rt').read()
qpu2 = open(args.QPU2,'rt').read()
etol = args.etol
ecut = args.ecut

print(f'Comparing two QPU files: {args.QPU1}  and {args.QPU2}  with ecut={ecut}')
errmax = compareqpu(qpu1,qpu2, args.noprint, ecut, etol)
print(f'Difference= {errmax:.3f} eV')

if errmax< etol:
    print ('   Comparison OK!  Difference sum=',errmax,' <1.1e-2 between:   ' + args.QPU1+ '   and   ' + args.QPU2)
    sys.exit()
else:
    print ("   Readin two files =  ", args.QPU1, '  ',args.QPU2)
    print( '   Error! Difference>1.1e-2 between:   ' + args.QPU1 + '   and   ' + args.QPU2, ' :  max(abs(QPU-QPU))=',errmax)
    print( '   (But small diff can be not a problem. It can be due to a minor machine-depenence.)')
    sys.exit(-1)
