#!/bin/csh -f
#for tatara in kyushu-u This is neglected in other cases.
if(-e /home/etc/intelMPI.csh) source /home/etc/intelMPI.csh
######## \epsilon calculation.
set n = $0
set nfpgw = ${n:h}
 echo  $nfpgw

 echo $argv[1]
setenv LMJOB $argv[1]

#cray 
#set echo_run="aprun"
#set mpi_run="aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN"
#set serial_run="aprun"

#normal mpi 
set echo_run=""
set mpi_run="mpirun -np $MPI_SIZE"
set serial_run=""


rm -f NoCore QPU*

### Check the existence of EPScond
#if (! -e EPScond) then
#   echo ' Not exist EPScond: Maximum omega. intervals for plotting .'
#   echo ' Now I made a sample of EPScond.tmp'
#   echo ' 1d0 0.1d0 ' > EPScond.tmp   
#   exit 1
#endif 

### Get LATTC and SYMOPS
$echo_run echo 0 |$serial_run $nfpgw/lmf --novxc  $argv[1] --jobgw > llmfgw00


### Add q points  to Q0P file.  -----------------
# moved to <QforEPS> in GWinput
$echo_run echo 2|$serial_run $nfpgw/qg4gw  >lqg4gw02

#eigenvalues for micro-tetrahedron method.
if(-e Qmtet) then
  mv Qmtet Qeigval 
$echo_run echo 5 |$serial_run $nfpgw/lmf --novxc  $argv[1] --jobgw > llmfgw_eigval
  mv eigval eigmtet
endif

###
#echo 1 | $serial_run $nfpgw/ng0  >lng01
#echo 2 | $serial_run $nfpgw/ng0  >lng02
#$serial_run $nfpgw/nfp4gw        >lnfp4gw
$echo_run echo 1 |$serial_run $nfpgw/lmf --novxc  $argv[1] --jobgw > llmfgw01
#@ exinfo = `tail -3 llmfgw01 | head -1|awk '{print $2}'`
#set exinfo = `echo $?`
set exinfo = $?

if($exinfo == 0 ) then
$echo_run echo " OK! lmf mode=1 --jobgw"
else
$echo_run echo Error in echo 1\|lmf $argv[1] --jobgw
$echo_run echo  `tail -3 llmfgw01 `
  exit
endif
$echo_run echo $argv[1]|$serial_run $nfpgw/lmf2gw   > llmf2gw

#$echo_run echo 1|$serial_run $nfpgw/rdata4gw_v2      >lrdata4gw

# get EFERMI
$echo_run echo 1|$serial_run $nfpgw/heftet      >leftet

$echo_run echo 8|$serial_run $nfpgw/hbasfp0 >lbas
$echo_run echo 202|$serial_run $nfpgw/hvccfp0        >lvcc	
$echo_run echo 223|$serial_run $nfpgw/hx0fp0  >lx0




 

