#!/bin/bash -eu
trap 'echo "ERROR exit"' ERR
if [ $# -ne 3 ] || [ $1 != "-np" ] ; then
    echo "An example of usage: epsPP -np 4 si"
    echo "epsPP gives interband and intraband contributions"
    exit 101
fi
nfpgw=`dirname $0`
MPI_SIZE=$2
TARGET=$3
######## THIS IS for no lfc mode. See hbasfp0 and hx0fp0 c2 case.
echo "### START epsPP@"$nfpgw,' $MPI_SIZE= '$MPI_SIZE, ' $TARGET= '$TARGET
set -x
$nfpgw/lmf-MPIK --job=0 --novxc $TARGET --jobgw >& llmfgw00  #generate information files
$nfpgw/qg4gw --job=2 --zmel0  >& lqg4gw02   #Generate q points for GW
mpirun -np $MPI_SIZE $nfpgw/lmf-MPIK --job=1 --zmel0 $TARGET --jobgw >& llmfgw01 #generate eigenfunctions for GW.
$nfpgw/rdata4gw_v2 --job=0 >& lrdata4gw_v2 # Prepare all files for GW
$nfpgw/heftet  --job=1 >& leftet # A file EFERMI for hx0fp0 generated
$nfpgw/hbasfp0 --job=4 >& lbas   # Product basis generation mode=4
mpirun -np $MPI_SIZE $nfpgw/hvccfp0 --job=202 >& lvcc # Coulomb matrix for lbas 
mpirun -np $MPI_SIZE $nfpgw/hx0fp0 --job=202 --zmel0 --interbandonly >& lx0_interband #EPS for interband
#mpirun -np $MPI_SIZE $nfpgw/hx0fp0 --job=202 --zmel0 --intrabandonly >& lx0_intraband #EPS for intraband
echo OK! ==== All calclation finished for epsPP ====,$TARGET
