#!/usr/bin/env python3
import argparse
import contextlib
from pathlib import Path
from run_cmd import run_cmd, MPIParams

EXEC_DIR = Path(__file__).resolve().parent

def cal_eigen(args, extra_args):
    if not Path("kpoints_eigen.in").is_file():
        raise SystemExit("Error: 'kpoints_eigen.in' not found.")

    target = args.extension
    mpi_size = args.np
    cluster = args.cluster
    run_cmd(cluster, MPIParams(nprocs=mpi_size, command=EXEC_DIR/"lmf_main",
                               args=[target, "--quit=band", *extra_args]), stdout="llmf_ef")
    run_cmd(cluster, MPIParams(nprocs=mpi_size, command=EXEC_DIR/"lmf_main",
                               args=[target, "--band", "--eigen-at-k", "--skipbstruxinit",
                                     f"-emin={args.emin}", f"-emax={args.emax}", *extra_args]), stdout="llmf_eigen")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog='job_eigenvalue',
        description=(
            'Get eigenvalues at any k-point listed in kpoints_eigen.in.\n'
            'The file kpoints_eigen.in must exist in the current directory.\n'
            'Format: Each line contains the cartesian coordinates (in units of 2π/a) of a k-point to be calculated.\n'
            'Example kpoints_eigen.in:\n'
            '  kx1 ky1 kz1\n'
            '  kx2 ky2 kz2\n'
            '  kx3 ky3 kz3\n'
            '  ...\n\n'
            'The energy range can be specified with the -emin and -emax options.\n'
            'The default range is -100 eV to 30 eV.\n\n'
            'Example:\n'
            '  job_eigenvalue cu -np 8 -emin=-20 -emax=20 -vpwemax=4 -vgmax=15\n'
            'Output: Eigenvalues for the specified k-points and energy range are saved in eigenup.dat (majority spin state) and eigendw.dat (minority spin state).\n'
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("-c", "--cluster", help="cluster name", default="default", type=str)
    parser.add_argument("extension", help='Extension of the ctrl file')
    parser.add_argument("-np",       help='Number of MPI cores for lmf', default=8, type=int)
    parser.add_argument("-emin",     help='Lower bound of output energy in eV', default=-100, type=float)
    parser.add_argument("-emax",     help='Upper bound of output energy in eV', default=30, type=float)
    parser.add_argument("-d", "--dir", help="execution directory (default: current directory)", default=".", type=str)
    args, extra_args = parser.parse_known_args()
    with contextlib.chdir(args.dir):
        cal_eigen(args, extra_args)
