#!/bin/bash -eux
nfpgw=`dirname $0`
echo $0
echo $@
#echo $4
if [ $# -le 2 ] || [ $2 != "-np" ]; then
  echo "An example of usage: job_ham si -np 4 [options for lmf]"
  exit
else
  MPI_SIZE=$3
fi
rm -f HamiltonianPMT*
echo 'Runnnig Hamiltonian generation'
mpirun -np $3 $nfpgw/lmf $1 --writeham --mkprocar >& out_writeham
# Get Hamiltonian file, namded as HamiltonianMTO
cat HamiltonianPMT.* >HamiltonianPMT
rm HamiltonianPMT.* 
# Get |MTP> Get MTprojected Hamiltonian
mpirun -np $3 $nfpgw/lmfham1 $1 >& out_lmfham1

# Get |MLO> Get MLO Hamiltonian
#$nfpgw/lmfham2 --job=0 >& out_lmfham2_0
#$nfpgw/lmfham2 --job=1 >& out_lmfham2_1
echo 
echo '1.Edit mlo_foobar in GWinput, and Run'
echo '2.>lmfham2 si --job=0'
echo '3.>lmfham2 si --job=1, then Check bandplot.lmfham2.*.glt'
echo 'OK! end of job_ham. Run next steps above'
