#!/bin/bash
# generate MLO ### all input arguments are processed ###
if [ $# -ne 3 ] || [ $2 != "-np" ] ; then
    echo "An example of usage: job_mloW cu -np 4"
    echo "Do job_band_* in advance to genMLO"
    exit 101
fi
nfpgw=`dirname $0`
MATERIAL=$1
MPI_SIZE=$3
NO_MPI=0
### end of processing input arguments ###
if [ ! -e bnd001.spin1 ];then 
    $echo_run echo "!!! Perform job_band in advance!" 
    exit
fi

### Read funcitons run_arg and run_arg_tee defined in a file run_arg ###
source $nfpgw/run_arg

######## auto-convert legacy GWinput -> GWinput.toml if needed ##########
if [ ! -f GWinput.toml ] && [ -f GWinput ]; then
    echo "job_mloW: auto-generating GWinput.toml from GWinput"
    python3 $nfpgw/gwinput2toml.py GWinput || { echo "job_mloW: gwinput2toml.py failed"; exit 1; }
fi
if [ ! -f GWinput.toml ]; then
    echo "job_mloW: ERROR -- GWinput.toml is required" >&2
    exit 1
fi

######## start here ##########
$echo_run echo "### START genMLWF: MPI size= " $MPI_SIZE, "MATERIAL= "$MATERIAL
## If sigm and sigm.$MATERIAL coexist, sigm.$MATERIAL is moved to sigm.$MATERIAL.backup in advance.
if [ -e sigm ]; then 
    if [ -e sigm.$MATERIAL ]; then
	mv sigm.$MATERIAL sigm.$MATERIAL.bakup 
  	ln -s -f sigm sigm.$MATERIAL 
  	$echo_run echo '--- sigm is used. sigm.$MATERIAL is softlink to it  ---'
    fi
else
    $echo_run echo '--- Neither sigm nor sigm.$MATERIAL exists. ==> LDA '
fi 


######## lmf part #########################################
run_arg '---' $NO_MPI   $nfpgw /lmfa  llmfa $MATERIAL # if lmfa is not yet.
run_arg '---' $MPI_SIZE $nfpgw /lmf llmf_start $MATERIAL

##### preparation of required inputs for GW (mainly prepare required eigenfuncitons) ######
argin=0; run_arg $argin $NO_MPI   $nfpgw /lmf llmfgw00 $MATERIAL --jobgw=0
argin=1; run_arg $argin $NO_MPI   $nfpgw /qg4gw      lqg4gw   #Generate requied q+G vectors.
argin=1; run_arg $argin $MPI_SIZE $nfpgw /lmf llmfgw01 $MATERIAL --jobgw=1 --mlo
#--wanatom

argin=1; run_arg $argin $NO_MPI $nfpgw /heftet leftet # A file EFERMI for hx0fp0
argin=0; run_arg $argin $NO_MPI $nfpgw /hbasfp0 lbas  # Product basis generation 

### pkm4crpa file mode for crpa ###
#argin=10011; run_arg $argin 1 $nfpgw /hwmatK_MPI lpkm4crpa 

### Main part of v, W-v for Wanniers. ##########################
run_arg '---' $MPI_SIZE  $nfpgw /mlo lmlo $MATERIAL --mlo
argin=0;  run_arg $argin $MPI_SIZE $nfpgw /hvccfp0 lvcc        # Coulomb matrix v
argin=1;  run_arg $argin $MPI_SIZE $nfpgw /hwmatK_MPI lwmatK1 $MATERIAL --mlo # Matrix elements of v for Wannier
argin=111; run_arg $argin $MPI_SIZE $nfpgw /hx0fp0 lx0_111     # Screened Coulomb W minus v, W-v
argin=2;  run_arg $argin $MPI_SIZE $nfpgw /hwmatK_MPI lwmatK2 $MATERIAL --mlo # Matrix element of W-v

#$nfpgw/Cal_W.py

# #### crpa
# argin=10011; run_arg $argin $MPI_SIZE $nfpgw /hx0fp0 lx0_10011    # cRPA Screened Coulomb W minus v, W-v
# argin=100;  run_arg $argin $MPI_SIZE $nfpgw /hwmatK_MPI lwmatK2crpa # Matrix element of W-v
# #$nfpgw/Cal_W.py

$echo_run echo "OK! It's finished well."
exit 0
