#!/bin/bash
# --------------------------------
# Get GWinpt.tmp
n=$0
nfpgw=`dirname $0`
echo $nfpgw
echo $#
echo $1

$nfpgw/lmfa $1 >llmfa
$nfpgw/lmf --jobgw=0  $1 > llmfgw00
$nfpgw/gwinit   #This changes the <QPNT> setting.

echo "-------------------------------------------------------------------"
echo "  We use n1n2n3=" 4 4 4 " in GWinput. This is k points mesh for GW mode"
echo "  You can change it by hand (not need to repeat this). =="
echo 'OK! GWinpt.tmp is generated!'
 
