#!/bin/bash
# -------------------------------------------------------------------------
# generate MLWF.
# NOTE: Wannier is generated before wanplot (wanplot is only to make *.xsf file for plot).
#       After wanplot, we goto calculate <wan wan |W |wan wan>
# For cray, set machine="cray"
#--------------------------------------------------------------------------
### all input arguments are processed ###
if [ $# -ne 3 ] || [ $2 != "-np" ] ; then
    echo "An example of usage: genMLWF cu -np 4"
    echo "Do job_band_* in advance to genMLWF to get superposition of Wannier band plot!"
    exit 101
fi
nfpgw=`dirname $0`
MATERIAL=$1
MPI_SIZE=$3
NO_MPI=1
### end of processing input arguments ###

source $nfpgw/run_arg

$echo_run echo "### START genMLWF: MPI size= " $MPI_SIZE, "MATERIAL= "$MATERIAL

run_arg '---' $NO_MPI   $nfpgw /lmfa  llmfa $MATERIAL # if lmfa is not yet.
run_arg '---' $MPI_SIZE $nfpgw /lmf llmf_start $MATERIAL

argin=0; run_arg $argin $NO_MPI   $nfpgw /lmf      llmfgw00 $MATERIAL --jobgw=0
argin=1; run_arg $argin $NO_MPI   $nfpgw /qg4gw      lqg4gw   #Generate requied q+G vectors.
argin=1; run_arg $argin $MPI_SIZE $nfpgw /lmf llmfgw01 $MATERIAL --jobgw=1

argin=1; run_arg $argin $NO_MPI $nfpgw /heftet leftet # A file EFERMI for hx0fp0
argin=0; run_arg $argin $NO_MPI $nfpgw /hbasfp0 lbas  # Product basis generation 

argin=1 ;run_arg $argin $NO_MPI $nfpgw   /hmaxloc lmaxloc1     # b-vector BBVEC
argin=2 ;run_arg $argin $MPI_SIZE $nfpgw /huumat_MPI luumat2 --q2q1test  # UU (UUmatrix <u_k,i|u_k+b,j>) matrix are caltulated.

$echo_run echo "OK! --q2q1test finished. Normalization check in luumat2!"
exit 0
