#!/bin/bash

mkdir MKbackup/
mkdir MKbackup/MAKEINC
cp  lm7K/MAKEINC/* MKbackup/MAKEINC
cp  lm7K/Makefile  MKbackup/
cp  fpgw/exec/make.inc* MKbackup/
cp  fpgw/exec/make.inc  MKbackup/
cp  fpgw/exec/makefile  MKbackup/
