from comp import test2_check, runprogs, rmfiles
def test(args, bindir, testdir, workdir):
    MATERIAL = "ni"
    ncore = args.np
    lmfa = f'mpirun -np 1 {bindir}/lmfa '
    lmf  = f'mpirun -np {args.np} {bindir}/lmf '
    outfile = f'out.lmf.{MATERIAL}'
    dats = ['TrKpm.syml001', 'TrRpm.syml001', 'TrKpm.syml002', 'TrRpm.syml002']
    tall = ''

    rmfiles(workdir, [outfile] + dats)
    if args.checkonly:
        runprogs(["rm -rf summary.txt"], quiet=True)
    else:
        runprogs([
            lmfa + f" {MATERIAL} > " + outfile,
            lmf  + f" {MATERIAL} > " + outfile,
            f"{bindir}/job_band   {MATERIAL} -np {ncore} --NoGnuplot",  # band plot
            f"{bindir}/job_magnon -np {ncore} {MATERIAL}",              # magnon calculation
            "gnuplot mag3d.glt",
            "gnuplot r_k.glt",
            "gnuplot wan_bandplot.glt"
        ])
    # omega=0 skip (K/R have 1/omega poles)
    skip_w0 = lambda line: len(line.split()) >= 5 and abs(float(line.split()[4])) < 1e-6
    for dat in dats:
        print(dat, end=': ')
        tall += test2_check(testdir + '/' + dat, workdir + '/' + dat,
                            abs_tol=1e-3, rel_tol=1e-3, skipcond=skip_w0)
    message = f'''
    ==========================================================================
    Magnon calculation finished.
      TrKpm.syml00[12], TrRpm.syml00[12]
      *.pdf generated by gnuplot
    To view: evince {workdir}/magnon3d_100.pdf
    Reference eps: {testdir}/ref/*.eps
    ==========================================================================
    '''
    print(message)
    return tall
