from comp import test2_check,peak_check,runprogs,rmfiles
def test(args,bindir,testdir,workdir): #Fixed. called as >testecalj Fe_magnon
    MATERIAL="fe"
    ncore=args.np
    lmfa= f'mpirun -np 1 {bindir}/lmfa '
    lmf = f'mpirun -np {args.np} {bindir}/lmf '
    outfile='out.lmf.fe'
    dat1='TrKpm.syml001'
    dat2='TrRpm.syml001'
    tall=''

    rmfiles(workdir,[outfile,dat1,dat2])
    if(args.checkonly): runprogs([
            "rm -rf summary.txt"
            ],quiet=True)
    else: runprogs([
        lmfa + f" {MATERIAL} > "+ outfile,
        lmf  + f" {MATERIAL} > "+ outfile,
        f"{bindir}/job_band   {MATERIAL} -np {ncore} --NoGnuplot",  # band plot
        f"{bindir}/job_magnon -np {ncore} {MATERIAL}",              # magnon calculation
        "gnuplot mag3d.glt",
        "gnuplot r_k.glt",
        "gnuplot wan_bandplot.glt"
    ])
    # bcc Fe in the simple cubic cell of two atoms: the bands of the bcc cell are folded and degenerate, and K(q,omega) and
    # R(q,omega) change with the compiler and the number of ranks (K by up to 7 %, a magnon peak by up to 6 % between
    # gfortran and nvfortran; R has poles).  So K is compared loosely, and for R the positions of the magnon peaks.
    # The reference is of kt1, nvfortran, -np 60 (2026-08-19).  (2026-09-30 02:10: the comparison of R point by point, and of K
    # to 1e-3, failed on kt1 and kr7 with -np 8 although the peak positions agreed to 2.5 meV)
    print(dat1,end=': ')
    skip_w0 = lambda line: len(line.split()) >= 5 and abs(float(line.split()[4])) < 1e-6   # omega = 0
    tall+=test2_check(testdir+'/'+dat1, workdir+'/'+dat1, abs_tol=0.5, rel_tol=0.1, skipcond=skip_w0)
    print(dat2,end=': ')
    tall+=peak_check(testdir+'/'+dat2, workdir+'/'+dat2, qcol=3, wcol=4, vcol=6, wmin=1e-6, wmax=1.5, rel_tol=0.1, abs_tol=0.003)
    message1=f'''
    ==========================================================================
    Magnon calculation finished.
      TrKpm.syml001: K(q,omega) trace
      TrRpm.syml001: R(q,omega) trace
      *.pdf generated by gnuplot
    To view: evince {workdir}/magnon3d_100.pdf
    Compare with previous: {testdir}/eps/*.eps
    ==========================================================================
    '''
    print(message1)
    return tall
