#!/bin/csh

echo ------ effective mom ---------------------
foreach xxx (`ls ChiPM[0-9]*[0-9].nolfc.mat`)
echo ChiPMhead $xxx |calj_nlfc_mat |grep 'e mom'
end

echo ------ interp ---------------------
foreach xxx (`ls ChiPM[0-9]*[0-9].nolfc.mat`)
echo ChiPMhead $xxx |calj_interp_mat |grep 'FWHM='
end

echo ------ hermitian ---------------------
foreach xxx (`ls ChiPM[0-9]*[0-9].nolfc.mat`)
echo ChiPMhead $xxx |calj_nlfc_mat |grep search1
end

echo ------JMAT---------------------
rm Jmat0 Jmat
foreach xxx (`ls ChiPM*.nolfc.mat`)
echo ChiPMhead $xxx |calj_nlfc_mat |grep 'JJMAT' >> Jmat0
end
sed 's/JJMAT:  //g' Jmat0 >Jmat
#echo ChiPMhead ChiPM0001.nolfc.mat 2|calj_nlfc |grep "\!\!" >>Jmat

echo ------MMAT---------------------
rm Mmat0 Mmat
foreach xxx (`ls ChiPM*.nolfc.mat`)
echo ChiPMhead $xxx |calj_nlfc_mat |grep MMAT >> Mmat0
end
sed 's/MMAT:  //g' Mmat0 >Mmat

echo ------Mmm---------------------
foreach xxx (`ls ChiPM*.nolfc.mat`)
echo ChiPMhead $xxx |calj_nlfc_mat |grep Mmm
end

