#!/bin/csh -f
######## <q|\chi^+-|q> calculation.
set n = $0
set nfpgw = ${n:h}
echo $nfpgw
echo $argv[1]
setenv LMJOB $argv[1]
rm -f NoCore QPU*

### Get LATTC and SYMOPS
echo 0 |$nfpgw/lmfgw --novxc  $argv[1]   > llmfgw00

### Add q points  to Q0P file.  ! read <QforEPS> <QforEPSL> in GWinput
echo 2|$nfpgw/qg4gw              >lqg4gw02

#eigenvalues for micro-tetrahedron method.
if(-e Qmtet) then
  mv Qmtet Qeigval 
  echo 5 |$nfpgw/lmfgw --novxc  $argv[1] > llmfgw_eigval
  mv eigval eigmtet
endif
echo 1 |$nfpgw/lmfgw --novxc  $argv[1]   > llmfgw01
#@ exinfo = `tail -3 llmfgw01 | head -1|awk '{print $2}'`
set exinfo = $?
if($exinfo == 0 ) then
  echo " OK! lmfgw mode=1 "
else
  echo `tail -3 llmfgw01 `
endif
echo $argv[1]|$nfpgw/lmf2gw      >llmf2gw
echo 1|$nfpgw/rdata4gw_v2        >lrdata4gw

echo 1|$nfpgw/heftet             >leftet  # get EFERMI
echo 8|$nfpgw/hbasfp0            >lbas
echo 202|$nfpgw/hvccfp0          >lvcc	
echo 10222|$nfpgw/hx0fp0        >lx0




 

