#!/bin/csh
set n = $0 
set fpgw = ${n:h}
echo $fpgw

if(-e SEXU) mv SEXU SEXU.bk
if(-e SEXD) mv SEXD SEXD.bk

touch EXspTEST
# This takes some minutes as same as echo 1|hsfp0.
echo 1|$fpgw/hsfp0 >lsxtest
mv GWinput GWinput.bk

echo ' esmr(Ry) efermi(Ry) Sx1(eV)  Sx2 ... '
rm -rf EXesmr*
#-----------------------
foreach esmr (0.001 0.002 0.003 0.004 0.005 0.006 0.007 0.008 0.009 0.010 0.015 0.020 0.030 0.040 0.080 0.100 0.150 0.200 0.250 0.300)
cat  <<EOF > GWinput
esmr $esmr
EOF
cat GWinput.bk >>GWinput 

$fpgw/hef >& lef 
echo -n '   ' $esmr
grep 'ef    =' lef |awk '{printf "%10.6f",$3}'
grep 'Sx(eV)' lef  |awk '{printf "%10.4f",$12}'
echo ' '
mv lef lef.$esmr
end

#-----------------------
mv EXspTEST EXspTEST.bk
mv GWinput.bk GWinput


 


