#!/bin/csh
set n = $0 
set fpgw = ${n:h}
echo $fpgw

mv SEXU SEXU.bk
if(-e SEXD) mv SEXD SEXD.bk

cp GWIN GWIN.bk
touch EXspTEST
# This takes some minutes as same as echo 1|hsfp0.
#echo 1|$fpgw/hsfp0 >lsxtest200

echo ' esmr(Ry) efermi(Ry) Sx1(eV)  Sx2 ... '
rm -rf EXesmr*
#-----------------------
foreach esmr (0.005 0.010 0.015 0.020 0.025 0.030 0.040 0.050 0.080 0.100 0.120 0.150 0.180 0.200 0.220 0.250 0.300)
awk '{ if(NR==11) print '"$esmr"';else print $0 }' GWIN.bk> GWIN
$fpgw/hef >& lef 
echo -n '   ' $esmr
grep 'ef    =' lef |awk '{printf "%10.6f",$3}'
grep 'Sx(eV)' lef  |awk '{printf "%10.4f",$12}'
echo ' '
mkdir EXesmr$esmr
mv GWIN EXWT* lef EXesmr$esmr
end

#-----------------------
mv GWIN.bk GWIN
mv SEXU.bk SEXU
if(-e SEXD.bk) mv SEXD.bk SEXD
rm EXspTEST


 





 


