#!/bin/csh
# --------------------------------
# Get band plot of GW calculations.
#
# Required inputs are 
#  SEXU SECU SEXcoreU
#  *.mas *.rst *  QPNT SYML
#---------------------------------------------
set n = $0
set nfpgw = ${n:h}
echo $nfpgw

echo $argv

#exit
if( (! -e SYML) ||-z SYML) then
  echo --- No SYML file \(it might be size zero\)!
  exit
endif
echo ' '
echo ' 'hqpe \(or hqpemetal\) to fix the zero level is supposed to be already done. OK\?
echo ' '
echo ' '----- We use SYML --from here------------
cat SYML
echo ' '
echo ' '------------------- to  here------------
echo 0 | $nfpgw/lmfgw $argv[1] `awk '{printf "%s", $0}' $argv[2]` >llmfgw00
echo 3 | $nfpgw/qg4gw    >lqg4gw
echo 4 | $nfpgw/lmfgw $argv[1] `awk '{printf "%s", $0}' $argv[2]` >llmfgw04
foreach ext (UP DN)
if(-e LBAND.$ext) then
  echo LBAND.$ext
  cp LBAND.$ext LBAND
  if(-e TOTE2.$ext) cp TOTE2.$ext TOTE2
  $nfpgw/hbndout  >lbndout.$ext 
  $nfpgw/bandplot      #This is a script calling bandfp which generate ps file.
  foreach fin (BandLDA BandQP1 BandQP2 BandGWpoint BandQpoint) 
    if(-e $fin ) mv $fin $fin.$ext
  end
  foreach fout (BandLDA BandQP1 BandQP2)
    if(-e $fout.ps) mv $fout.ps $fout.$ext.ps
  end	
endif
end
if(-e LBAND) rm LBAND 
if(-e TOTE2) rm TOTE2




 
