#!/usr/bin/python
import sys
import string
import os
print
print "========= plotg  ========="
try:
	print "Readin file =     ",sys.argv[1]
except:	
	print "usage: plotg QPUfile ix "
	print "   ix=0 for LDA  "
	print "   ix=1 for QP   "
	print "   ix=2 for QPnoZ"
	sys.exit()

ibmin_o = 3
ibmax_o = 16
ibmin_u  =17
ibmax_u  =74


print "setting Occu_min  Occu_max =   ",ibmin_o,ibmax_o
print "setting Uoccu_min Uoccu_max=   ",ibmin_u,ibmax_u

fr = open(sys.argv[1],'rt')
oxx=fr.read()
oxx=string.split(oxx,'\n')
fr.close()
ispin=0
nx = 10
nx = string.atoi(sys.argv[2])+10
if(nx==10): aaa= ' LDA'
if(nx==11): aaa= ' QP1'
if(nx==12): aaa= ' QP2'
try:
	print "OK  for   ",aaa
except:
	print 'nx=',nx

ix=0

fdname = "dat.uocc"
fwd=open(fdname,'wt')
init=0

#######################################################
print '\n--------For unoccupied--------------'

for ib in range(ibmin_u,ibmax_u+1,1):
	ibr=0
	for iline in oxx:
		try:
			ibb=string.atoi(string.split(iline)[3])
			if ibb==ib:
				ibr=ibr+1
				print ib,
				out='%d %s !iband= %d' % (ibr, string.split(iline)[nx],ib)
				fwd.write(out+'\n')
				init=1
		except:
			pass
	fwd.write('\n')
#			ix=ix+1
fwd.close()

#######################################################
print '\n--------For occupied--------------'

fdname = "dat.occ"
fwd=open(fdname,'wt')
init=0
for ib in range(ibmin_o,ibmax_o+1,1):
	ibr=0
	for iline in oxx:
		try:
			ibb=string.atoi(string.split(iline)[3])
			if ibb==ib:
				ibr=ibr+1
				print ib,
				out='%d %s !iband= %d' % (ibr, string.split(iline)[nx],ib)
				fwd.write(out+'\n')
				init=1
		except:
			pass
	fwd.write('\n')
#			ix=ix+1
fwd.close()


fname = "dat.gpl"
fw=open(fname,'wt')
out = 'set title "%s %s"\n' % (sys.argv[1],aaa)
#Range
out= out+ 'set yrange [-20:150]\n'
#out= out+ 'set yrange [-20:15]\n'
out= out+ 'set pointsize 2\n'
out= out+ 'plot "dat.uocc" using 1:2 with linespoints 2 \\\n'
out= out+ '  ,"dat.occ" using 1:2 with linespoints 1\n'
#out='plot "dat" using 1:2 with lines -1\npause -1\n'
fw.write(out)
fw.close()
os.system("gnuplot -persist %s" % fname)

	
