* MAE calculation based on FePt and MnGa. Force theorem Liqin PhysRevB.99.054418,
** implementation of SOC axis
I recommend you to see ovarall calling flow  lmfp->bndfp->m_band_cal and m_subze_bzintegration.
sev is the band energy.
At m_bandcal_init, we set up Hamiltonian at m_bandcal.F@L142
          hamm(:,:,1:2)= hamm(:,:,1:2)+hammhso(:,:,1:2) !spin-diag SOC elements (1,1), (2,2) added
          hamm(:,:, 3) = hammhso(:,:,3) !spin-offdiagonal SOC elements (1,2) added
So, things very clear now. 
SO part is just hammhso(:,:,isp) where isp=3 is right-upper block of spin matrix.
Recent version is quite clean rather than old version.
hammhso is generated aughsoc in m_bandcal.
Look into hammhso if necessary (T.Kotani implemented only 
the case 001 and 110, but it should be easy to make it general case).
SOC axis is set by HAM_SOCAXIS

** FePt test
MAE test force theorem
creat ctrls.fept by hand
>ctrlgenM1.py fept
Set LMXA=6 
nk 16 16 12
nspin=2 
MMOM=0,0,2.2 
xcfun=103 !GGA-PBE
so=0
NOTE: digits of atomic position is as accurate as possible (

# mpirun -np 4 ~/ecalj/SRC/exec/lmf-MPIK fept --phispinsym -vso=0 |tee llmf
Base line self-consistent calculation. The end of save file shows
>c so=0 mmom=3.2521968 ehf(eV)=-535698.5395703 ehk(eV)=-535698.5395982 sev(eV)=-367.9715004

# Then you have to modify ctrl file 
 SYMGRP e
 NOINV  T  (probably needed?--at least safer setting)
 %const soa1=0 soa2=0 soa3=1 
      SOCAXIS={soa1} {soa2} {soa3}   (!spin axis. this is in HAM category)
# mpirun -np 4 ~/ecalj/SRC/exec/lmf-MPIK fept --phispinsym -vso=0 --quit=band |tee llmfso0
>i so=0 mmom=3.2522553 ehf(eV)=-535698.5395688 ehk(eV)=-535698.5395972 sev(eV)=-367.9707584
(not rewrite rst file. Just perturbation from the last result).
sev is the band energy for the potential in rst file.

# 001 direction SO=1
mpirun -np 4 ~/ecalj/SRC/exec/lmf-MPIK fept --phispinsym --quit=band -vso=1 -vsoa1=0 -vsoa2=0 -vsoa3=1
>  HAM_SOCAXIS       opt    r8v      3,  3,   *,  3       0 0 1
is shown at the beginig of console output
A line is added to save.fept
>i so=1 soa1=0 soa2=0 soa3=1 mmom=3.2189814 ehf(eV)=-535698.8432677 ehk(eV)=-535698.8338371 sev(eV)=-368.2744573
sev is the band energy for the potential in rst file in addition to the SO term

# 110 direction SO=1
A line is added to save.fept
mpirun -np 4 ~/ecalj/SRC/exec/lmf-MPIK fept --phispinsym --quit=band -vso=1 -vsoa1=1 -vsoa2=1 -vsoa3=0
>i so=1 soa1=1 soa2=1 soa3=0 mmom=3.2216341 ehf(eV)=-535698.8404701 ehk(eV)=-535698.8316219 sev(eV)=-368.2716597

-----------
The difference of sev is -368.2744573+368.2716597= 0.0027976= 2797 micro eV.

** MnGa
Similar procedure shows (old version of save file output in Ry) 
>mpirun -np 4 lmf-MPIK mnga -vso=0 --phispinsym >llmfso0
c so=0 mmom=2.4082439 ehf=-6195.6056894 ehk=-6195.6056905
i so=0 mmom=2.4082689                      ehf=-6195.605 6905 ehk=-6195.6056917 sumev=  -32.994 029 
i so=1 soa1=0 soa2=0 soa3=1 mmom=2.4094348 ehf=-6195.607 1509 ehk=-6195.607152  sumev=  -32.995 490 
i so=1 soa1=1 soa2=1 soa3=0 mmom=2.4091936 ehf=-6195.607 1208 ehk=-6195.607122  sumev=  -32.995 459
Gives 421 micro eV (xcfun=1).
