#!/bin/sh
#for xx in  2; do #1 2 3 4 5 6 7 8; do
for xx in  14 15; do
export machine=node$xx 
echo rsh -n $machine "export PATH=$PATH;nohup pqd $xx >& /dev/null &"
rsh -n $machine "export PATH=$PATH;nohup pqd $xx >& /dev/null &"
done
exit

#echo rsh -n dob$xx "export PATH=$PATH;pqd $xx >& /dev/null &"
#rsh -n dob$xx "export PATH=$PATH;pqd $xx >& /dev/null &"




