#!/bin/bash
### See $1:fsmom and $2:rstar
jobid=$1$2$3$4`basename $0`
echo $jobid
temp2=temp2.$jobid
temp1=temp1.$jobid
temp0=temp0.$jobid
work=work.$jobid
pushd .

mkdir $work
cd    $work
work=`pwd`

# set common part
echo $* > $temp0
# for initial condition
cat << 'IIIII1' > $temp1.init
dirhead = 'INIT,pwe,'
IIIII1

# for main calculation
cat << 'IIIII2' > $temp2.init
#### for main calculations
plat='PLAT=1 0 0 0 1 0 0 0 1'
symgrp= 'SYMGRP i'
dirhead = 'DimerCubeSymi,pwe,'
setting['JOBLIST___']=\
'''
echo "runnig main"
lmf --rs=1,1,1,0,0 dimer $arguments0 -vdis=$dis > llmf,'dis='$dis
rm -f {mixm}.dimer
'''
IIIII2

### initial condition calculation
cat $temp0       >  $temp1
cat $temp1.init  >> $temp1
echo "pwe=0"     >> $temp1
job_molecule_ini.py $temp1 $jobid
d0=`cat dname1.$jobid`.`cat dname2.$jobid`
mkdir ../$d0
mv   ctrl.dimer ../$d0
cd   ../$d0
bash ctrl.dimer
cp rst.dimer $work/rst.dimer.$jobid

### main job ###################
for pwe in 0 1 2 3 4 5 6 7 8 9 10
do
cd $work
pwd
cat $temp0       > $temp2.$pwe
cat $temp2.init >> $temp2.$pwe
echo "pwe=$pwe" >> $temp2.$pwe
job_molecule_dis2.py $temp2.$pwe $jobid
d1=`cat dname1.$jobid`
d2=`cat dname2.$jobid`
mkdir ../$d1
mkdir ../$d1/$d2
cd    ../$d1/$d2
mv    $work/ctrl.dimer  .
cp    $work/rst.dimer.$jobid ./rst.dimer
bash ctrl.dimer 
cp   rst.dimer $work/rst.dimer.$jobid
done

popd
