#!/bin/bash
if [ $# -ne 3 ]; then
  echo "this is for Total DOS plot. tdos.*.glt for gnuplot is generated."
  echo "Usage: >job_tdos material_id -np 4" 1>&2
  exit 1
fi
MPI_SIZE=1
if [ $2 != "-np" ]; then
  echo "An example of usage: job_tdos si -np 4"
else
  MPI_SIZE=$3
fi
echo $MPI_SIZE
n=$0
lmdir=${n%/*}
ddd=$1
mpirun -np $MPI_SIZE $lmdir/lmf-MPIK $ddd --tdos    |tee llmf_tdos
num=`head -2 dos.tot.$ddd |tail -n 1|wc -w`

ufileg=tdos.${ddd}.glt
echo '#!/usr/bin/gnuplot -persist' > ${ufileg}
echo set title \"Total DOS\" >> ${ufileg}
echo set xlabel \" eV \(zero at the Fermi energy or top of valence\)\" >> ${ufileg}
echo set ylabel \" number of states/\(cell Ry\)\" >> ${ufileg}

if [ $num == '3' ]; then
    echo 'spin=2'
    echo set yrange [-50:50] >> ${ufileg}
    cat <<EOF >>${ufileg}
plot 'dos.tot.${ddd}' u (\$1*13.605):2 w l, '' u (\$1*13.605):(-\$3) w l
EOF
else
    echo 'spin=1'
    echo set yrange [0:50] >> ${ufileg}
    cat <<EOF >>${ufileg}
plot 'dos.tot.${ddd}' u (\$1*13.605):2 w l
EOF
fi

gnuplot -persist ${ufileg}
echo To repeat, gnuplot -persist ${ufileg}

exit



