#!/bin/bash
MPI_SIZE=1
if [ $2 != "-np" ]; then
  echo "An example of usage: job_band_nspin1 si -np 4"
else
  MPI_SIZE=$3
fi
echo $MPI_SIZE
ddd=$1
n=$0
lmdir=${n%/*}
mpirun -np $MPI_SIZE $lmdir/lmf-MPIK $ddd --quit=band    |tee llmf_ef
mpirun -np $MPI_SIZE $lmdir/lmf-MPIK --band:fn=syml $ddd  |tee llmf_band
# -18,16 means the range to plot
echo -18,16,15,15|$lmdir/plbnds -fplot -gnuplot -ef=0 -scl=13.605  $ddd
cp  bnds.gnu bnds.gnu.${ddd}
gnuplot -persist bnds.gnu.${ddd}
echo If you like, edit and run 'job_band, or gnuplot -persist bnds.gnu.'${ddd}


