#!/bin/bash
#!/bin/bash
if [ $# -ne 1 ]; then
  echo "this is for PDOS plot. tdos.*.glt for gnuplot is generated."
  echo "Usage: >job_tdos material_id" 1>&2
  exit 1
fi

ddd=$1
cat <<EOF >SYMOPS
          48
   1   1  0.0000000000000000E+00  0.0000000000000000E+00  0.0000000000000000E+00
  0.1000000000000000E+01  0.0000000000000000E+00  0.0000000000000000E+00
  0.0000000000000000E+00  0.1000000000000000E+01  0.0000000000000000E+00
  0.0000000000000000E+00  0.0000000000000000E+00  0.1000000000000000E+01
EOF
echo 1|qg4gw >lqg4gw_symops_e
lmf   $ddd --pdos    |tee llmf_pdos
lmdos $ddd --pdos    |tee llmdos_pdos

cat <<EOF

===== PDOS file structure (dos.isp*) =========================
(add +1 since, 1st columun is energy in these pdos files.)
  For s,p,d,f the indices 1-16 correspond to:
      index   l    m     polynomial
         1    0    0        1
    -----------------------------
         2    1   -1        y
         3    1    0        z
         4    1    1        x
    -----------------------------
         5    2   -2        xy
         6    2   -1        yz
         7    2    0        3z^2-1
         8    2    1        xz
         9    2    2        x^2-y^2
    -----------------------------
         10   3   -3        y(3x^2-y^2)
         11   3   -2        xyz
         12   3   -1        y(5z^2-1)
         13   3    0        z(5z^2-3)
         14   3    1        x(5z^2-1)
         15   3    2        z(x^2-y^2)
         16   3    3        x(x^2-3y^2)
   ------------------------
   higher is lm ordered. See Ylm definition in lmto/fpgw doc.
==============================================================
EOF

for ufile in `ls dos.isp1.site*.${ddd}`
do
  dfile=`echo $ufile |sed -e 's/isp1/isp2/g'`
  ufileg=pdos.`echo $ufile |sed -e 's/dos.isp1.//g'`.glt
  echo '#!/usr/bin/gnuplot -persist' > ${ufileg}

  echo $ufile 
  echo set title \"PDOS s\,p\,d\,f\,g division in MuffinTin\" >> ${ufileg}
  echo set xlabel \" eV \(zero at the Fermi energy or top of valence\)\" >> ${ufileg}
  echo set ylabel \" number of states/\(cell Ry\)\" >> ${ufileg}

  if [ -e $dfile ] ; then
      echo set yrange [-50:50] >> ${ufileg}
      echo plot \"${ufile}\" u \(\$1*13.605\):\(\$2\) w l, \'\' u \(\$1*13.605\):\(\$3+\$4+\$5\) w l, \"\" u \(\$1*13.605\):\(\$6+\$7+\$8+\$9+\$10\) w l, \"\" u \(\$1*13.605\):\(\$11+\$12+\$13+\$14+\$15+\$16+\$17\) w l, \"\" u \(\$1*13.605\):\(\$18+\$19+\$20+\$21+\$22+\$23+\$24\+\$25\+\$26\) w l,          \"${dfile}\" u \(\$1*13.605\):\(-\$2\) w l, \'\' u \(\$1*13.605\):\(-\$3-\$4-\$5\) w l, \"\" u \(\$1*13.605\):\(-\$6-\$7-\$8-\$9-\$10\) w l, \"\" u \(\$1*13.605\):\(-\$11-\$12-\$13-\$14-\$15-\$16-\$17\) w l, \"\" u \(\$1*13.605\):\(-\$18-\$19-\$20-\$21-\$22-\$23-\$24\-\$25\-\$26\) w l  >> ${ufileg} 

  else

      echo set yrange [0:50] >> ${ufileg}
      echo plot \"${ufile}\" u \(\$1*13.605\):\(\$2\) w l, \'\' u \(\$1*13.605\):\(\$3+\$4+\$5\) w l, \"\" u \(\$1*13.605\):\(\$6+\$7+\$8+\$9+\$10\) w l, \"\" u \(\$1*13.605\):\(\$11+\$12+\$13+\$14+\$15+\$16+\$17\) w l, \"\" u \(\$1*13.605\):\(\$18+\$19+\$20+\$21+\$22+\$23+\$24\+\$25\+\$26\) w l  >> ${ufileg}
  fi

  gnuplot -p ${ufileg}
done


echo --------------------------------
echo ' ' NOTE: For your purpose, you have to edit pdos.site.foobar.gnu files for gnuplot.
echo '      ' pdos date sotred in dos.isp... are ordered in Ylm \(1st is energy in Ry\).
exit
