%!PS-Adobe-2.0 generated by plsub.f ...
/inch{72 mul}def /cm{72 mul 2.54 div}def 0 0 translate  1 1 scale
/tails 0.4 def % set to 0 for blanking chars without tails
/lto{lineto}def % shorthand for lineto
/blank-on{/b 1 def}def /blank-off{/b 0 def}def blank-on
/smaller 0.67 def % sub/superscripts are this much smaller
/shift   0.33 def % and are shifted by this much of the char height
/hshift  0.10 def % horizontal space, fraction of char height
% push size then font onto stack to select font
/choosefont {findfont exch scalefont setfont} def
% paint object on top of stack at current position
/debug {dup /str 30 string def str cvs show} def
% finding width of longest ordinate label (current width on stack) ...
/max 0 def /mxw{/w exch def w max gt {/max w def} if}def
% string centring, justification in the four quadrants
% and absicca and ordinate label centring ...
/showru{show}def
/showcu{dup stringwidth pop 2 div neg 0 rmoveto show}def
/showlu{dup stringwidth pop neg 0 rmoveto show}def
/showrc{0 h 2 div neg rmoveto show}def
/showcc{dup stringwidth pop 2 div neg h 2 div neg rmoveto show}def
/showlc{dup stringwidth pop neg h 2 div neg rmoveto show}def
/showrd{0 h neg rmoveto show}def
/showld{dup stringwidth pop neg h neg rmoveto show}def
/showcd{dup stringwidth pop 2 div neg h neg rmoveto show}def
/showa{gsave fontsize /Symbol choosefont
       dup stringwidth pop 2 div neg h 1.5 mul neg rmoveto show grestore}def
/showA{gsave fontsize /Symbol choosefont
       dup stringwidth pop 2 div neg h 0.5 mul rmoveto show grestore}def
/showo{gsave fontsize /Symbol choosefont
       dup stringwidth pop dup mxw h 2 div add neg h 2 div neg rmoveto show grestore}def
/showO{gsave fontsize /Symbol choosefont
       dup h 2 div h 2 div neg rmoveto show grestore}def
% aliases for pslabl ...
/show0{showcc}def /show1{show}def /show2{showrd}def /show3{showld}def
/show4{showlu}def
% newline macros for horizontal and vertical labelling ...
/newlinehf{currentpoint fontsize sub moveto}def
/newlinevf{currentpoint exch fontsize add exch moveto}def
/newlinehr{currentpoint fontsize add moveto}def
/newlinevr{currentpoint exch fontsize sub exch moveto}def
/savecurrentpoint {currentpoint /ybak exch def /xbak exch def} def
% end preamble ...

 % FONT: set font and fontsize ..
/font /Times-Roman def /fontsize  24 def
/h fontsize 0.6 mul def % h is about char height
fontsize font choosefont
% pltsts:  set  logx=F  logy=F
% pltstp: frame corners (GU): lb= (0 0)  rt = (.464 1)
  1.5 setlinewidth 1 setlinejoin [7.2 3.6 2.16 3.6] 0 setdash
% --- FRME : axes at x=0 1  y=-15 15  bold=3
/max 0 def 
  1.5 setlinewidth 1 setlinejoin [ ] 0 setdash
newpath 144 144 moveto 327.7 144 lto
 327.7 540 lto
 144 540 lto
 144 144 lto closepath gsave 1 1 1 setrgbcolor fill grestore stroke
newpath 144 144 moveto 144 153.9 lto stroke
newpath 162.4 144 moveto 162.4 149.9 lto stroke
newpath 180.7 144 moveto 180.7 153.9 lto stroke
newpath 199.1 144 moveto 199.1 149.9 lto stroke
newpath 217.5 144 moveto 217.5 153.9 lto stroke
newpath 235.9 144 moveto 235.9 149.9 lto stroke
newpath 254.2 144 moveto 254.2 153.9 lto stroke
newpath 272.6 144 moveto 272.6 149.9 lto stroke
newpath 291 144 moveto 291 153.9 lto stroke
newpath 309.4 144 moveto 309.4 149.9 lto stroke
newpath 327.7 144 moveto 327.7 153.9 lto stroke
newpath 144 540 moveto 144 530.1 lto stroke
newpath 162.4 540 moveto 162.4 534.1 lto stroke
newpath 180.7 540 moveto 180.7 530.1 lto stroke
newpath 199.1 540 moveto 199.1 534.1 lto stroke
newpath 217.5 540 moveto 217.5 530.1 lto stroke
newpath 235.9 540 moveto 235.9 534.1 lto stroke
newpath 254.2 540 moveto 254.2 530.1 lto stroke
newpath 272.6 540 moveto 272.6 534.1 lto stroke
newpath 291 540 moveto 291 530.1 lto stroke
newpath 309.4 540 moveto 309.4 534.1 lto stroke
newpath 327.7 540 moveto 327.7 530.1 lto stroke
newpath 144 157.2 moveto 146.8 157.2 lto stroke
newpath 144 183.6 moveto 148.6 183.6 lto stroke
gsave blank-on    144.0   183.6 moveto (-12) showo  grestore
newpath 144 210 moveto 146.8 210 lto stroke
newpath 144 236.4 moveto 148.6 236.4 lto stroke
gsave blank-on    144.0   236.4 moveto (-8) showo  grestore
newpath 144 262.8 moveto 146.8 262.8 lto stroke
newpath 144 289.2 moveto 148.6 289.2 lto stroke
gsave blank-on    144.0   289.2 moveto (-4) showo  grestore
newpath 144 315.6 moveto 146.8 315.6 lto stroke
newpath 144 342 moveto 148.6 342 lto stroke
gsave blank-on    144.0   342.0 moveto (0) showo  grestore
newpath 144 368.4 moveto 146.8 368.4 lto stroke
newpath 144 394.8 moveto 148.6 394.8 lto stroke
gsave blank-on    144.0   394.8 moveto (4) showo  grestore
newpath 144 421.2 moveto 146.8 421.2 lto stroke
newpath 144 447.6 moveto 148.6 447.6 lto stroke
gsave blank-on    144.0   447.6 moveto (8) showo  grestore
newpath 144 474 moveto 146.8 474 lto stroke
newpath 144 500.4 moveto 148.6 500.4 lto stroke
gsave blank-on    144.0   500.4 moveto (12) showo  grestore
newpath 144 526.8 moveto 146.8 526.8 lto stroke
newpath 327.7 157.2 moveto 325 157.2 lto stroke
newpath 327.7 183.6 moveto 323.2 183.6 lto stroke
newpath 327.7 210 moveto 325 210 lto stroke
newpath 327.7 236.4 moveto 323.2 236.4 lto stroke
newpath 327.7 262.8 moveto 325 262.8 lto stroke
newpath 327.7 289.2 moveto 323.2 289.2 lto stroke
newpath 327.7 315.6 moveto 325 315.6 lto stroke
newpath 327.7 342 moveto 323.2 342 lto stroke
newpath 327.7 368.4 moveto 325 368.4 lto stroke
newpath 327.7 394.8 moveto 323.2 394.8 lto stroke
newpath 327.7 421.2 moveto 325 421.2 lto stroke
newpath 327.7 447.6 moveto 323.2 447.6 lto stroke
newpath 327.7 474 moveto 325 474 lto stroke
newpath 327.7 500.4 moveto 323.2 500.4 lto stroke
newpath 327.7 526.8 moveto 325 526.8 lto stroke
  1.5 setlinewidth 1 setlinejoin [7.2 3.6 2.16 3.6] 0 setdash
% ---  xt1=0 tsx=.1 mtx=2  yt1=-14 tsy=2 mty=2
 % FRME: Label axes ...
   235.9   144.0 moveto 0 h 3 mul neg rmoveto
   144.0   342.0 moveto h 2 mul max add neg 0 rmoveto
 % FRME: adding title ...
   327.7   540.0 moveto 0 h 0.5 mul rmoveto
% --- plcrv: new curve, 2 pts lt 2 bold 3 col= 0 0 0 len=(7.2 3.6 2.16 3.6) ---
gsave newpath 144 144 moveto 144 540 lineto
              327.7 540 lineto 327.7 144 lineto closepath clip
 0 0 0 setrgbcolor
newpath 144 342 moveto 327.7 342 lto

 stroke grestore
  1.5 setlinewidth 1 setlinejoin [ ] 0 setdash
% --- plcrv: new curve, 21 pts lt 1 bold 3 ---
gsave newpath 144 144 moveto 144 540 lineto
              327.7 540 lineto 327.7 144 lineto closepath clip
newpath 144 271.8 moveto 153.2 271.6 lto
    162.4    271.1 lto
    171.6    270.1 lto
    180.7    268.5 lto
    189.9    266.1 lto
    199.1    262.8 lto
    208.3    258.7 lto
    217.5    253.9 lto
    226.7    248.9 lto
    235.9    243.8 lto
    245.1    238.9 lto
    254.2    234.2 lto
    263.4    230.0 lto
    272.6    226.3 lto
    281.8    223.0 lto
    291.0    220.4 lto
    300.2    218.3 lto
    309.4    216.7 lto
    318.6    215.8 lto
 327.7 215.5 lto

 stroke grestore
  1.5 setlinewidth 1 setlinejoin [ ] 0 setdash
% --- plcrv: new curve, 21 pts lt 1 bold 3 ---
gsave newpath 144 144 moveto 144 540 lineto
              327.7 540 lineto 327.7 144 lineto closepath clip
newpath 144 299.1 moveto 153.2 299.1 lto
    162.4    299.2 lto
    171.6    299.4 lto
    180.7    299.7 lto
    189.9    300.0 lto
    199.1    300.4 lto
    208.3    298.9 lto
    217.5    297.2 lto
    226.7    296.4 lto
    235.9    296.1 lto
    245.1    296.2 lto
    254.2    296.5 lto
    263.4    296.9 lto
    272.6    297.4 lto
    281.8    298.0 lto
    291.0    298.4 lto
    300.2    298.9 lto
    309.4    299.2 lto
    318.6    299.4 lto
 327.7 299.4 lto

 stroke grestore
  1.5 setlinewidth 1 setlinejoin [ ] 0 setdash
% --- plcrv: new curve, 21 pts lt 1 bold 3 ---
gsave newpath 144 144 moveto 144 540 lineto
              327.7 540 lineto 327.7 144 lineto closepath clip
newpath 144 299.1 moveto 153.2 299.1 lto
    162.4    299.2 lto
    171.6    299.4 lto
    180.7    299.7 lto
    189.9    300.0 lto
    199.1    300.4 lto
    208.3    300.7 lto
    217.5    301.1 lto
    226.7    301.4 lto
    235.9    301.6 lto
    245.1    301.7 lto
    254.2    301.7 lto
    263.4    301.4 lto
    272.6    301.1 lto
    281.8    300.7 lto
    291.0    300.3 lto
    300.2    300.0 lto
    309.4    299.7 lto
    318.6    299.5 lto
 327.7 299.4 lto

 stroke grestore
  1.5 setlinewidth 1 setlinejoin [ ] 0 setdash
% --- plcrv: new curve, 21 pts lt 1 bold 3 ---
gsave newpath 144 144 moveto 144 540 lineto
              327.7 540 lineto 327.7 144 lineto closepath clip
newpath 144 318.5 moveto 153.2 318.4 lto
    162.4    318.1 lto
    171.6    316.0 lto
    180.7    310.4 lto
    189.9    305.5 lto
    199.1    301.6 lto
    208.3    300.7 lto
    217.5    301.1 lto
    226.7    301.4 lto
    235.9    301.6 lto
    245.1    301.7 lto
    254.2    301.7 lto
    263.4    301.4 lto
    272.6    301.1 lto
    281.8    300.7 lto
    291.0    300.3 lto
    300.2    300.0 lto
    309.4    299.7 lto
    318.6    299.5 lto
 327.7 299.4 lto

 stroke grestore
  1.5 setlinewidth 1 setlinejoin [ ] 0 setdash
% --- plcrv: new curve, 21 pts lt 1 bold 3 ---
gsave newpath 144 144 moveto 144 540 lineto
              327.7 540 lineto 327.7 144 lineto closepath clip
newpath 144 318.5 moveto 153.2 318.4 lto
    162.4    318.1 lto
    171.6    317.7 lto
    180.7    317.0 lto
    189.9    316.3 lto
    199.1    315.4 lto
    208.3    314.5 lto
    217.5    313.6 lto
    226.7    312.7 lto
    235.9    311.9 lto
    245.1    311.2 lto
    254.2    310.8 lto
    263.4    310.5 lto
    272.6    310.4 lto
    281.8    310.4 lto
    291.0    310.5 lto
    300.2    310.6 lto
    309.4    310.7 lto
    318.6    310.8 lto
 327.7 310.8 lto

 stroke grestore
  1.5 setlinewidth 1 setlinejoin [ ] 0 setdash
% --- plcrv: new curve, 21 pts lt 1 bold 3 ---
gsave newpath 144 144 moveto 144 540 lineto
              327.7 540 lineto 327.7 144 lineto closepath clip
newpath 144 327.2 moveto 153.2 325.6 lto
    162.4    321.4 lto
    171.6    317.7 lto
    180.7    317.0 lto
    189.9    316.3 lto
    199.1    315.4 lto
    208.3    314.5 lto
    217.5    313.6 lto
    226.7    312.7 lto
    235.9    311.9 lto
    245.1    311.2 lto
    254.2    310.8 lto
    263.4    310.5 lto
    272.6    310.4 lto
    281.8    310.4 lto
    291.0    310.5 lto
    300.2    310.6 lto
    309.4    310.7 lto
    318.6    310.8 lto
 327.7 310.8 lto

 stroke grestore
  1.5 setlinewidth 1 setlinejoin [ ] 0 setdash
% --- plcrv: new curve, 21 pts lt 1 bold 3 ---
gsave newpath 144 144 moveto 144 540 lineto
              327.7 540 lineto 327.7 144 lineto closepath clip
newpath 144 391.3 moveto 153.2 393.7 lto
    162.4    400.3 lto
    171.6    409.8 lto
    180.7    421.3 lto
    189.9    434.1 lto
    199.1    448.0 lto
    208.3    462.9 lto
    217.5    478.5 lto
    226.7    494.8 lto
    235.9    511.8 lto
    245.1    529.3 lto
    254.2    547.3 lto
    263.4    565.7 lto
    272.6    584.4 lto
    281.8    602.8 lto
    291.0    620.3 lto
    300.2    634.7 lto
    309.4    642.0 lto
    318.6    644.0 lto
 327.7 644.4 lto

 stroke grestore
% pltsts:  set  logx=F  logy=F
% pltstp: frame corners (GU): lb= (.464 0)  rt = (1 1)
  1.5 setlinewidth 1 setlinejoin [7.2 3.6 2.16 3.6] 0 setdash
% --- FRME : axes at x=0 1  y=-15 15  bold=3
/max 0 def 
  1.5 setlinewidth 1 setlinejoin [ ] 0 setdash
newpath 327.7 144 moveto 540 144 lto
 540 540 lto
 327.7 540 lto
 327.7 144 lto closepath gsave 1 1 1 setrgbcolor fill grestore stroke
newpath 327.7 144 moveto 327.7 153.9 lto stroke
newpath 349 144 moveto 349 149.9 lto stroke
newpath 370.2 144 moveto 370.2 153.9 lto stroke
newpath 391.4 144 moveto 391.4 149.9 lto stroke
newpath 412.6 144 moveto 412.6 153.9 lto stroke
newpath 433.9 144 moveto 433.9 149.9 lto stroke
newpath 455.1 144 moveto 455.1 153.9 lto stroke
newpath 476.3 144 moveto 476.3 149.9 lto stroke
newpath 497.5 144 moveto 497.5 153.9 lto stroke
newpath 518.8 144 moveto 518.8 149.9 lto stroke
newpath 540 144 moveto 540 153.9 lto stroke
newpath 327.7 540 moveto 327.7 530.1 lto stroke
newpath 349 540 moveto 349 534.1 lto stroke
newpath 370.2 540 moveto 370.2 530.1 lto stroke
newpath 391.4 540 moveto 391.4 534.1 lto stroke
newpath 412.6 540 moveto 412.6 530.1 lto stroke
newpath 433.9 540 moveto 433.9 534.1 lto stroke
newpath 455.1 540 moveto 455.1 530.1 lto stroke
newpath 476.3 540 moveto 476.3 534.1 lto stroke
newpath 497.5 540 moveto 497.5 530.1 lto stroke
newpath 518.8 540 moveto 518.8 534.1 lto stroke
newpath 540 540 moveto 540 530.1 lto stroke
newpath 327.7 157.2 moveto 330.9 157.2 lto stroke
newpath 327.7 183.6 moveto 333.1 183.6 lto stroke
newpath 327.7 210 moveto 330.9 210 lto stroke
newpath 327.7 236.4 moveto 333.1 236.4 lto stroke
newpath 327.7 262.8 moveto 330.9 262.8 lto stroke
newpath 327.7 289.2 moveto 333.1 289.2 lto stroke
newpath 327.7 315.6 moveto 330.9 315.6 lto stroke
newpath 327.7 342 moveto 333.1 342 lto stroke
newpath 327.7 368.4 moveto 330.9 368.4 lto stroke
newpath 327.7 394.8 moveto 333.1 394.8 lto stroke
newpath 327.7 421.2 moveto 330.9 421.2 lto stroke
newpath 327.7 447.6 moveto 333.1 447.6 lto stroke
newpath 327.7 474 moveto 330.9 474 lto stroke
newpath 327.7 500.4 moveto 333.1 500.4 lto stroke
newpath 327.7 526.8 moveto 330.9 526.8 lto stroke
newpath 540 157.2 moveto 536.8 157.2 lto stroke
newpath 540 183.6 moveto 534.7 183.6 lto stroke
newpath 540 210 moveto 536.8 210 lto stroke
newpath 540 236.4 moveto 534.7 236.4 lto stroke
newpath 540 262.8 moveto 536.8 262.8 lto stroke
newpath 540 289.2 moveto 534.7 289.2 lto stroke
newpath 540 315.6 moveto 536.8 315.6 lto stroke
newpath 540 342 moveto 534.7 342 lto stroke
newpath 540 368.4 moveto 536.8 368.4 lto stroke
newpath 540 394.8 moveto 534.7 394.8 lto stroke
newpath 540 421.2 moveto 536.8 421.2 lto stroke
newpath 540 447.6 moveto 534.7 447.6 lto stroke
newpath 540 474 moveto 536.8 474 lto stroke
newpath 540 500.4 moveto 534.7 500.4 lto stroke
newpath 540 526.8 moveto 536.8 526.8 lto stroke
  1.5 setlinewidth 1 setlinejoin [7.2 3.6 2.16 3.6] 0 setdash
% ---  xt1=0 tsx=.1 mtx=2  yt1=-14 tsy=2 mty=2
 % FRME: Label axes ...
   433.9   144.0 moveto 0 h 3 mul neg rmoveto
   327.7   342.0 moveto h 2 mul max add neg 0 rmoveto
 % FRME: adding title ...
   540.0   540.0 moveto 0 h 0.5 mul rmoveto
% --- plcrv: new curve, 2 pts lt 2 bold 3 col= 0 0 0 len=(7.2 3.6 2.16 3.6) ---
gsave newpath 327.7 144 moveto 327.7 540 lineto
              540 540 lineto 540 144 lineto closepath clip
 0 0 0 setrgbcolor
newpath 327.7 342 moveto 540 342 lto

 stroke grestore
  1.5 setlinewidth 1 setlinejoin [ ] 0 setdash
% --- plcrv: new curve, 21 pts lt 1 bold 3 ---
gsave newpath 327.7 144 moveto 327.7 540 lineto
              540 540 lineto 540 144 lineto closepath clip
newpath 327.7 215.5 moveto 338.4 215.9 lto
    349.0    217.1 lto
    359.6    219.2 lto
    370.2    222.0 lto
    380.8    225.5 lto
    391.4    229.8 lto
    402.0    234.7 lto
    412.6    240.2 lto
    423.3    246.2 lto
    433.9    252.3 lto
    444.5    258.4 lto
    455.1    263.9 lto
    465.7    268.3 lto
    476.3    271.4 lto
    486.9    273.2 lto
    497.5    274.1 lto
    508.2    274.5 lto
    518.8    274.6 lto
    529.4    274.6 lto
 540 274.6 lto

 stroke grestore
  1.5 setlinewidth 1 setlinejoin [ ] 0 setdash
% --- plcrv: new curve, 21 pts lt 1 bold 3 ---
gsave newpath 327.7 144 moveto 327.7 540 lineto
              540 540 lineto 540 144 lineto closepath clip
newpath 327.7 299.4 moveto 338.4 299.3 lto
    349.0    298.9 lto
    359.6    298.4 lto
    370.2    297.5 lto
    380.8    296.5 lto
    391.4    295.4 lto
    402.0    294.1 lto
    412.6    292.7 lto
    423.3    291.2 lto
    433.9    289.7 lto
    444.5    288.3 lto
    455.1    286.8 lto
    465.7    285.5 lto
    476.3    284.3 lto
    486.9    283.2 lto
    497.5    282.3 lto
    508.2    281.5 lto
    518.8    281.0 lto
    529.4    280.7 lto
 540 280.6 lto

 stroke grestore
  1.5 setlinewidth 1 setlinejoin [ ] 0 setdash
% --- plcrv: new curve, 21 pts lt 1 bold 3 ---
gsave newpath 327.7 144 moveto 327.7 540 lineto
              540 540 lineto 540 144 lineto closepath clip
newpath 327.7 299.4 moveto 338.4 299.5 lto
    349.0    299.8 lto
    359.6    300.3 lto
    370.2    301.0 lto
    380.8    301.9 lto
    391.4    302.9 lto
    402.0    304.1 lto
    412.6    305.4 lto
    423.3    304.8 lto
    433.9    304.6 lto
    444.5    305.2 lto
    455.1    307.1 lto
    465.7    310.7 lto
    476.3    315.0 lto
    486.9    316.5 lto
    497.5    317.6 lto
    508.2    317.9 lto
    518.8    318.1 lto
    529.4    318.3 lto
 540 318.3 lto

 stroke grestore
  1.5 setlinewidth 1 setlinejoin [ ] 0 setdash
% --- plcrv: new curve, 21 pts lt 1 bold 3 ---
gsave newpath 327.7 144 moveto 327.7 540 lineto
              540 540 lineto 540 144 lineto closepath clip
newpath 327.7 299.4 moveto 338.4 299.5 lto
    349.0    299.8 lto
    359.6    300.3 lto
    370.2    301.0 lto
    380.8    301.9 lto
    391.4    302.9 lto
    402.0    304.1 lto
    412.6    305.4 lto
    423.3    306.9 lto
    433.9    308.5 lto
    444.5    310.1 lto
    455.1    311.8 lto
    465.7    313.4 lto
    476.3    315.0 lto
    486.9    316.5 lto
    497.5    317.8 lto
    508.2    318.9 lto
    518.8    319.7 lto
    529.4    320.2 lto
 540 320.4 lto

 stroke grestore
  1.5 setlinewidth 1 setlinejoin [ ] 0 setdash
% --- plcrv: new curve, 21 pts lt 1 bold 3 ---
gsave newpath 327.7 144 moveto 327.7 540 lineto
              540 540 lineto 540 144 lineto closepath clip
newpath 327.7 310.8 moveto 338.4 310.7 lto
    349.0    310.4 lto
    359.6    309.8 lto
    370.2    309.1 lto
    380.8    308.2 lto
    391.4    307.3 lto
    402.0    306.3 lto
    412.6    305.4 lto
    423.3    306.9 lto
    433.9    308.5 lto
    444.5    310.1 lto
    455.1    311.8 lto
    465.7    313.4 lto
    476.3    316.4 lto
    486.9    317.2 lto
    497.5    317.8 lto
    508.2    318.9 lto
    518.8    319.7 lto
    529.4    320.2 lto
 540 320.4 lto

 stroke grestore
  1.5 setlinewidth 1 setlinejoin [ ] 0 setdash
% --- plcrv: new curve, 21 pts lt 1 bold 3 ---
gsave newpath 327.7 144 moveto 327.7 540 lineto
              540 540 lineto 540 144 lineto closepath clip
newpath 327.7 310.8 moveto 338.4 310.9 lto
    349.0    311.0 lto
    359.6    311.2 lto
    370.2    311.5 lto
    380.8    311.9 lto
    391.4    312.3 lto
    402.0    312.8 lto
    412.6    313.4 lto
    423.3    313.9 lto
    433.9    314.5 lto
    444.5    315.1 lto
    455.1    315.7 lto
    465.7    316.2 lto
    476.3    316.8 lto
    486.9    323.9 lto
    497.5    332.6 lto
    508.2    341.9 lto
    518.8    350.7 lto
    529.4    357.5 lto
 540 360.1 lto

 stroke grestore
  1.5 setlinewidth 1 setlinejoin [ ] 0 setdash
% --- plcrv: new curve, 21 pts lt 1 bold 3 ---
gsave newpath 327.7 144 moveto 327.7 540 lineto
              540 540 lineto 540 144 lineto closepath clip
newpath 327.7 644.4 moveto 338.4 644 lto
    349.0    642.7 lto
    359.6    640.8 lto
    370.2    638.3 lto
    380.8    635.4 lto
    391.4    622.3 lto
    402.0    609.3 lto
    412.6    596.7 lto
    423.3    584.7 lto
    433.9    573.4 lto
    444.5    562.8 lto
    455.1    553.2 lto
    465.7    536.7 lto
    476.3    516.7 lto
    486.9    497.7 lto
    497.5    480.1 lto
    508.2    464.2 lto
    518.8    450.8 lto
    529.4    441.4 lto
 540 437.8 lto

 stroke grestore
  1.5 setlinewidth 1 setlinejoin [ ] 0 setdash
% --- plcrv: new curve, 21 pts lt 1 bold 3 ---
gsave newpath 327.7 144 moveto 327.7 540 lineto
              540 540 lineto 540 144 lineto closepath clip
newpath 327.7 678.5 moveto 338.4 676.2 lto
    349.0    669.6 lto
    359.6    659.8 lto
    370.2    648.1 lto
    380.8    635.4 lto
    391.4    622.3 lto
    402.0    609.3 lto
    412.6    596.7 lto
    423.3    584.7 lto
    433.9    573.4 lto
    444.5    562.8 lto
    455.1    553.2 lto
    465.7    544.4 lto
    476.3    536.7 lto
    486.9    530.0 lto
    497.5    524.5 lto
    508.2    520.1 lto
    518.8    516.9 lto
    529.4    515.0 lto
 540 514.5 lto

 stroke grestore
  1.5 setlinewidth 1 setlinejoin [ ] 0 setdash
% --- plcrv: new curve, 21 pts lt 1 bold 3 ---
gsave newpath 327.7 144 moveto 327.7 540 lineto
              540 540 lineto 540 144 lineto closepath clip
newpath 327.7 678.5 moveto 338.4 676.2 lto
    349.0    669.6 lto
    359.6    659.8 lto
    370.2    648.1 lto
    380.8    635.5 lto
    391.4    632.5 lto
    402.0    629.4 lto
    412.6    626.4 lto
    423.3    619.5 lto
    433.9    600.9 lto
    444.5    579.7 lto
    455.1    558.3 lto
    465.7    544.4 lto
    476.3    536.7 lto
    486.9    530.0 lto
    497.5    524.5 lto
    508.2    520.1 lto
    518.8    516.9 lto
    529.4    515.0 lto
 540 514.5 lto

 stroke grestore
%%BoundingBox: 144 144 540 678.5
showpage
