#!/bin/csh
set ddd =  $argv[1]
echo $ddd
echo $argv[2]

##############################################
if(-e wkp.$ddd) rm wkp.$ddd
lmf --mixsig=$argv[2] --quit=band $ddd    >llmf_ef
##############################################

lmf --mixsig=$argv[2] --band:fn=syml $ddd >llmf_band
#echo -1,1,10,10|plbnds $ddd >>llmf_band
#fplot -f plot.plbnds >>llmf_band

exit
echo -15,15,15,15|plbnds -fplot -ef=0 -scl=13.605 -spin1 $ddd
mv bnd1.dat bnd1.spin1
mv bnd2.dat bnd2.spin1
echo -15,15,15,15|plbnds -fplot -ef=0 -scl=13.605 -spin2 $ddd
mv bnd1.dat bnd1.spin2
mv bnd2.dat bnd2.spin2


#plbnds -fplot -ef=0 -scl=13.605 -spin2 eras
fplot -f plot.plbnds.$ddd
