#!/bin/csh
# --------------------------------
# self-consistent GW itteration .
#---------------------------------
set n = $0
set nfpgw = ${n:h}
echo $nfpgw
echo $argv

##############################################
if(-e wkp.$argv[1]) rm wkp.$argv[1]
lmf $argv[1] --quit=band    >llmf_ef
##############################################

lmf --band:fn=syml $argv > llmf_band
echo -10,15,15,15|plbnds -fplot -ef=0 -scl=13.605  $argv[1]

###########
cat $nfpgw/bandp.ngp >bandp_plot.ngp
cat plot.ngp  >> bandp_plot.ngp
ngraph bandp_plot.ngp
