lmdir = ../
include ../Make.inc

ALL:	$(TB)

.PRECIOUS:	$(TB)


$(TB):	$(TB)(addes.o) \
	$(TB)(addoff.o) \
	$(TB)(bndtb.o) \
	$(TB)(bndtbf.o) \
	$(TB)(covsrt.o) \
	$(TB)(derivp.o) \
	$(TB)(dhmix.o) \
	$(TB)(dskham.o) \
	$(TB)(efgrad.o) \
	$(TB)(fitmrq.o) \
	$(TB)(gaussj.o) \
	$(TB)(getujh.o) \
	$(TB)(hstr0.o) \
	$(TB)(hstr.o) \
	$(TB)(invtb1.o) \
	$(TB)(iodell.o) \
	$(TB)(iomv.o) \
	$(TB)(ioqm.o) \
	$(TB)(itrpck.o) \
	$(TB)(lumo.o) \
	$(TB)(makcg9.o) \
	$(TB)(makv0.o) \
	$(TB)(meptr.o) \
	$(TB)(mkrho0.o) \
	$(TB)(mkwttb.o) \
	$(TB)(mrqcof.o) \
	$(TB)(mrqmin.o) \
	$(TB)(nlme.o) \
	$(TB)(qmix2.o) \
	$(TB)(qmix.o) \
	$(TB)(rcnsl0.o) \
	$(TB)(rcut.o) \
	$(TB)(rdtbh.o) \
	$(TB)(rhomix.o) \
	$(TB)(secmtb.o) \
	$(TB)(shotbm.o) \
	$(TB)(skham.o) \
	$(TB)(skhso.o) \
	$(TB)(swapv.o) \
	$(TB)(symre.o) \
	$(TB)(symrtb.o) \
	$(TB)(symtbd.o) \
	$(TB)(tbadh1.o) \
	$(TB)(tbadh2.o) \
	$(TB)(tbdiag.o) \
	$(TB)(tbesel.o) \
	$(TB)(tbfdia.o) \
	$(TB)(tbfrce.o) \
	$(TB)(tbham.o) \
	$(TB)(tbloch.o) \
	$(TB)(tbmpol.o) \
	$(TB)(tbtote.o) \
	$(TB)(tbzint.o) \
	$(TB)(tiozll.o) \
	$(TB)(ume.o)
	$(RANLIB) $@
 
clean: 
	-rm -f $(TB) Makefile Names
