#+Title: How to make doping?
#+LANGUAGE: en
#+STARTUP: showall
#+OPTIONS: \n:t
#+OPTION: email:takaokotani@gmail.com
#+LATEX_CLASS: beamer
#+LATEX_CLASS_OPTIONS: [dvipdfmx,12pt]
#+BEAMER_THEME: metropolis
#+LATEX_HEADER: \usepackage{bxdpx-beamer}
#+LATEX_HEADER: \usepackage{pxjahyper}
#+LATEX_HEADER: \usepackage{minijs}
#+LATEX_HEADER: \usepackage{minted}
#+LATEX_HEADER: \renewcommand{\kanjifamilydefault}{\gtdefault}

The 1st principle calculations are performed under the charge neutrality.
We have two methods (or they are combined ) to treat fractional number of electrons 
in the primitive cell. (Search 'Charges:' in the ecaljmanual.tex/pdf).

* You can use fractional numbers for SPEC_ATOM_Z, and/or set valence charge by BZ \_ZBAK.
  Following sample is doping for Si, Z=14 and two atoms per cell.
-----

** NOTE for SPEC_ATOM_Z, SPEC_ATOM_Q, SPEC_ATOM_MOM
The default setting is (in ctrl.si) given as
#+begin_src
SPEC
    ATOM=Si Z=14 R=2.16 
#+end_src
, where we specify one of species, ATOM=Si as 'Si' with Z=14. 
(The Si spec is placed by the SITE category).
With the default ctrl file (given by ctrlgenM1.py), 
try lmfa as
#+begin_src bash
lmfa Si |grep conf
#+end_src
. Then it shows a default electronic configuration. (See conf: in ecaljmanual).
The total number of electrons should be the same as Z=14. (Q=0 is shown in the lmfa output).

If you like to change the electronic configuration, you need to set SPEC_ATOM_Q and SEPC_ATOM_MMOM.
An example in ctrl file is
#+begin_src
SPEC
    ATOM=Si Z=14.1 R=2.16 Q=2,2.1 
#+end_src
In this case, Z=14.1 (virtual atom) with 2 electrons for valence s, 2.1 electrons for valence p.
(after d, we have zero numbers).
Thus the charge neutralityis satisfied. Try MMOM=0,0.1 together with nspin=2, then you see
a magnetic initial configulation of electrons is given. MMOM=0,0.1 means that we have magnetic moment 
for p channel.


**  Fractional Z, such as Z=14.2 
Together with Z, you have to add Q for the atom. 
For example Z=14.2, we need Q=2,2.2 (add +0.2 electron for p channel) 
to keep charge neutrality of atom when we have spherical atomic densities (core is frozen usually during lmf) 
are generated. Then Q=0 (check of charge neutrality) is shown in the output of lmfa.
Pay attention that lmfa finishs normally. Then run lmf or lmf-MPIK.
#+begin_src bash
 grep 'z=',llmf 
#+end_src
shows Z for atoms.

#+begin_src bash
 grep -A5 'Charges:'
#+end_src
shows 
#+RESULTS:
 Charges:  valence     8.40000   cores    20.00000   nucleii   -28.40000
    hom background     0.00000   deviation from neutrality:     -0.00000

Here we see   nuclei = - 2* 14.2  = -28.4  # given by Z

CAUTION: at the first iteration, Charges: shows such as
  Charges:  valence     8.00000   cores    20.00000   nucleii   -28.00000
  hom background     0.12300   deviation from neutrality: 0.12300
because of the initial condition is given by superposition of atomic densities. It show
deviation is nonzero ==> But 'deviation from neutrality: 0' from the next iteration.


** Back ground charge by ZBAK
Set BZ\_ZBAK. If ZBAK=0.4, the back ground charge is negative as -0.4|e|, 
thus the number of electron becomes 0.4 smaller.
(cores + valence electron + ZBAK = |total nucleus charge|).
#+begin_src bash
 grep -A5 'Charges:'
#+end_src
shows 
#+RESULTS:
------------
Charges:  valence     7.60000   cores    20.00000   nucleii   -28.00000
    hom background     0.40000   deviation from neutrality:     -0.00000

That is, 7.6+0.4+20.0  =  -28.0


** Combination of fractional Z and BZ_ZBAK
   Let us try Z=14.2, Q=2,2.2, together with ZBAK=0.3
   In this case, we have 
-------
   Charges:  valence     8.10000   cores    20.00000   nucleii   -28.40000
    hom background     0.30000   deviation from neutrality:     -0.00000

This means that (2 atoms per cell).
  nuclei     = - 2* 14.2  = -28.4  # given by Z
  cores      =   2* 10    =  20    # given by the atom of integer part of Z.
  background =  0.3                # given by ZBAK
Thus we have 
  valence electron = 28.4 - 20- 0.3 = 8.1 


