#!/bin/bash
ext=fe
ddd=${ext}_dos
echo $ddd $ext
ln -s rst.$ext rst.${ddd}
lmdir=../..
# modify ctrl file as I did. METAL=T Q=BAND nk=8. Check SAVEDOS=T option
# this is also OK for 
$lmdir/lmf --no-fixef0 --quit=band $ddd |tee llmfdos  
echo 15,10,-1,1|$lmdir/pldos dos.$ddd  -lst='1;2'
echo 'Check ps.dos*(postscript)!'

