#!/bin/tcsh
# --------------------------------
# self-consistent GW itteration using MPI.
#---------------------------------
if(-e NoCore) then
  rm -f NoCore 
endif
if(-e QPU) then
 rm -f QP[UD]
endif

if(! -e SEBK) then
 mkdir SEBK
endif

if($# != 3 || $argv[1] != "-np" ) then
    echo "an example of usage: gwsc1shot_mpi -np 4 si"
    exit
endif

set n = $0
set nfpgw = ${n:h}

set TARGET=$argv[3]
set MPI_SIZE=$argv[2]
echo "MPI size: " $MPI_SIZE
echo $TARGET


##########################################################################
foreach i2x (0 1 2 3 4 5 6 7 8 9 )
foreach i1x (0 1 2 3 4 5 6 7 8 9 )
@ ix = $i2x * 10 + $i1x

echo 1 |$nfpgw/qg4gw           > lqg4gw

# -- get EFERMI for hx0fp0
echo 1|$nfpgw/heftet      >leftet

# -- hchknw only calculate NW, which contains the number of nw corresponding to QPNT -----
echo 1|$nfpgw/hchknw         >lchknw


### Core1 exchange self-energy 
# -- product basis for core
echo 3|$nfpgw/hbasfp0 >lbasC
# -- Coulobm matrix
echo 0|mpirun -np $MPI_SIZE $nfpgw/hvccfp0        >lvccC

###################################################
#mkdir core
#cp BASFP* PPBR* VCCFP core
###################################################


# -- the self energy from core1
echo 1003| mpirun -np $MPI_SIZE $nfpgw/hsfp0_sc   >lsxC


###################################################
#echo ' --- end of test gw_lmf2 --- '
#exit 
###################################################


### Valence part of the self-energy
echo 0|$nfpgw/hbasfp0  >lbas
# -- Coulobm matrix
echo 0|mpirun -np $MPI_SIZE $nfpgw/hvccfp0  >lvcc	

# -- Sergey.F the exchange self energy from valence core2+valence elctrons 
echo 1001|mpirun -np $MPI_SIZE $nfpgw/hsfp0_sc   >lsx

# -- Sergey.F the screened coulom interaction 
echo 1011|$nfpgw/hx0fp0_sc  >lx01011

#########################################################
#mkdir val
#cp BASFP* PPBR* VCCFP NW WV* val
##########################################################

# -- Sergey. F the correlation self-energy from valence core2+valence elctrons 
echo 1002|mpirun -np $MPI_SIZE $nfpgw/hsfp0_sc   >lsc

# -- Make summary 
echo 1000|$nfpgw/hqpe    >lqpe
exit

### end of itteration loop #########################################################
cp evec.$TARGET evec_prev_iter
ln -s -f sigm sigm.$TARGET
mv SEX* SEC* XC* SEBK


#### exit only for a loop
$nfpgw/lmf $TARGET > llmf
exit



foreach file (sigm QPU QPD TOTE.UP TOTE.DN lqpe lsc lsx lx0 llmfgw01 evecfix.chk llmf) 
  if(-e $file) cp $file $file.${ix}run
end
echo $ix 'iteration over'
end
end
exit
