#!/bin/bash
ddd=es
lmdir=../..
rm -rf wkp.$ddd
$lmdir/lmf $ddd --quit=band    |tee llmf_ef
$lmdir/lmf --band:fn=syml $ddd  |tee llmf_band

echo -15,150,15,15|$lmdir/plbnds -fplot -ef=0 -scl=13.605  $ddd
$lmdir/fplot -f plot.plbnds ; mv ps.dat ps.band.$ddd
echo 'Check ps.band.* (postscript)!'

