#!/bin/csh
#echo $argv[1] $argv[2] $argv[3]

###############################################
set max = 950 #$argv[1] 
set ymax = 1600 #$argv[1] 
set xx = 4
set yy = 5
set zz = 6
set zzx = 7
#ETOTeV.fc_${id}_222_rmt.800 dat1
#ETOTeV.fc_${id}_222_rmt.850 dat2
set sft1 = 0
#set czero = 0.441082147922057
set id2 = 11

set pqdir = $HOME/bin

################################33
if(-e $pqdir/plsp_ni_saveid) then
  set count = `cat $pqdir/plsp_ni_saveid`
else 
  set count = 000000
endif
@ count = $count + 1
cat > $pqdir/plsp_ni_saveid <<EOF
$count
EOF
set len = `wc -c $pqdir/plsp_ni_saveid| cut -f 1 -d'/'`  
echo len =  $len
if     ( $len <3 ) then 
  set count = 00000$count
else if( $len <4 ) then 
  set count =  0000$count
else if( $len <5 ) then 
  set count =   000$count
else if( $len <6 ) then 
  set count =    00$count
else if( $len <7 ) then 
  set count =     0$count
endif
set batchname = {$count}


set chipmn = `ls -1 ChiPM*.nolfc.dat`
#echo $chipmn
#if(-e czero) rm czero
@ count = 0
foreach xxx ( $chipmn )
  head -2 $xxx| tail -1 | sed -e 's/D/E/g' - |awk \
    '{if($1==0.0 && $2==0.0 && $3==0.0 && $4==0.0){printf "%15.12f \n",-$5 >"czero"}}' 
  @ count = $count + 1
  echo -n $count, $xxx; head -2 $xxx| tail -1 
end
set czero = `head -1 czero`
set ppp=`pwd`
set ppp=`echo $ppp |sed -e 's/\_/_ /g'`
######################################
cat <<EOF >ggg
#!/usr/bin/gnuplot -persist
set xrange [0: ${max}]
set yrange [0: ${ymax}]
set xlabel "omega(meV)"
set ylabel "Im[<m|chi^{+-}(q,omega)|m>/<m|m>^2]"
set title "$ppp"
set noclabel
set grid
set nolabel
czero = ${czero}
plot \
EOF
######################################
@ cc = 0
foreach xxx ( $chipmn )
  @ cc = $cc + 1
  echo $xxx|chipmdat  > $xxx.extended
  set ti = `head -2 $xxx| tail -1 | awk '{printf "q=(%7.4f %7.4f %7.4f)",$1, $2, $3}' `
  if($cc != 1) echo -n "'$xxx.extended' using (ddd${xx}):(ddd${zzx}) ti '${ti}' with lines" >>ggg
#  if($cc != 1) echo -n "'$xxx.extended' using (ddd${xx}):(ddd${zz}/((ddd${yy}+czero)**2+ddd${zz}**2)) ti '${ti}' with lines" >>ggg
  if($cc != 1 && $cc != $count) then
    echo ", \" >>ggg
  endif
end
echo " " >>ggg

#echo 'endend' >>ggg
#-e 's/\, endend//g' ggg  >ggg0

sed -e 's/ddd/\$/g' ggg >ggg0
mv ggg0 ggg

cat <<EOF >>ggg
set term postscript enhanced color
set output "SpinNi_${batchname}_${PWD:t}.eps"
replot
EOF
chmod +x ggg
./ggg

exit
