#!/bin/csh
#echo $argv[1] $argv[2] $argv[3]
foreach xxx (01 02 03 04 05 06 07)
if(-e ChiPM$xxx.nolfc.dat) then
  echo ChiPM$xxx.nolfc.dat|chipmdat  >ChiPM$xxx.nolfc.dat.extended
  set ifi$xxx = ChiPM$xxx.nolfc.dat.extended
endif
end

set max = 0 #$argv[1] 
set xx = 4
set yy = 5
set zz = 6
#ETOTeV.fc_${id}_222_rmt.800 dat1
#ETOTeV.fc_${id}_222_rmt.850 dat2
set sft1 = 0
set czero =   0.441082147922057
set id2 = 11

cat <<EOF >ggg
#!/usr/bin/gnuplot -persist
#set yrange [0: ${max}]
set noclabel
set grid
set nolabel
plot  \
  "${ifi02}"  using (\$${xx}):(\$${zz}/((\$${yy}+${czero})**2+\$${zz}**2)) ti "0.1" with lines,  \
  "${ifi03}"  using (\$${xx}):(\$${zz}/((\$${yy}+${czero})**2+\$${zz}**2)) ti "0.2" with lines , \
  "${ifi04}"  using (\$${xx}):(\$${zz}/((\$${yy}+${czero})**2+\$${zz}**2)) ti "0.3" with lines 
set term postscript enhanced color
set output "ETOTeV.eps"
replot
save "Etot11.plt"
EOF
chmod +x ggg
./ggg

exit

  "ChiPM07.dat"  using (\$${xx}):(\$${zz}/((\$${yy}+${czero})**2+\$${zz}**2)) ti "0.5" with lines,\
  "ChiPM09.dat"  using (\$${xx}):(\$${zz}/((\$${yy}+${czero})**2+\$${zz}**2)) ti "0.7" with lines

      "ETOTeV.fc_${id}_222_rmt.850"  using 2:(\$6) with lines,\
      "ETOTeV.fc_${id}_222_rmt.850"  using 2:(\$6) with points, \
      "ETOTeV.fc_${id2}_222_rmt.800"  using 2:(\$6+$sft1) with lines,\
      "ETOTeV.fc_${id2}_222_rmt.800"  using 2:(\$6+$sft1) with points,\
      "ETOTeV.fc_${id2}_222_rmt.850"  using 2:(\$6+$sft1) with lines,\
      "ETOTeV.fc_${id2}_222_rmt.850"  using 2:(\$6+$sft1) with points

  "${if02}"  using (\$${xx}):(\$${zz}/((\$${yy}+${czero})**2+\$${zz}**2)) ti "0.1" with points, \
  "${if02}"  using (\$${xx}):(\$${zz}/((\$${yy}+${czero})**2+\$${zz}**2)) ti "0.1" with lines,  \
  "${if03}"  using (\$${xx}):(\$${zz}/((\$${yy}+${czero})**2+\$${zz}**2)) ti "0.2" with lines , \
  "${if03}"  using (\$${xx}):(\$${zz}/((\$${yy}+${czero})**2+\$${zz}**2)) ti "0.2" with points ,\
  "${if04}"  using (\$${xx}):(\$${zz}/((\$${yy}+${czero})**2+\$${zz}**2)) ti "0.3" with lines , \
  "${if04}"  using (\$${xx}):(\$${zz}/((\$${yy}+${czero})**2+\$${zz}**2)) ti "0.3" with points 
