#!/bin/tcsh
rm -rf converted
mkdir converted

foreach xxx (`find . -name "*.F"`)
#echo vvv $xxx 
./redo $xxx > $xxx.beforeFindent
set exinfo0 = $?
./findent $xxx.beforeFindent > converted/$xxx
set exinfo1 = $?
rm $xxx.beforeFindent
if($exinfo0 != 0 | $exinfo1 != 0 ) then
  echo vvv $xxx 
endif
end
