#!/bin/bash
# --------------------------------
# Get GWinpt.tmp
#
n=$0
nfpgw=`dirname $0`
echo $nfpgw
echo $#
echo $1

if [ $# == 4 ]; then
n1=$2
n2=$3
n3=$4
else
n1=4
n2=4
n3=4
fi

echo $n1 $n2 $n3 

$nfpgw/lmfa $1 >llmfa
echo 0 | $nfpgw/lmfgw $1    > llmfgw00
echo 1 $n1 $n2 $n3| $nfpgw/gwinit   #This changes the <QPNT> setting.

echo
echo "-------------------------------------------------------------------"
echo "  We use n1n2n3=" $n1 $n2 $n3 " in GWinput. This is k points mesh for GW mode"
echo "  You can change it by hand (not need to repeat this). =="
echo 'OK! GWinpt.tmp is generated!'
 
