%!PS-Adobe-2.0 generated by plsub.f ...
/inch{72 mul}def /cm{72 mul 2.54 div}def 0 0 translate  1 1 scale
/tails 0.4 def % set to 0 for blanking chars without tails
/lto{lineto}def % shorthand for lineto
/blank-on{/b 1 def}def /blank-off{/b 0 def}def blank-on
/smaller 0.67 def % sub/superscripts are this much smaller
/shift   0.33 def % and are shifted by this much of the char height
% push size then font onto stack to select font
/choosefont {findfont exch scalefont setfont} def
% paint object on top of stack at current position
/debug {dup /str 30 string def str cvs show} def
% finding width of longest ordinate label (current width on stack) ...
/max 0 def /mxw{/w exch def w max gt {/max w def} if}def
% string centring, justification in the four quadrants
% and absicca and ordinate label centring ...
/showru{show}def
/showcu{dup stringwidth pop 2 div neg 0 rmoveto show}def
/showlu{dup stringwidth pop neg 0 rmoveto show}def
/showrc{0 h 2 div neg rmoveto show}def
/showcc{dup stringwidth pop 2 div neg h 2 div neg rmoveto show}def
/showlc{dup stringwidth pop neg h 2 div neg rmoveto show}def
/showrd{0 h neg rmoveto show}def
/showld{dup stringwidth pop neg h neg rmoveto show}def
/showcd{dup stringwidth pop 2 div neg h neg rmoveto show}def
/showa{gsave fontsize /Symbol choosefont
       dup stringwidth pop 2 div neg h 1.5 mul neg rmoveto show grestore}def
/showA{gsave fontsize /Symbol choosefont
       dup stringwidth pop 2 div neg h 0.5 mul rmoveto show grestore}def
/showo{gsave fontsize /Symbol choosefont
       dup stringwidth pop dup mxw h 2 div add neg h 2 div neg rmoveto show grestore}def
/showO{gsave fontsize /Symbol choosefont
       dup h 2 div h 2 div neg rmoveto show grestore}def
% aliases for pslabl ...
/show0{showcc}def /show1{show}def /show2{showrd}def /show3{showld}def
/show4{showlu}def
% newline macros for horizontal and vertical labelling ...
/newlinehf{currentpoint fontsize sub moveto}def
/newlinevf{currentpoint exch fontsize add exch moveto}def
/newlinehr{currentpoint fontsize add moveto}def
/newlinevr{currentpoint exch fontsize sub exch moveto}def
/savecurrentpoint {currentpoint /ybak exch def /xbak exch def} def
% end preamble ...

 % FONT: set font and fontsize ..
/font /Times-Roman def /fontsize  24 def
/h fontsize 0.6 mul def % h is about char height
fontsize font choosefont
% pltstp: frame corners (GU): lb= (0.05 0.935)  rt = (0.98 0.97)
% --- FRME : axes at x=-0.5 0.5  y=0 5  bold=3
/max 0 def 
  1.5 setlinewidth 1 setlinejoin [ ] 0 setdash
newpath 163.8 514.3 moveto 532.1 514.3 lto
 532.1 528.1 lto
 163.8 528.1 lto
 163.8 514.3 lto closepath gsave 1 1 1 setrgbcolor fill grestore stroke
newpath 163.8 514.3 moveto 163.8 514.6 lto stroke
newpath 347.9 514.3 moveto 347.9 514.6 lto stroke
newpath 532.1 514.3 moveto 532.1 514.6 lto stroke
newpath 163.8 528.1 moveto 163.8 527.8 lto stroke
newpath 347.9 528.1 moveto 347.9 527.8 lto stroke
newpath 532.1 528.1 moveto 532.1 527.8 lto stroke
newpath 163.8 514.3 moveto 173 514.3 lto stroke
newpath 163.8 517 moveto 173 517 lto stroke
newpath 163.8 519.8 moveto 173 519.8 lto stroke
newpath 163.8 522.6 moveto 173 522.6 lto stroke
newpath 163.8 525.3 moveto 173 525.3 lto stroke
newpath 163.8 528.1 moveto 173 528.1 lto stroke
newpath 532.1 514.3 moveto 522.9 514.3 lto stroke
newpath 532.1 517 moveto 522.9 517 lto stroke
newpath 532.1 519.8 moveto 522.9 519.8 lto stroke
newpath 532.1 522.6 moveto 522.9 522.6 lto stroke
newpath 532.1 525.3 moveto 522.9 525.3 lto stroke
newpath 532.1 528.1 moveto 522.9 528.1 lto stroke
  1 setlinewidth 1 setlinejoin [ ] 0 setdash
% ---  xt1=-.5 tsx=.5 mtx=1  yt1=0 tsy=1 mty=1
 % FRME: Label axes ...
   347.9   514.3 moveto 0 h 3 mul neg rmoveto
   163.8   521.2 moveto h 2 mul max add neg 0 rmoveto
 % FRME: adding title ...
   532.1   528.1 moveto 0 h 0.5 mul rmoveto
  1.5 setlinewidth 1 setlinejoin [ ] 0 setdash
% --- plcrv: new curve, 501 pts lt 1 bold 3 ---
gsave newpath 163.8 514.3 moveto 163.8 528.1 lineto
              532.1 528.1 lineto 532.1 514.3 lineto closepath clip
newpath 163.8 515.7 moveto 164.5 515.7 lto
    165.3    515.7 lto
    166.0    515.8 lto
    166.7    515.8 lto
    167.5    515.9 lto
    168.2    515.9 lto
    169.0    516.0 lto
    169.7    516.0 lto
    170.4    516.1 lto
    171.2    516.1 lto
    171.9    516.1 lto
    172.6    516.1 lto
    173.4    516.2 lto
    174.1    516.2 lto
    174.8    516.2 lto
    175.6    516.3 lto
    176.3    516.3 lto
    177.1    516.4 lto
    177.8    516.4 lto
    178.5    516.4 lto
    179.3    516.4 lto
    180.0    516.5 lto
    180.7    516.5 lto
    181.5    516.5 lto
    182.2    516.6 lto
    183.0    516.6 lto
    183.7    516.7 lto
    184.4    516.7 lto
    185.2    516.7 lto
    185.9    516.8 lto
    186.6    516.8 lto
    187.4    516.8 lto
    188.1    516.8 lto
    188.8    516.8 lto
    189.6    516.9 lto
    190.3    516.9 lto
    191.1    516.9 lto
    191.8    517.0 lto
    192.5    517.0 lto
    193.3    517.0 lto
    194.0    517.1 lto
    194.7    517.1 lto
    195.5    517.1 lto
    196.2    517.1 lto
    196.9    517.2 lto
    197.7    517.2 lto
    198.4    517.2 lto
    199.2    517.3 lto
    199.9    517.3 lto
    200.6    517.3 lto
    201.4    517.4 lto
    202.1    517.4 lto
    202.8    517.4 lto
    203.6    517.4 lto
    204.3    517.5 lto
    205.0    517.5 lto
    205.8    517.5 lto
    206.5    517.5 lto
    207.3    517.6 lto
    208.0    517.6 lto
    208.7    517.6 lto
    209.5    517.7 lto
    210.2    517.7 lto
    210.9    517.7 lto
    211.7    517.8 lto
    212.4    517.8 lto
    213.1    517.8 lto
    213.9    517.9 lto
    214.6    517.9 lto
    215.4    517.9 lto
    216.1    518.0 lto
    216.8    518.0 lto
    217.6    518.0 lto
    218.3    518.1 lto
    219.0    518.1 lto
    219.8    518.1 lto
    220.5    518.2 lto
    221.3    518.2 lto
    222.0    518.2 lto
    222.7    518.3 lto
    223.5    518.3 lto
    224.2    518.3 lto
    224.9    518.3 lto
    225.7    518.4 lto
    226.4    518.4 lto
    227.1    518.5 lto
    227.9    518.5 lto
    228.6    518.6 lto
    229.4    518.6 lto
    230.1    518.7 lto
    230.8    518.7 lto
    231.6    518.8 lto
    232.3    518.8 lto
    233.0    518.9 lto
    233.8    518.9 lto
    234.5    519.0 lto
    235.2    519.0 lto
    236.0    519.1 lto
    236.7    519.2 lto
    237.5    519.2 lto
    238.2    519.3 lto
    238.9    519.4 lto
    239.7    519.4 lto
    240.4    519.5 lto
    241.1    519.6 lto
    241.9    519.7 lto
    242.6    519.9 lto
    243.3    520.0 lto
    244.1    520.1 lto
    244.8    520.3 lto
    245.6    520.4 lto
    246.3    520.7 lto
    247.0    521.3 lto
    247.8    522.6 lto
    248.5    523.8 lto
    249.2    523.7 lto
    250.0    523.2 lto
    250.7    523.3 lto
    251.5    523.4 lto
    252.2    523.4 lto
    252.9    523.4 lto
    253.7    523.2 lto
    254.4    522.9 lto
    255.1    522.8 lto
    255.9    522.7 lto
    256.6    522.6 lto
    257.3    522.6 lto
    258.1    522.6 lto
    258.8    522.5 lto
    259.6    522.4 lto
    260.3    522.3 lto
    261.0    522.2 lto
    261.8    522.1 lto
    262.5    521.9 lto
    263.2    521.9 lto
    264.0    521.8 lto
    264.7    521.8 lto
    265.4    521.7 lto
    266.2    521.7 lto
    266.9    521.6 lto
    267.7    521.6 lto
    268.4    521.5 lto
    269.1    521.5 lto
    269.9    521.5 lto
    270.6    521.6 lto
    271.3    521.7 lto
    272.1    521.9 lto
    272.8    522.1 lto
    273.5    522.0 lto
    274.3    521.6 lto
    275.0    521.2 lto
    275.8    520.4 lto
    276.5    519.7 lto
    277.2    519.2 lto
    278.0    518.8 lto
    278.7    518.5 lto
    279.4    518.2 lto
    280.2    518.0 lto
    280.9    517.8 lto
    281.6    517.6 lto
    282.4    517.4 lto
    283.1    517.3 lto
    283.9    517.1 lto
    284.6    516.9 lto
    285.3    516.8 lto
    286.1    516.6 lto
    286.8    516.5 lto
    287.5    516.5 lto
    288.3    516.4 lto
    289.0    516.2 lto
    289.8    516.1 lto
    290.5    516.0 lto
    291.2    515.9 lto
    292.0    515.7 lto
    292.7    515.7 lto
    293.4    515.6 lto
    294.2    515.3 lto
    294.9    515.1 lto
    295.6    515.0 lto
    296.4    514.9 lto
    297.1    514.8 lto
    297.9    514.8 lto
    298.6    514.7 lto
    299.3    514.6 lto
    300.1    514.6 lto
    300.8    514.5 lto
    301.5    514.5 lto
    302.3    514.5 lto
    303.0    514.5 lto
    303.7    514.5 lto
    304.5    514.5 lto
    305.2    514.5 lto
    306.0    514.5 lto
    306.7    514.5 lto
    307.4    514.5 lto
    308.2    514.5 lto
    308.9    514.6 lto
    309.6    514.6 lto
    310.4    514.6 lto
    311.1    514.6 lto
    311.8    514.5 lto
    312.6    514.6 lto
    313.3    514.6 lto
    314.1    514.6 lto
    314.8    514.6 lto
    315.5    514.7 lto
    316.3    514.7 lto
    317.0    514.7 lto
    317.7    514.7 lto
    318.5    514.8 lto
    319.2    514.8 lto
    320.0    514.9 lto
    320.7    514.9 lto
    321.4    514.9 lto
    322.2    514.9 lto
    322.9    514.9 lto
    323.6    515.0 lto
    324.4    515.0 lto
    325.1    515.0 lto
    325.8    515.0 lto
    326.6    515.1 lto
    327.3    515.1 lto
    328.1    515.1 lto
    328.8    515.1 lto
    329.5    515.1 lto
    330.3    515.1 lto
    331.0    515.2 lto
    331.7    515.2 lto
    332.5    515.2 lto
    333.2    515.2 lto
    333.9    515.2 lto
    334.7    515.3 lto
    335.4    515.3 lto
    336.2    515.3 lto
    336.9    515.4 lto
    337.6    515.6 lto
    338.4    515.7 lto
    339.1    515.8 lto
    339.8    515.8 lto
    340.6    515.8 lto
    341.3    515.8 lto
    342.0    515.7 lto
    342.8    515.7 lto
    343.5    515.7 lto
    344.3    515.6 lto
    345.0    515.5 lto
    345.7    515.4 lto
    346.5    515.3 lto
    347.2    515.2 lto
    347.9    515.2 lto
    348.7    515.1 lto
    349.4    515.1 lto
    350.1    515.0 lto
    350.9    515.0 lto
    351.6    514.9 lto
    352.4    514.9 lto
    353.1    514.9 lto
    353.8    514.9 lto
    354.6    514.8 lto
    355.3    514.8 lto
    356.0    514.8 lto
    356.8    514.8 lto
    357.5    514.8 lto
    358.3    514.8 lto
    359.0    514.7 lto
    359.7    514.7 lto
    360.5    514.7 lto
    361.2    514.7 lto
    361.9    514.7 lto
    362.7    514.7 lto
    363.4    514.7 lto
    364.1    514.6 lto
    364.9    514.6 lto
    365.6    514.6 lto
    366.4    514.6 lto
    367.1    514.6 lto
    367.8    514.6 lto
    368.6    514.6 lto
    369.3    514.6 lto
    370.0    514.5 lto
    370.8    514.5 lto
    371.5    514.5 lto
    372.2    514.5 lto
    373.0    514.5 lto
    373.7    514.5 lto
    374.5    514.5 lto
    375.2    514.5 lto
    375.9    514.5 lto
    376.7    514.5 lto
    377.4    514.5 lto
    378.1    514.5 lto
    378.9    514.4 lto
    379.6    514.4 lto
    380.3    514.4 lto
    381.1    514.4 lto
    381.8    514.4 lto
    382.6    514.4 lto
    383.3    514.4 lto
    384.0    514.4 lto
    384.8    514.4 lto
    385.5    514.4 lto
    386.2    514.4 lto
    387.0    514.4 lto
    387.7    514.4 lto
    388.5    514.4 lto
    389.2    514.5 lto
    389.9    514.6 lto
    390.7    514.7 lto
    391.4    514.8 lto
    392.1    514.9 lto
    392.9    515.0 lto
    393.6    514.9 lto
    394.3    514.9 lto
    395.1    514.9 lto
    395.8    514.9 lto
    396.6    514.9 lto
    397.3    514.9 lto
    398.0    514.9 lto
    398.8    514.9 lto
    399.5    514.8 lto
    400.2    514.8 lto
    401.0    514.8 lto
    401.7    514.8 lto
    402.4    514.8 lto
    403.2    514.8 lto
    403.9    514.8 lto
    404.7    514.8 lto
    405.4    514.8 lto
    406.1    514.8 lto
    406.9    514.8 lto
    407.6    514.9 lto
    408.3    514.9 lto
    409.1    514.9 lto
    409.8    514.9 lto
    410.5    514.8 lto
    411.3    514.7 lto
    412.0    514.7 lto
    412.8    514.7 lto
    413.5    514.6 lto
    414.2    514.6 lto
    415.0    514.6 lto
    415.7    514.6 lto
    416.4    514.6 lto
    417.2    514.7 lto
    417.9    514.7 lto
    418.6    514.8 lto
    419.4    514.9 lto
    420.1    515.0 lto
    420.9    515.1 lto
    421.6    515.2 lto
    422.3    515.2 lto
    423.1    515.2 lto
    423.8    515.2 lto
    424.5    515.2 lto
    425.3    515.2 lto
    426.0    515.2 lto
    426.8    515.2 lto
    427.5    515.2 lto
    428.2    515.2 lto
    429.0    515.2 lto
    429.7    515.2 lto
    430.4    515.2 lto
    431.2    515.2 lto
    431.9    515.2 lto
    432.6    515.2 lto
    433.4    515.2 lto
    434.1    515.2 lto
    434.9    515.1 lto
    435.6    515.1 lto
    436.3    515.1 lto
    437.1    515.1 lto
    437.8    515.1 lto
    438.5    515.1 lto
    439.3    515.1 lto
    440.0    515.1 lto
    440.7    515.0 lto
    441.5    515.0 lto
    442.2    515.0 lto
    443.0    515.0 lto
    443.7    515.0 lto
    444.4    515.0 lto
    445.2    515.0 lto
    445.9    515.0 lto
    446.6    515.0 lto
    447.4    515.0 lto
    448.1    515.0 lto
    448.8    515.0 lto
    449.6    515.0 lto
    450.3    515.0 lto
    451.1    515.0 lto
    451.8    515.0 lto
    452.5    515.0 lto
    453.3    515.0 lto
    454.0    515.0 lto
    454.7    515.0 lto
    455.5    515.0 lto
    456.2    515.0 lto
    457.0    515.0 lto
    457.7    515.0 lto
    458.4    515.0 lto
    459.2    515.0 lto
    459.9    515.0 lto
    460.6    515.0 lto
    461.4    515.0 lto
    462.1    515.0 lto
    462.8    515.0 lto
    463.6    515.0 lto
    464.3    515.0 lto
    465.1    515.0 lto
    465.8    515.0 lto
    466.5    515.0 lto
    467.3    515.0 lto
    468.0    515.0 lto
    468.7    515.0 lto
    469.5    515.0 lto
    470.2    515.0 lto
    470.9    515.0 lto
    471.7    515.0 lto
    472.4    515.0 lto
    473.2    515.0 lto
    473.9    515.0 lto
    474.6    515.0 lto
    475.4    515.0 lto
    476.1    515.0 lto
    476.8    515.0 lto
    477.6    515.0 lto
    478.3    515.0 lto
    479.0    515.0 lto
    479.8    515.0 lto
    480.5    515.0 lto
    481.3    515.0 lto
    482.0    515.0 lto
    482.7    515.0 lto
    483.5    515.1 lto
    484.2    515.1 lto
    484.9    515.1 lto
    485.7    515.1 lto
    486.4    515.1 lto
    487.1    515.1 lto
    487.9    515.1 lto
    488.6    515.1 lto
    489.4    515.1 lto
    490.1    515.1 lto
    490.8    515.0 lto
    491.6    515.0 lto
    492.3    515.0 lto
    493.0    515.0 lto
    493.8    515.0 lto
    494.5    515.0 lto
    495.3    515.0 lto
    496.0    515.0 lto
    496.7    515.0 lto
    497.5    515.0 lto
    498.2    515.0 lto
    498.9    515.0 lto
    499.7    515.0 lto
    500.4    515.0 lto
    501.1    515.0 lto
    501.9    515.0 lto
    502.6    515.0 lto
    503.4    515.0 lto
    504.1    515.0 lto
    504.8    515.0 lto
    505.6    515.0 lto
    506.3    515.0 lto
    507.0    515.0 lto
    507.8    515.0 lto
    508.5    515.0 lto
    509.2    515.0 lto
    510.0    515.0 lto
    510.7    515.0 lto
    511.5    515.0 lto
    512.2    515.0 lto
    512.9    515.0 lto
    513.7    515.0 lto
    514.4    515.0 lto
    515.1    515.0 lto
    515.9    515.0 lto
    516.6    515.0 lto
    517.3    515.0 lto
    518.1    515.0 lto
    518.8    515.0 lto
    519.6    515.0 lto
    520.3    515.0 lto
    521.0    515.0 lto
    521.8    515.0 lto
    522.5    515.0 lto
    523.2    515.0 lto
    524.0    515.0 lto
    524.7    515.0 lto
    525.5    515.0 lto
    526.2    515.0 lto
    526.9    515.0 lto
    527.7    514.9 lto
    528.4    514.9 lto
    529.1    514.9 lto
    529.9    514.9 lto
    530.6    514.9 lto
    531.3    514.9 lto
 532.1 514.9 lto

 stroke grestore
  1.5 setlinewidth 1 setlinejoin [14.4 7.2] 0 setdash
% --- plcrv: new curve, 2 pts lt 2 bold 3 len=(14.4 7.2) ---
gsave newpath 344.2 514.3 moveto 344.2 528.1 lineto
              417.9 528.1 lineto 417.9 514.3 lineto closepath clip
newpath 381 514.3 moveto 381 528.1 lto

 stroke grestore
% pltstp: frame corners (GU): lb= (.05 .9)  rt = (.98 .935)
% --- FRME : axes at x=-.5 .5  y=0 5  bold=3
/max 0 def 
  1.5 setlinewidth 1 setlinejoin [ ] 0 setdash
newpath 163.8 500.4 moveto 532.1 500.4 lto
 532.1 514.3 lto
 163.8 514.3 lto
 163.8 500.4 lto closepath gsave 1 1 1 setrgbcolor fill grestore stroke
newpath 163.8 500.4 moveto 163.8 500.7 lto stroke
newpath 347.9 500.4 moveto 347.9 500.7 lto stroke
newpath 532.1 500.4 moveto 532.1 500.7 lto stroke
newpath 163.8 514.3 moveto 163.8 513.9 lto stroke
newpath 347.9 514.3 moveto 347.9 513.9 lto stroke
newpath 532.1 514.3 moveto 532.1 513.9 lto stroke
newpath 163.8 500.4 moveto 173 500.4 lto stroke
newpath 163.8 503.2 moveto 173 503.2 lto stroke
newpath 163.8 505.9 moveto 173 505.9 lto stroke
newpath 163.8 508.7 moveto 173 508.7 lto stroke
newpath 163.8 511.5 moveto 173 511.5 lto stroke
newpath 163.8 514.3 moveto 173 514.3 lto stroke
newpath 532.1 500.4 moveto 522.9 500.4 lto stroke
newpath 532.1 503.2 moveto 522.9 503.2 lto stroke
newpath 532.1 505.9 moveto 522.9 505.9 lto stroke
newpath 532.1 508.7 moveto 522.9 508.7 lto stroke
newpath 532.1 511.5 moveto 522.9 511.5 lto stroke
newpath 532.1 514.3 moveto 522.9 514.3 lto stroke
  1.5 setlinewidth 1 setlinejoin [14.4 7.2] 0 setdash
% ---  xt1=-.5 tsx=.5 mtx=1  yt1=0 tsy=1 mty=1
 % FRME: Label axes ...
   347.9   500.4 moveto 0 h 3 mul neg rmoveto
   163.8   507.3 moveto h 2 mul max add neg 0 rmoveto
 % FRME: adding title ...
   532.1   514.3 moveto 0 h 0.5 mul rmoveto
  1.5 setlinewidth 1 setlinejoin [ ] 0 setdash
% --- plcrv: new curve, 501 pts lt 1 bold 3 ---
gsave newpath 163.8 500.4 moveto 163.8 514.3 lineto
              532.1 514.3 lineto 532.1 500.4 lineto closepath clip
newpath 163.8 500.5 moveto 164.5 500.5 lto
    165.3    500.5 lto
    166.0    500.5 lto
    166.7    500.5 lto
    167.5    500.5 lto
    168.2    500.5 lto
    169.0    500.5 lto
    169.7    500.5 lto
    170.4    500.5 lto
    171.2    500.5 lto
    171.9    500.6 lto
    172.6    500.6 lto
    173.4    500.6 lto
    174.1    500.6 lto
    174.8    500.6 lto
    175.6    500.6 lto
    176.3    500.6 lto
    177.1    500.6 lto
    177.8    500.6 lto
    178.5    500.7 lto
    179.3    500.7 lto
    180.0    500.7 lto
    180.7    500.7 lto
    181.5    500.7 lto
    182.2    500.7 lto
    183.0    500.7 lto
    183.7    500.7 lto
    184.4    500.7 lto
    185.2    500.8 lto
    185.9    500.8 lto
    186.6    500.8 lto
    187.4    500.8 lto
    188.1    500.8 lto
    188.8    500.8 lto
    189.6    500.8 lto
    190.3    500.9 lto
    191.1    500.9 lto
    191.8    500.9 lto
    192.5    500.9 lto
    193.3    500.9 lto
    194.0    500.9 lto
    194.7    500.9 lto
    195.5    501.0 lto
    196.2    501.0 lto
    196.9    501.0 lto
    197.7    501.0 lto
    198.4    501.0 lto
    199.2    501.0 lto
    199.9    501.1 lto
    200.6    501.1 lto
    201.4    501.1 lto
    202.1    501.1 lto
    202.8    501.1 lto
    203.6    501.2 lto
    204.3    501.2 lto
    205.0    501.2 lto
    205.8    501.2 lto
    206.5    501.2 lto
    207.3    501.3 lto
    208.0    501.3 lto
    208.7    501.3 lto
    209.5    501.3 lto
    210.2    501.3 lto
    210.9    501.4 lto
    211.7    501.4 lto
    212.4    501.4 lto
    213.1    501.4 lto
    213.9    501.5 lto
    214.6    501.5 lto
    215.4    501.5 lto
    216.1    501.5 lto
    216.8    501.5 lto
    217.6    501.6 lto
    218.3    501.6 lto
    219.0    501.6 lto
    219.8    501.7 lto
    220.5    501.7 lto
    221.3    501.7 lto
    222.0    501.7 lto
    222.7    501.8 lto
    223.5    501.8 lto
    224.2    501.8 lto
    224.9    501.9 lto
    225.7    501.9 lto
    226.4    501.9 lto
    227.1    502.0 lto
    227.9    502.0 lto
    228.6    502.0 lto
    229.4    502.1 lto
    230.1    502.1 lto
    230.8    502.1 lto
    231.6    502.2 lto
    232.3    502.2 lto
    233.0    502.2 lto
    233.8    502.3 lto
    234.5    502.3 lto
    235.2    502.4 lto
    236.0    502.4 lto
    236.7    502.5 lto
    237.5    502.5 lto
    238.2    502.6 lto
    238.9    502.6 lto
    239.7    502.7 lto
    240.4    502.7 lto
    241.1    502.8 lto
    241.9    502.9 lto
    242.6    502.9 lto
    243.3    503.0 lto
    244.1    503.0 lto
    244.8    503.1 lto
    245.6    503.2 lto
    246.3    503.3 lto
    247.0    503.4 lto
    247.8    503.6 lto
    248.5    503.8 lto
    249.2    503.9 lto
    250.0    503.9 lto
    250.7    504.0 lto
    251.5    504.1 lto
    252.2    504.1 lto
    252.9    504.2 lto
    253.7    504.3 lto
    254.4    504.4 lto
    255.1    504.4 lto
    255.9    504.5 lto
    256.6    504.6 lto
    257.3    504.6 lto
    258.1    504.7 lto
    258.8    504.8 lto
    259.6    504.9 lto
    260.3    504.9 lto
    261.0    505.1 lto
    261.8    505.2 lto
    262.5    505.3 lto
    263.2    505.4 lto
    264.0    505.5 lto
    264.7    505.6 lto
    265.4    505.7 lto
    266.2    505.9 lto
    266.9    506.0 lto
    267.7    506.2 lto
    268.4    506.4 lto
    269.1    506.7 lto
    269.9    507.1 lto
    270.6    507.5 lto
    271.3    508.0 lto
    272.1    508.7 lto
    272.8    509.4 lto
    273.5    509.6 lto
    274.3    509.4 lto
    275.0    509.0 lto
    275.8    507.9 lto
    276.5    506.8 lto
    277.2    506.3 lto
    278.0    505.9 lto
    278.7    505.6 lto
    279.4    505.4 lto
    280.2    505.1 lto
    280.9    504.9 lto
    281.6    504.8 lto
    282.4    504.6 lto
    283.1    504.5 lto
    283.9    504.3 lto
    284.6    504.2 lto
    285.3    504.0 lto
    286.1    503.9 lto
    286.8    503.9 lto
    287.5    503.9 lto
    288.3    503.8 lto
    289.0    503.7 lto
    289.8    503.7 lto
    290.5    503.6 lto
    291.2    503.5 lto
    292.0    503.4 lto
    292.7    503.4 lto
    293.4    503.3 lto
    294.2    503.1 lto
    294.9    503.0 lto
    295.6    503.0 lto
    296.4    502.9 lto
    297.1    502.9 lto
    297.9    502.9 lto
    298.6    502.8 lto
    299.3    502.8 lto
    300.1    502.8 lto
    300.8    502.8 lto
    301.5    502.8 lto
    302.3    502.8 lto
    303.0    502.9 lto
    303.7    503.0 lto
    304.5    504.1 lto
    305.2    506.2 lto
    306.0    508.1 lto
    306.7    509.0 lto
    307.4    510.5 lto
    308.2    511.8 lto
    308.9    511.1 lto
    309.6    510.2 lto
    310.4    509.3 lto
    311.1    507.9 lto
    311.8    506.4 lto
    312.6    505.7 lto
    313.3    505.4 lto
    314.1    505.1 lto
    314.8    505.0 lto
    315.5    504.9 lto
    316.3    504.9 lto
    317.0    505.1 lto
    317.7    505.3 lto
    318.5    505.4 lto
    319.2    505.7 lto
    320.0    506.2 lto
    320.7    506.7 lto
    321.4    507.1 lto
    322.2    507.3 lto
    322.9    507.5 lto
    323.6    507.6 lto
    324.4    507.7 lto
    325.1    507.8 lto
    325.8    508.0 lto
    326.6    508.2 lto
    327.3    508.4 lto
    328.1    508.5 lto
    328.8    508.6 lto
    329.5    508.8 lto
    330.3    509.0 lto
    331.0    509.1 lto
    331.7    509.1 lto
    332.5    509.1 lto
    333.2    509.3 lto
    333.9    509.5 lto
    334.7    509.9 lto
    335.4    510.4 lto
    336.2    510.8 lto
    336.9    511.3 lto
    337.6    512.3 lto
    338.4    513.2 lto
    339.1    513.4 lto
    339.8    513.1 lto
    340.6    512.6 lto
    341.3    512.2 lto
    342.0    511.7 lto
    342.8    511.2 lto
    343.5    510.8 lto
    344.3    510.3 lto
    345.0    509.6 lto
    345.7    509.0 lto
    346.5    508.6 lto
    347.2    508.2 lto
    347.9    507.8 lto
    348.7    507.5 lto
    349.4    507.2 lto
    350.1    507.0 lto
    350.9    506.7 lto
    351.6    506.5 lto
    352.4    506.3 lto
    353.1    506.0 lto
    353.8    505.8 lto
    354.6    505.6 lto
    355.3    505.5 lto
    356.0    505.4 lto
    356.8    505.3 lto
    357.5    505.1 lto
    358.3    505.0 lto
    359.0    504.9 lto
    359.7    504.8 lto
    360.5    504.7 lto
    361.2    504.6 lto
    361.9    504.5 lto
    362.7    504.4 lto
    363.4    504.3 lto
    364.1    504.2 lto
    364.9    504.1 lto
    365.6    504.0 lto
    366.4    503.9 lto
    367.1    503.9 lto
    367.8    503.8 lto
    368.6    503.7 lto
    369.3    503.7 lto
    370.0    503.6 lto
    370.8    503.5 lto
    371.5    503.5 lto
    372.2    503.4 lto
    373.0    503.3 lto
    373.7    503.3 lto
    374.5    503.2 lto
    375.2    503.2 lto
    375.9    503.2 lto
    376.7    503.1 lto
    377.4    503.1 lto
    378.1    503.0 lto
    378.9    503.0 lto
    379.6    502.9 lto
    380.3    502.9 lto
    381.1    502.9 lto
    381.8    502.9 lto
    382.6    502.8 lto
    383.3    502.8 lto
    384.0    502.7 lto
    384.8    502.7 lto
    385.5    502.7 lto
    386.2    502.7 lto
    387.0    502.6 lto
    387.7    502.6 lto
    388.5    502.6 lto
    389.2    502.7 lto
    389.9    502.7 lto
    390.7    502.7 lto
    391.4    502.8 lto
    392.1    502.8 lto
    392.9    502.8 lto
    393.6    502.7 lto
    394.3    502.7 lto
    395.1    502.7 lto
    395.8    502.7 lto
    396.6    502.6 lto
    397.3    502.5 lto
    398.0    502.4 lto
    398.8    502.3 lto
    399.5    502.2 lto
    400.2    502.1 lto
    401.0    502.1 lto
    401.7    502.1 lto
    402.4    502.0 lto
    403.2    502.0 lto
    403.9    502.0 lto
    404.7    502.0 lto
    405.4    502.0 lto
    406.1    502.0 lto
    406.9    502.0 lto
    407.6    502.1 lto
    408.3    502.2 lto
    409.1    502.5 lto
    409.8    502.6 lto
    410.5    502.3 lto
    411.3    502.0 lto
    412.0    501.8 lto
    412.8    501.7 lto
    413.5    501.6 lto
    414.2    501.6 lto
    415.0    501.5 lto
    415.7    501.5 lto
    416.4    501.4 lto
    417.2    501.4 lto
    417.9    501.4 lto
    418.6    501.4 lto
    419.4    501.5 lto
    420.1    501.7 lto
    420.9    502.1 lto
    421.6    502.5 lto
    422.3    502.5 lto
    423.1    502.5 lto
    423.8    502.6 lto
    424.5    502.6 lto
    425.3    502.7 lto
    426.0    502.7 lto
    426.8    502.8 lto
    427.5    502.7 lto
    428.2    502.7 lto
    429.0    502.7 lto
    429.7    502.7 lto
    430.4    502.7 lto
    431.2    502.7 lto
    431.9    502.7 lto
    432.6    502.7 lto
    433.4    502.7 lto
    434.1    502.7 lto
    434.9    502.6 lto
    435.6    502.6 lto
    436.3    502.6 lto
    437.1    502.6 lto
    437.8    502.6 lto
    438.5    502.6 lto
    439.3    502.6 lto
    440.0    502.5 lto
    440.7    502.5 lto
    441.5    502.5 lto
    442.2    502.5 lto
    443.0    502.5 lto
    443.7    502.5 lto
    444.4    502.4 lto
    445.2    502.4 lto
    445.9    502.3 lto
    446.6    502.3 lto
    447.4    502.3 lto
    448.1    502.2 lto
    448.8    502.2 lto
    449.6    502.1 lto
    450.3    502.1 lto
    451.1    502.1 lto
    451.8    502.1 lto
    452.5    502.0 lto
    453.3    502.0 lto
    454.0    502.0 lto
    454.7    502.0 lto
    455.5    502.0 lto
    456.2    502.0 lto
    457.0    502.0 lto
    457.7    502.0 lto
    458.4    502.0 lto
    459.2    502.1 lto
    459.9    502.1 lto
    460.6    502.2 lto
    461.4    502.2 lto
    462.1    502.3 lto
    462.8    502.3 lto
    463.6    502.3 lto
    464.3    502.4 lto
    465.1    502.4 lto
    465.8    502.5 lto
    466.5    502.5 lto
    467.3    502.6 lto
    468.0    502.6 lto
    468.7    502.6 lto
    469.5    502.7 lto
    470.2    502.7 lto
    470.9    502.7 lto
    471.7    502.8 lto
    472.4    502.8 lto
    473.2    502.8 lto
    473.9    502.9 lto
    474.6    502.9 lto
    475.4    502.9 lto
    476.1    503.0 lto
    476.8    503.0 lto
    477.6    503.0 lto
    478.3    503.0 lto
    479.0    503.0 lto
    479.8    503.1 lto
    480.5    503.1 lto
    481.3    503.1 lto
    482.0    503.1 lto
    482.7    503.1 lto
    483.5    503.2 lto
    484.2    503.2 lto
    484.9    503.2 lto
    485.7    503.2 lto
    486.4    503.3 lto
    487.1    503.3 lto
    487.9    503.3 lto
    488.6    503.3 lto
    489.4    503.3 lto
    490.1    503.3 lto
    490.8    503.4 lto
    491.6    503.4 lto
    492.3    503.4 lto
    493.0    503.4 lto
    493.8    503.4 lto
    494.5    503.4 lto
    495.3    503.5 lto
    496.0    503.5 lto
    496.7    503.5 lto
    497.5    503.5 lto
    498.2    503.5 lto
    498.9    503.5 lto
    499.7    503.5 lto
    500.4    503.6 lto
    501.1    503.6 lto
    501.9    503.6 lto
    502.6    503.6 lto
    503.4    503.6 lto
    504.1    503.6 lto
    504.8    503.6 lto
    505.6    503.7 lto
    506.3    503.7 lto
    507.0    503.7 lto
    507.8    503.7 lto
    508.5    503.7 lto
    509.2    503.7 lto
    510.0    503.7 lto
    510.7    503.7 lto
    511.5    503.7 lto
    512.2    503.7 lto
    512.9    503.7 lto
    513.7    503.7 lto
    514.4    503.7 lto
    515.1    503.7 lto
    515.9    503.7 lto
    516.6    503.7 lto
    517.3    503.8 lto
    518.1    503.8 lto
    518.8    503.8 lto
    519.6    503.8 lto
    520.3    503.8 lto
    521.0    503.8 lto
    521.8    503.8 lto
    522.5    503.8 lto
    523.2    503.8 lto
    524.0    503.8 lto
    524.7    503.8 lto
    525.5    503.8 lto
    526.2    503.8 lto
    526.9    503.8 lto
    527.7    503.8 lto
    528.4    503.8 lto
    529.1    503.8 lto
    529.9    503.8 lto
    530.6    503.8 lto
    531.3    503.8 lto
 532.1 503.8 lto

 stroke grestore
  1.5 setlinewidth 1 setlinejoin [14.4 7.2] 0 setdash
% --- plcrv: new curve, 2 pts lt 2 bold 3 len=(14.4 7.2) ---
gsave newpath 344.2 500.4 moveto 344.2 514.3 lineto
              417.9 514.3 lineto 417.9 500.4 lineto closepath clip
newpath 381 500.4 moveto 381 514.3 lto

 stroke grestore
% pltstp: frame corners (GU): lb= (.05 .62)  rt = (.98 .9)
% --- FRME : axes at x=-.5 .5  y=0 40  bold=3
/max 0 def 
  1.5 setlinewidth 1 setlinejoin [ ] 0 setdash
newpath 163.8 389.5 moveto 532.1 389.5 lto
 532.1 500.4 lto
 163.8 500.4 lto
 163.8 389.5 lto closepath gsave 1 1 1 setrgbcolor fill grestore stroke
newpath 163.8 389.5 moveto 163.8 392.3 lto stroke
gsave blank-on    163.8   389.5 moveto (-0.5) showa  grestore
newpath 347.9 389.5 moveto 347.9 392.3 lto stroke
gsave blank-on    347.9   389.5 moveto (0) showa  grestore
newpath 532.1 389.5 moveto 532.1 392.3 lto stroke
gsave blank-on    532.1   389.5 moveto (0.5) showa  grestore
newpath 163.8 500.4 moveto 163.8 497.6 lto stroke
newpath 347.9 500.4 moveto 347.9 497.6 lto stroke
newpath 532.1 500.4 moveto 532.1 497.6 lto stroke
newpath 163.8 389.5 moveto 173 389.5 lto stroke
gsave blank-on    163.8   389.5 moveto (0) showo  grestore
newpath 163.8 417.2 moveto 173 417.2 lto stroke
gsave blank-on    163.8   417.2 moveto (10) showo  grestore
newpath 163.8 445 moveto 173 445 lto stroke
gsave blank-on    163.8   445.0 moveto (20) showo  grestore
newpath 163.8 472.7 moveto 173 472.7 lto stroke
gsave blank-on    163.8   472.7 moveto (30) showo  grestore
newpath 163.8 500.4 moveto 173 500.4 lto stroke
gsave blank-on    163.8   500.4 moveto (40) showo  grestore
newpath 532.1 389.5 moveto 522.9 389.5 lto stroke
newpath 532.1 417.2 moveto 522.9 417.2 lto stroke
newpath 532.1 445 moveto 522.9 445 lto stroke
newpath 532.1 472.7 moveto 522.9 472.7 lto stroke
newpath 532.1 500.4 moveto 522.9 500.4 lto stroke
  1.5 setlinewidth 1 setlinejoin [14.4 7.2] 0 setdash
% ---  xt1=-.5 tsx=.5 mtx=1  yt1=0 tsy=10 mty=1
 % FRME: Label axes ...
   347.9   389.5 moveto 0 h 3 mul neg rmoveto
   163.8   445.0 moveto h 2 mul max add neg 0 rmoveto
 % FRME: adding title ...
   532.1   500.4 moveto 0 h 0.5 mul rmoveto
  1.5 setlinewidth 1 setlinejoin [ ] 0 setdash
% --- plcrv: new curve, 501 pts lt 1 bold 3 ---
gsave newpath 163.8 389.5 moveto 163.8 500.4 lineto
              532.1 500.4 lineto 532.1 389.5 lineto closepath clip
newpath 163.8 389.5 moveto 164.5 389.5 lto
    165.3    389.5 lto
    166.0    389.5 lto
    166.7    389.5 lto
    167.5    389.5 lto
    168.2    389.5 lto
    169.0    389.5 lto
    169.7    389.5 lto
    170.4    389.5 lto
    171.2    389.5 lto
    171.9    389.5 lto
    172.6    389.5 lto
    173.4    389.5 lto
    174.1    389.5 lto
    174.8    389.5 lto
    175.6    389.5 lto
    176.3    389.5 lto
    177.1    389.5 lto
    177.8    389.5 lto
    178.5    389.5 lto
    179.3    389.5 lto
    180.0    389.6 lto
    180.7    389.6 lto
    181.5    389.6 lto
    182.2    389.6 lto
    183.0    389.6 lto
    183.7    389.6 lto
    184.4    389.6 lto
    185.2    389.6 lto
    185.9    389.6 lto
    186.6    389.6 lto
    187.4    389.6 lto
    188.1    389.6 lto
    188.8    389.6 lto
    189.6    389.6 lto
    190.3    389.6 lto
    191.1    389.6 lto
    191.8    389.6 lto
    192.5    389.6 lto
    193.3    389.6 lto
    194.0    389.6 lto
    194.7    389.6 lto
    195.5    389.6 lto
    196.2    389.6 lto
    196.9    389.6 lto
    197.7    389.7 lto
    198.4    389.7 lto
    199.2    389.7 lto
    199.9    389.7 lto
    200.6    389.7 lto
    201.4    389.7 lto
    202.1    389.7 lto
    202.8    389.7 lto
    203.6    389.7 lto
    204.3    389.7 lto
    205.0    389.7 lto
    205.8    389.8 lto
    206.5    389.8 lto
    207.3    389.8 lto
    208.0    389.8 lto
    208.7    389.8 lto
    209.5    389.8 lto
    210.2    389.8 lto
    210.9    389.8 lto
    211.7    389.9 lto
    212.4    389.9 lto
    213.1    389.9 lto
    213.9    389.9 lto
    214.6    389.9 lto
    215.4    389.9 lto
    216.1    390.0 lto
    216.8    390.0 lto
    217.6    390.0 lto
    218.3    390.0 lto
    219.0    390.1 lto
    219.8    390.1 lto
    220.5    390.1 lto
    221.3    390.1 lto
    222.0    390.2 lto
    222.7    390.2 lto
    223.5    390.2 lto
    224.2    390.3 lto
    224.9    390.3 lto
    225.7    390.3 lto
    226.4    390.4 lto
    227.1    390.4 lto
    227.9    390.5 lto
    228.6    390.5 lto
    229.4    390.6 lto
    230.1    390.6 lto
    230.8    390.7 lto
    231.6    390.7 lto
    232.3    390.8 lto
    233.0    390.9 lto
    233.8    390.9 lto
    234.5    391.0 lto
    235.2    391.1 lto
    236.0    391.2 lto
    236.7    391.3 lto
    237.5    391.4 lto
    238.2    391.5 lto
    238.9    391.6 lto
    239.7    391.8 lto
    240.4    391.9 lto
    241.1    392.1 lto
    241.9    392.4 lto
    242.6    392.6 lto
    243.3    392.8 lto
    244.1    393.1 lto
    244.8    393.5 lto
    245.6    394.0 lto
    246.3    395.0 lto
    247.0    398.1 lto
    247.8    402.9 lto
    248.5    407.3 lto
    249.2    408.0 lto
    250.0    407.1 lto
    250.7    408.2 lto
    251.5    409.1 lto
    252.2    409.8 lto
    252.9    410.4 lto
    253.7    410.6 lto
    254.4    410.5 lto
    255.1    410.8 lto
    255.9    411.3 lto
    256.6    411.9 lto
    257.3    412.5 lto
    258.1    413.1 lto
    258.8    413.6 lto
    259.6    414.0 lto
    260.3    414.4 lto
    261.0    414.8 lto
    261.8    415.2 lto
    262.5    415.7 lto
    263.2    416.3 lto
    264.0    417.0 lto
    264.7    417.7 lto
    265.4    418.5 lto
    266.2    419.3 lto
    266.9    420.1 lto
    267.7    420.9 lto
    268.4    422.0 lto
    269.1    423.5 lto
    269.9    425.3 lto
    270.6    427.5 lto
    271.3    430.5 lto
    272.1    434.1 lto
    272.8    436.5 lto
    273.5    436.3 lto
    274.3    435.0 lto
    275.0    433.1 lto
    275.8    428.6 lto
    276.5    424.3 lto
    277.2    421.9 lto
    278.0    420.2 lto
    278.7    418.9 lto
    279.4    417.9 lto
    280.2    417.0 lto
    280.9    416.2 lto
    281.6    415.8 lto
    282.4    415.3 lto
    283.1    414.6 lto
    283.9    413.9 lto
    284.6    413.4 lto
    285.3    412.9 lto
    286.1    412.5 lto
    286.8    412.4 lto
    287.5    412.6 lto
    288.3    412.7 lto
    289.0    412.5 lto
    289.8    412.3 lto
    290.5    412.2 lto
    291.2    411.7 lto
    292.0    411.0 lto
    292.7    411.2 lto
    293.4    410.6 lto
    294.2    408.6 lto
    294.9    406.8 lto
    295.6    405.8 lto
    296.4    405.4 lto
    297.1    405.0 lto
    297.9    404.6 lto
    298.6    403.9 lto
    299.3    403.5 lto
    300.1    403.3 lto
    300.8    403.1 lto
    301.5    403.0 lto
    302.3    403.1 lto
    303.0    403.4 lto
    303.7    404.3 lto
    304.5    413.1 lto
    305.2    432.1 lto
    306.0    448.9 lto
    306.7    458.9 lto
    307.4    472.7 lto
    308.2    486.3 lto
    308.9    485.7 lto
    309.6    478.6 lto
    310.4    472.7 lto
    311.1    463.9 lto
    311.8    455.8 lto
    312.6    451.6 lto
    313.3    448.6 lto
    314.1    446.4 lto
    314.8    444.9 lto
    315.5    443.6 lto
    316.3    442.5 lto
    317.0    441.8 lto
    317.7    441.1 lto
    318.5    440.6 lto
    319.2    440.6 lto
    320.0    440.9 lto
    320.7    441.2 lto
    321.4    441.3 lto
    322.2    441.3 lto
    322.9    441.4 lto
    323.6    440.6 lto
    324.4    438.9 lto
    325.1    437.8 lto
    325.8    437.2 lto
    326.6    437.0 lto
    327.3    436.4 lto
    328.1    435.3 lto
    328.8    434.6 lto
    329.5    434.5 lto
    330.3    434.9 lto
    331.0    435.3 lto
    331.7    435.5 lto
    332.5    435.8 lto
    333.2    436.5 lto
    333.9    437.5 lto
    334.7    439.4 lto
    335.4    441.7 lto
    336.2    444.1 lto
    336.9    447.3 lto
    337.6    452.8 lto
    338.4    458.1 lto
    339.1    459.8 lto
    339.8    459.0 lto
    340.6    457.6 lto
    341.3    456.3 lto
    342.0    454.7 lto
    342.8    453.1 lto
    343.5    452.2 lto
    344.3    449.6 lto
    345.0    445.5 lto
    345.7    442.5 lto
    346.5    440.5 lto
    347.2    439.2 lto
    347.9    438.1 lto
    348.7    436.7 lto
    349.4    435.6 lto
    350.1    436.0 lto
    350.9    435.8 lto
    351.6    434.2 lto
    352.4    431.2 lto
    353.1    421.4 lto
    353.8    411.8 lto
    354.6    408.6 lto
    355.3    407.6 lto
    356.0    406.9 lto
    356.8    406.2 lto
    357.5    405.8 lto
    358.3    405.4 lto
    359.0    405.1 lto
    359.7    404.7 lto
    360.5    404.6 lto
    361.2    404.3 lto
    361.9    403.7 lto
    362.7    403.3 lto
    363.4    403.0 lto
    364.1    402.9 lto
    364.9    402.8 lto
    365.6    402.9 lto
    366.4    402.9 lto
    367.1    403.0 lto
    367.8    403.7 lto
    368.6    404.5 lto
    369.3    404.5 lto
    370.0    404.7 lto
    370.8    405.0 lto
    371.5    405.2 lto
    372.2    405.4 lto
    373.0    405.5 lto
    373.7    405.7 lto
    374.5    406.0 lto
    375.2    406.4 lto
    375.9    406.7 lto
    376.7    407.0 lto
    377.4    407.5 lto
    378.1    408.1 lto
    378.9    408.8 lto
    379.6    409.7 lto
    380.3    410.4 lto
    381.1    411.1 lto
    381.8    411.9 lto
    382.6    413.0 lto
    383.3    414.0 lto
    384.0    414.9 lto
    384.8    415.8 lto
    385.5    416.9 lto
    386.2    418.1 lto
    387.0    419.5 lto
    387.7    421.0 lto
    388.5    422.8 lto
    389.2    425.3 lto
    389.9    428.5 lto
    390.7    432.8 lto
    391.4    437.6 lto
    392.1    442.1 lto
    392.9    445.5 lto
    393.6    446.0 lto
    394.3    446.4 lto
    395.1    449.3 lto
    395.8    452.6 lto
    396.6    455.5 lto
    397.3    458.2 lto
    398.0    461.2 lto
    398.8    465.5 lto
    399.5    468.0 lto
    400.2    468.7 lto
    401.0    469.7 lto
    401.7    470.0 lto
    402.4    471.1 lto
    403.2    471.3 lto
    403.9    471.3 lto
    404.7    471.8 lto
    405.4    471.2 lto
    406.1    471.0 lto
    406.9    472.5 lto
    407.6    475.3 lto
    408.3    482.8 lto
    409.1    490.6 lto
    409.8    488.6 lto
    410.5    481.8 lto
    411.3    479.3 lto
    412.0    479.7 lto
    412.8    480.2 lto
    413.5    480.1 lto
    414.2    479.2 lto
    415.0    478.4 lto
    415.7    478.3 lto
    416.4    480.7 lto
    417.2    484.2 lto
    417.9    485.8 lto
    418.6    490.1 lto
    419.4    497.7 lto
    420.1    514.8 lto
    420.9    564.0 lto
    421.6    554.2 lto
    422.3    494.6 lto
    423.1    474.9 lto
    423.8    466.6 lto
    424.5    461.6 lto
    425.3    457.3 lto
    426.0    454.0 lto
    426.8    451.1 lto
    427.5    447.9 lto
    428.2    445.3 lto
    429.0    443.4 lto
    429.7    442.0 lto
    430.4    440.8 lto
    431.2    439.8 lto
    431.9    438.2 lto
    432.6    436.4 lto
    433.4    435.1 lto
    434.1    434.1 lto
    434.9    433.4 lto
    435.6    433.0 lto
    436.3    432.4 lto
    437.1    431.7 lto
    437.8    431.3 lto
    438.5    431.2 lto
    439.3    431.0 lto
    440.0    430.6 lto
    440.7    430.2 lto
    441.5    430.1 lto
    442.2    430.1 lto
    443.0    430.2 lto
    443.7    431.7 lto
    444.4    432.6 lto
    445.2    431.2 lto
    445.9    430.7 lto
    446.6    431.8 lto
    447.4    433.5 lto
    448.1    432.5 lto
    448.8    427.6 lto
    449.6    422.0 lto
    450.3    417.9 lto
    451.1    415.5 lto
    451.8    413.5 lto
    452.5    411.5 lto
    453.3    410.3 lto
    454.0    408.6 lto
    454.7    406.0 lto
    455.5    403.6 lto
    456.2    401.8 lto
    457.0    400.4 lto
    457.7    399.6 lto
    458.4    399.3 lto
    459.2    399.3 lto
    459.9    399.4 lto
    460.6    399.4 lto
    461.4    399.4 lto
    462.1    399.3 lto
    462.8    399.3 lto
    463.6    399.2 lto
    464.3    399.1 lto
    465.1    399.1 lto
    465.8    399.0 lto
    466.5    399.0 lto
    467.3    398.9 lto
    468.0    398.7 lto
    468.7    398.4 lto
    469.5    398.3 lto
    470.2    398.2 lto
    470.9    398.2 lto
    471.7    398.1 lto
    472.4    398.0 lto
    473.2    397.9 lto
    473.9    397.8 lto
    474.6    397.7 lto
    475.4    397.6 lto
    476.1    397.5 lto
    476.8    397.4 lto
    477.6    397.3 lto
    478.3    397.1 lto
    479.0    397.0 lto
    479.8    397.0 lto
    480.5    396.9 lto
    481.3    396.8 lto
    482.0    396.8 lto
    482.7    396.7 lto
    483.5    396.7 lto
    484.2    396.6 lto
    484.9    396.6 lto
    485.7    396.5 lto
    486.4    396.5 lto
    487.1    396.4 lto
    487.9    396.4 lto
    488.6    396.3 lto
    489.4    396.3 lto
    490.1    396.2 lto
    490.8    396.2 lto
    491.6    396.1 lto
    492.3    396.1 lto
    493.0    396.0 lto
    493.8    396.0 lto
    494.5    395.9 lto
    495.3    395.9 lto
    496.0    395.8 lto
    496.7    395.8 lto
    497.5    395.8 lto
    498.2    395.7 lto
    498.9    395.7 lto
    499.7    395.6 lto
    500.4    395.6 lto
    501.1    395.5 lto
    501.9    395.4 lto
    502.6    395.4 lto
    503.4    395.3 lto
    504.1    395.2 lto
    504.8    395.2 lto
    505.6    395.2 lto
    506.3    395.1 lto
    507.0    395.1 lto
    507.8    395.0 lto
    508.5    395.0 lto
    509.2    394.9 lto
    510.0    394.9 lto
    510.7    394.9 lto
    511.5    394.8 lto
    512.2    394.8 lto
    512.9    394.8 lto
    513.7    394.7 lto
    514.4    394.7 lto
    515.1    394.6 lto
    515.9    394.6 lto
    516.6    394.6 lto
    517.3    394.5 lto
    518.1    394.5 lto
    518.8    394.5 lto
    519.6    394.4 lto
    520.3    394.4 lto
    521.0    394.4 lto
    521.8    394.4 lto
    522.5    394.3 lto
    523.2    394.3 lto
    524.0    394.3 lto
    524.7    394.2 lto
    525.5    394.2 lto
    526.2    394.2 lto
    526.9    394.1 lto
    527.7    394.1 lto
    528.4    394.1 lto
    529.1    394.0 lto
    529.9    394.0 lto
    530.6    393.9 lto
    531.3    393.9 lto
 532.1 393.9 lto

 stroke grestore
  1.5 setlinewidth 1 setlinejoin [14.4 7.2] 0 setdash
% --- plcrv: new curve, 2 pts lt 2 bold 3 len=(14.4 7.2) ---
gsave newpath 344.2 389.5 moveto 344.2 500.4 lineto
              417.9 500.4 lineto 417.9 389.5 lineto closepath clip
newpath 381 389.5 moveto 381 500.4 lto

 stroke grestore
%%BoundingBox: 163.8 389.5 532.1 528.1
showpage
