from comp import test2_check,runprogs,rmfiles
def test(args,bindir,testdir,workdir): #Fixed. called as >testecalj Fe_magnon
    MATERIAL="fe"
    ncore=args.np
    lmfa= f'mpirun -np 1 {bindir}/lmfa '
    lmf = f'mpirun -np {args.np} {bindir}/lmf '
    outfile='out.lmf.fe'
    dat1='TrKpm.syml001'
    dat2='TrRpm.syml001'
    tall=''

    rmfiles(workdir,[outfile,dat1,dat2])
    if(args.checkonly): runprogs([
            "rm -rf summary.txt"
            ],quiet=True)
    else: runprogs([
        lmfa + f" {MATERIAL} > "+ outfile,
        lmf  + f" {MATERIAL} > "+ outfile,
        f"{bindir}/job_band   {MATERIAL} -np {ncore} --NoGnuplot",  # band plot
        f"{bindir}/job_magnon -np {ncore} {MATERIAL}",              # magnon calculation
        "gnuplot mag3d.glt",
        "gnuplot r_k.glt",
        "gnuplot wan_bandplot.glt"
    ])
    print(dat1,end=': ')
    # skip condition: omega ~ 0 (K(q,ω) has poles near ω=0 sensitive to small drift)
    skip_w0 = lambda line: len(line.split()) >= 5 and abs(float(line.split()[4])) < 1e-6
    tall+=test2_check(testdir+'/'+dat1, workdir+'/'+dat1, abs_tol=1e-3, rel_tol=1e-3, skipcond=skip_w0)
    print(dat2,end=': ')
    # R(q,ω) has 1/ω-like poles: skip ω ~ 0 rows (values can diverge/sign-flip on tiny drift)
    tall+=test2_check(testdir+'/'+dat2, workdir+'/'+dat2, abs_tol=1e-3, rel_tol=1e-3, skipcond=skip_w0)
    message1=f'''
    ==========================================================================
    Magnon calculation finished.
      TrKpm.syml001: K(q,omega) trace
      TrRpm.syml001: R(q,omega) trace
      *.pdf generated by gnuplot
    To view: evince {workdir}/magnon3d_100.pdf
    Compare with previous: {testdir}/eps/*.eps
    ==========================================================================
    '''
    print(message1)
    return tall
