#!/bin/csh -f 
grep VerNum fpgw/gwsrc/switches.F 
echo $argv[1] $argv[2]
if( $argv[2] == "go" ) then
set exec = fpgw/exec/
set test = fpgw/TESTinstallGW/
tar -cvf fpgw$argv[1].tar fpgw/*/*.F fpgw/tote/make* fpgw/tote/[tcs]* $exec/[cegsmt]*  util/*.F util/pl* util/make* fpgw/Miyake/maxloc/*.F \
     fpgw/exec/d* fpgw/exec/hqpemetal fpgw/exec/inf* fpgw/exec/lmgw* fpgw/exec/plotg* fpgw/exec/xqp* \
     TOOLS/* $test/*/ctrl.* $test/*/GWinput $test/*/rst.* $test/*/QP* $test/*/l* $test/*/EPS* $test/*/ChiPM*.nlfc.mat $test/*/site.* 
gzip fpgw$argv[1].tar
endif

exit


