!> Finding the space group of the crystal: gensym (generators from the input string, operations of the lattice, those
!> leaving the crystal invariant, the group they generate). Split from m_mksym_util (2026-10-02): this is the ecalj backend
!> of the finder in MD/symmetry_spglib.md; spglib through symmetry.json is to come as another backend.
module m_symfind
  use m_lgunit,only:stdo
  use m_ftox
  use m_nvfortran,only: findloc
  use m_mpi,only: master_mpi
  use m_symop_util,only: spgcop,spgprd,spgeql,grpeql,latvec,asymop
  use m_symderive,only: symtbl,iclbsjx
  public gensym,ngmx,ngnmx
  private
  real(8),parameter:: toll=1d-4,tiny=1d-4,epsr=1d-12
  integer,parameter:: ngnmx=10
  integer,parameter:: ngmx = 48
  ! gensym(..., faithful) (2026-10-02): the space group used is one with distinct rotations (one translation per rotation, closed as a group).
  ! A cell with pure translations other than its lattice vectors (a supercell; e.g. diamond Si in the 8-atom cubic cell has the
  ! 3 fcc centerings) has more operations than ngmx (48 rotations x 4 translations) and stopped in sgroup ("probably bad
  ! translation"). With faithful, gensym chooses the translations of the generators among t + (pure translations) so that the
  ! generated group has distinct rotations (for Si: Pn-3m, 48 operations); the pure translations are not used as symmetries
  ! (a lower but valid symmetry: the density symmetrization in symprj needs a closed group, which a mere choice of one
  ! translation per rotation is not). Set by mksym(..., faithful=.true.) for the symmetry of the crystal; not for the
  ! lattice+AF group of m_mksym, where a pure translation that exchanges up and down spins is the point.
  ! (2026-10-02 05:22: faithful was a module variable of m_mksym_util; an argument of gensym now.)
contains
  subroutine gensym(slabl,gens,symfind,nbas,nspec,ngmx,plat,platcv,bas,ips, ng,g,ag, ngen,gen,nwgens,nggen,isym,istab,faithful) !Generate the space group ops
    !i Inputs:
    !i   slabl: name of the different species.
    !i   gens:  a list of generators, in symbolic representation  NB: this list is not required; see Remarks.
    !i   symfind:=T Find any additional group operations for this basis.
    !i   nspec: number of classes, atoms in same class are symmetry-related
    !i   plat:  primitive lattice vectors (scaled by alat)
    !i   platcv:(=plat usually). Used to scale translation part of generators, when translation part specified as a multiple of
    !i         :lattice vectors.  Can be same as plat but primitive lattice vectors of "conventional unit cell"
    !i         :are sometimes used to specify these translations, e.g. when generated from spacegroup data in some books.
    !i  nbas:  number of atoms in the basis
    !i  bas:   basis vectors
    !i  ips:   the jth atom belongs to spec ips(j)
    !o Outputs:
    !o   istab: site ib is transformed into istab(ib,ig) by operation ig
    !o   g:     symmetry operation matrix (assumed dimensioned >=ngmx)
    !o   ag:    symmetry operation vector (assumed dimensioned >=ngmx)
    !o   ... The following are generated if symfind=T
    !o   isym:  numbers characterizing the symmetry of lattice and crystal. isym is index for underlying lattice (see symlat)
    !o   ng:    number of group operations
    !o   ngen:  number of symmetry generators
    !o   gen:   generators in matrix form
    !o   nwgens:generators in ascii form
    !o   nggen :number of group ops generated by generators.
    !o         :Usually nggen=ng; however nggen can exceed ng if supercell is artificial -> extra translations; see groupg
    !r Remarks:
    !r   gensym generates the space group, using the following prescription:
    !r     1.  Any generators supplied from input gens
    !r         are checked for consistency with the underlying lattice.
    !r     2.  The space group is made from these generators.
    !r     For symfind=T, we do follwoings
    !r       * The point group of the underlying lattice without the basis is generated.
    !r       * The full space group is generated from the point group
    !r       * A set of generators for this group is created
    !r   This program was adapted from the Stuttgart ASA version lmto-46.
    implicit none
    logical,intent(in):: faithful !closed group with distinct rotations when the cell has pure translations (see the module header)
    logical :: symfind
    integer :: nbas,isym(*),istab(nbas,*),nspec,ngen,ngmx, ng,nrspec(nspec),ips(nbas),nggen 
    integer:: i , j , ibas , ic , iprint, igen , mxint , ig,iwdummy1(1)
    real(8) :: plat(3,3),platcv(3,3),g(3,3,*),ag(3,*),bas(3,nbas), qlat(3,3),vol,platt(3,3),gen(3,3,ngmx),agen(3,ngmx)
    character(8) ::  slabl(*), gens*(*), nwgens*(*),xn
    character(100) :: sg,sg1,sout,sout2
    call dinv33(plat,1,qlat,vol) !Reciprocal lattice vectors --- 
    nwgens = gens
    ngen=0 !initialization buf obata added at 2023-5-12
    if(len_trim(gens) > 0) then
       call psymop(trim(gens),platcv,gen,agen,ngen)     ! Symmetry group as given by input generators ---
       nwgens = trim(gens)
    endif
    do igen = 1, ngen
       if(.NOT.latvec(3,toll,qlat,matmul(gen(:,:,igen),plat))) &
            call rx('GENSYM: imcompatible with lattice generators. igen='//trim(xn(igen)))
    enddo !write(6,*)'goto sgroup',ngen  !  do i=1,ngen     !       write(stdo,ftox)i,' gen agen=',ftof(gen(:,i),2),' ',ftof(agen(:,i),3)!  enddo
    call sgroup(gen,agen,ngen, g,ag,ng, ngmx,qlat) ! Set up space group (g,ag,ng) for  generators (gen,agen,ngen)
    !                  write(stdo,ftox)'end of sgroup ngen nggen ngmx',ngen,nggen,ngmx,ftof(ag(:,1),3)
    if (maxval(ips)/= nspec.AND.iprint() > 0)write(stdo,ftox)' GENSYM (warning)',nspec,'species supplied but only',i,'spec used ...'
    nspec = maxval(ips) 
    nrspec= [(count(ips(1:nbas)==ic),ic=1,nspec)] ! nrspec:number of atoms in the ith class
    if (symfind) then !Complete the space group. SYMGRP find. symfind=T
       call symlat(plat,ng,g,isym(1)) !Symmetry of lattice without bas
       call symcry(bas, ips,nbas,nspec,nrspec,ng,plat,qlat,g,ag,istab ) ! Symmetry of lattice with bas
       if (ng > ngmx) return
       nwgens = ' '
       groupgblock:block 
         !o Outputs: 
         !o   gen,ngen:generators, and number needed to produce g
         !o   nggen :number of group ops generated by (gen,ngen)
         !o         :usually nggen=ng unless artificial translations
         !o   nwgens  :ascii representation of generators
         integer :: imax,isop,ngloc,ngmax,iprint,ngen0,i1,i2,j1,j2,icount,ngmax2
         real(8)::gloc(3,3,ngmx),agloc(3,ngmx),xx,vec(3)
         integer :: ntau,it,itmax,ngbest
         real(8) :: tau(3,nbas),gbest(3,3,ngmx),agbest(3,ngmx),gtry(3,3,ngmx),agtry(3,ngmx)
         logical :: ovf
         call pshpr(1)
         ngen0 = ngen
         call sgroup(gen,agen,ngen, gloc,agloc,nggen, ngmx,qlat)
         call puretrans(nbas,bas,ips,qlat,plat,ntau,tau) !pure translations of the crystal (2026-10-02)
         FaithfulSubgroup: if(faithful .and. ntau>0) then
           ! The cell has ntau pure translations other than lattice vectors. Choose generators among (g, ag + tau) so that the
           ! generated group has distinct rotations (closed, no pure translation in it); greedy, the largest such group.
           if(iprint()>0) write(stdo,ftox)' gensym: the cell has',ntau,'pure translations other than lattice vectors (a supercell);', &
                ' they are not used as symmetries, and the translations of the operations are chosen to close the group'
           ngmax2=nggen
           gbest(:,:,1:nggen)=gloc(:,:,1:nggen); agbest(:,1:nggen)=agloc(:,1:nggen); ngbest=nggen
           PairStart: block ! the first two generators by trying every pair, then the greedy from each best pair; the largest group wins
             ! (the greedy alone found 12 of 48 operations for Si in the cubic cell; one best pair, 24)
             integer,parameter:: npmx=20 !the best pairs extended (400 took 11 s for Si in the cubic cell and found nothing larger)
             integer:: is1,is2,it1,it2,n1,np,ip,ngenb,ngen1
             real(8):: a1(3),a2(3),pg(3,3,2,npmx),pa(3,2,npmx),genb(3,3,ngmx),agenb(3,ngmx)
             n1=0; np=0
             do is1 = 1, ng; do it1 = 0, ntau
                a1 = ag(:,is1) + merge([0d0,0d0,0d0], tau(:,max(it1,1)), it1==0)
                do is2 = is1+1, ng; do it2 = 0, ntau
                   a2 = ag(:,is2) + merge([0d0,0d0,0d0], tau(:,max(it2,1)), it2==0)
                   gen(:,:,ngen+1)=g(:,:,is1); agen(:,ngen+1)=a1
                   gen(:,:,ngen+2)=g(:,:,is2); agen(:,ngen+2)=a2
                   call sgroup(gen,agen,ngen+2, gloc,agloc,ngloc,ngmx,qlat, overflow=ovf)
                   if(ovf) cycle
                   if(.not.distinctrot(gloc,ngloc)) cycle
                   if(ngloc>n1) then; n1=ngloc; np=0; endif
                   if(ngloc==n1 .and. np<npmx) then
                      np=np+1; pg(:,:,1,np)=g(:,:,is1); pg(:,:,2,np)=g(:,:,is2); pa(:,1,np)=a1; pa(:,2,np)=a2
                   endif
                enddo; enddo
             enddo; enddo
             ngen1=ngen; ngenb=ngen
             do ip = 1, np !greedy extension of each best pair
                ngen=ngen1+2
                gen(:,:,ngen1+1:ngen1+2)=pg(:,:,:,ip); agen(:,ngen1+1:ngen1+2)=pa(:,:,ip)
                call sgroup(gen,agen,ngen, gloc,agloc,ngloc,ngmx,qlat, overflow=ovf)
                ngmax2=ngloc; gtry(:,:,1:ngloc)=gloc(:,:,1:ngloc); agtry(:,1:ngloc)=agloc(:,1:ngloc)
                do
                   imax=0; itmax=-1; ngmax=0
                   do isop = 1, ng
                      do it = 0, ntau
                         gen(:,:,ngen+1)= g(:,:,isop)
                         agen(:,ngen+1) = ag(:,isop) + merge([0d0,0d0,0d0], tau(:,max(it,1)), it==0)
                         call sgroup(gen,agen,ngen+1, gloc,agloc,ngloc,ngmx,qlat, overflow=ovf)
                         if(ovf) cycle
                         if(.not.distinctrot(gloc,ngloc)) cycle
                         if (ngloc > ngmax) then; imax = isop; itmax = it; ngmax = ngloc; endif
                      enddo
                   enddo
                   if(ngmax<=ngmax2) exit
                   ngen = ngen+1
                   gen(:,:,ngen)= g(:,:,imax)
                   agen(:,ngen) = ag(:,imax) + merge([0d0,0d0,0d0], tau(:,max(itmax,1)), itmax==0)
                   call sgroup(gen,agen,ngen, gloc,agloc,ngloc,ngmx,qlat, overflow=ovf)
                   ngmax2=ngloc; gtry(:,:,1:ngloc)=gloc(:,:,1:ngloc); agtry(:,1:ngloc)=agloc(:,1:ngloc)
                enddo
                if(ngmax2>ngbest) then
                   ngbest=ngmax2; gbest(:,:,1:ngbest)=gtry(:,:,1:ngbest); agbest(:,1:ngbest)=agtry(:,1:ngbest)
                   ngenb=ngen; genb(:,:,1:ngen)=gen(:,:,1:ngen); agenb(:,1:ngen)=agen(:,1:ngen)
                endif
                if(ngbest==ng) exit !all rotations: cannot do better
             enddo
             ngen=ngenb; gen(:,:,1:ngen)=genb(:,:,1:ngen); agen(:,1:ngen)=agenb(:,1:ngen)
           endblock PairStart
           nggen=ngbest
           gloc(:,:,1:nggen)=gbest(:,:,1:nggen); agloc(:,1:nggen)=agbest(:,1:nggen)
           if(iprint()>0) write(stdo,ftox)' gensym: a closed group of',nggen,'operations with distinct rotations (of',ng,'rotations)'
         else
         icount=0
         ngmax2=0
         do ! a set of generators (gen,agen) to maximize number of spc operations
            icount=icount+1
            imax = 0
            ngmax = 0
            do  isop = 1, ng!   ... Run through all symops, choosing whichever adds the most ops
               gen(:,:,ngen+1)= g(:,:,isop) 
               agen(:,ngen+1) = ag(:,isop)  
               call sgroup(gen,agen,ngen+1, gloc,agloc,ngloc,ngmx,qlat)
               if (ngloc > ngmax) then
                  imax = isop
                  ngmax = ngloc
                  nggen = ngloc
               endif
            enddo
            if(ngmax>ngmax2) then
               ngmax2=ngmax
            else
               exit
            endif
            ngen = ngen+1
            gen(:,:,ngen)= g(:,:,imax) 
            agen(: ,ngen)= ag(: ,imax) 
            if(iprint()>0) write(stdo,ftox)'   Enlarging ngen=',ngen,' ng nggen=',ng,nggen
         enddo
         endif FaithfulSubgroup
         call poppr
         if(iprint()>0.and. ngen0 == 0) then
            write(stdo,ftox)' groupg: the following are sufficient to generate the space group:'
         elseif(iprint()>0) then
            write(stdo,ftox)' groupg:',ngen-ngen0,'generator(s) were added to complete the group:'
         endif
         sout = ''
         sout2 = ''
         do isop = 1, ngen
            call asymop(gen(1,1,isop),agen(1,isop),':',sg) !cartesian
            sout=trim(sout)//' '//trim(sg)
            call asymop(gen(1,1,isop),matmul(agen(1:3,isop),qlat(:,:)),'::',sg1) !fractional
            sout2=trim(sout2)//' '//trim(sg1) 
         enddo
         if (ngen > ngen0 .AND. iprint() >= 20) then
            write(stdo,"('  Generators:  trans(cart)= ', a)")trim(adjustl(sout)) 
            write(stdo,"('  Generators:: trans(frac)= ', a)")trim(adjustl(sout2))
         endif
         nwgens = sout2
         if(iprint()>0.and.nggen>ng) write(stdo,ftox)' (warning) Enlarged ng=',nggen,' > lattice ng=',ng
         ng =nggen
         g(:,:,1:ng)= gloc(:,:,1:ng)
         ag(:,1:ng) = agloc(:,1:ng)
       endblock groupgblock
       call symtbl(0,nbas,bas,g,ag,ng,qlat,istab )
    else
       call symtbl(0,nbas,bas,g,ag,ng,qlat,istab )
       nggen = ng
    endif
    if(iprint()>0) then
       write(stdo,"(' gensym: ig group ops (:vector means translation in cartesian)')")
       do  ig = 1, ng
          call asymop(g(:,:,ig),ag(1,ig),':',sg)
          write(stdo,'(i5,2x,a)') ig,trim(sg)
       enddo
       write(stdo,"(a)")' gensym: site permutation table for group operations ...'
       write(stdo,"('  ib/ig:',48i3)")  [(ig,ig=1,ng)]
       do i = 1, nbas
          write(stdo,"(i7,':',48i3)") i,(istab(i,ig), ig=1,ng)
       enddo
    endif
  end subroutine gensym
  subroutine sgroup(gen,agen,ngen, g,ag,ng, ngmx,qb, overflow)  !Get space group ops for given generators (gen,agen,ngen)
    ! overflow (optional): set .true. and return, instead of stopping, when the group exceeds ngmx (2026-10-02, gensym faithful)
    !i Inputs
    !i   gen   :rotation part of generators of the group
    !i   agen  :translation part of space group generator
    !i   ngen  :number of generators
    !i   ngmx  :maximum allowed number of group operations
    !i   qb    :vectors of a microcell in the Brillouin zone
    !o Outputs
    !o   g     :point group operations
    !o   ag    :translation part of space group
    !o   ng    :number of group operations
    !r Remarks
    !r   Operations are defined as (g,a)(v):=g*v+a where g is a (3x3) matrix, a is a vector.
    !r   Always returns the identity operation as one group operation
    implicit none
    integer:: ngen,ng,ngmx
    integer:: ipr,igen,ig,itry,iord,nnow,j,ip,i,k,n2,m1,m2,is,nnew,n,m
    real(8):: gen(3,3,ngen),g(3,3,ngmx),qb(3,3),agen(3,ngen),ag(3,ngmx),h(3,3),hh(3,3),sig(3,3),asig(3),ah(3),ahh(3)
    character:: sout*80,sg*35
    real(8),parameter:: e(9)=[1d0,0d0,0d0, 0d0,1d0,0d0, 0d0,0d0,1d0],ae(3)=0d0
    character(8):: xt,xn
    logical,optional,intent(out):: overflow
    call getpr(ipr)
    sout = ' '
    ag=0d0
    g(:,:,1)=reshape(e,[3,3])
    if(present(overflow)) overflow=.false.
    ng = 1
    igenloop: do 80 igen=1, ngen
!       if(master_mpi) write(stdo,ftox)'Generator: ',igen,ftof(reshape(gen(:,:,igen),shape=[9]),3),'  ',ftof(agen(:,igen),3)
       call spgcop(gen(:,:,igen),agen(:,igen),sig,asig)
       do ig = 1, ng ! --- Extend the group by all products with sig ----
          if (spgeql(g(:,:,ig),ag(:,ig),sig,asig,qb)) then
             if (ipr > 30) write(stdo,ftox)' Generator ',igen,' already in group as element ',ig
             cycle
          endif
       enddo
       call spgcop(sig,asig,h,ah) !Determine order (= power of sig that restores unit operation)
       do  itry = 1, 100
          iord = itry
          if (spgeql(h,ah,e,ae,qb)) exit
          call spgprd(sig,asig,h,ah,h,ah)
       enddo
       nnow = ng
       do     j = 1, ng
          call spgcop(g(:,:,j),ag(:,j),h,ah)
          do ip = 1, iord-1
             call spgprd(sig,asig,h,ah,h,ah)
             do  i = 1, ng
                call spgprd(g(:,:,i),ag(:,i),h,ah,hh,ahh) ! ... Products of type  g1 sig**p g2
                if(any([(spgeql(g(:,:,k),ag(:,k),hh,ahh,qb),k=1,nnow)])) cycle
                nnow = nnow+1
                if (nnow > ngmx) goto 99
                call spgcop(hh,ahh,g(:,:,nnow),ag(:,nnow))
             enddo
          enddo
          if (j == 1) n2 = nnow
       enddo
       m1 = ng+1
       m2 = nnow
       do      is = 2, 50
          nnew = 0
          do    n = ng+1,n2
             do m = m1, m2
                call spgprd(g(:,:,n),ag(:,n),g(:,:,m),ag(:,m),h,ah) ! ... Products with more than one sandwiched sigma-factor
                if(any([(spgeql(g(:,:,k),ag(:,k),h,ah,qb),k=1,nnow)])) cycle
                nnew = nnew+1
                nnow = nnow+1
                if (nnow > ngmx) goto 99
                call spgcop(h,ah,g(:,:,nnow),ag(:,nnow))
             enddo
          enddo
          m1 = m2+1
          m2 = nnow
          if (nnew == 0) exit
       enddo
       ng = nnow
80  enddo igenloop
    if(ipr >= 30) then
       if (sout /= ' ' .AND. ipr >= 60) write(stdo,ftox)' Order of generator'//trim(sout)
       write(stdo,ftox)' sgroup: ',ng,'symmetry operations from',ngen,'generators'
       if (ipr >= 60 .AND. ng > 1) then
          write(stdo,'('' sgroup: ig op'')')
          do  ig = 1, ng
             call asymop(g(1,1,ig),ag(1,ig),':',sg)
!             write(6,*)' g=',g(:,1,ig)
!             write(6,*)'   ',g(:,2,ig)
!             write(6,*)'   ',g(:,3,ig)
!             write(6,*)'ag=',ag(:,ig)
             write(stdo,'(5x,i4,2x,a)') ig,sg
          enddo
       endif
!       stop 'qqqqqqqqqqqqqqq'
    endif
    return
99  continue
    if(present(overflow)) then
       overflow=.true.
       return
    endif
    call rx('SGROUP: ng='//trim(xn(ng))//' > '//trim(xn(ngmx))//' probably bad translation')
  end subroutine sgroup
  subroutine psymop(tin,plat, g,ag,ng) !- Get symmetry group operations(g,ag,ng) from symbolic representation t
    !i Inputs:
    !i   t     string of symmetry operations, separated by spaces
    !i   plat  lattice vectors that scale translation part ag  (if needed, i.e. if translation specified by '::')
    !o Outputs:
    !o   g,ng  group op (3x3 matrix) for each input, and number
    !r Remarks:
    !r   Symbols have two parts, first the point group part, followed by an optional translation.  The point group part has the form
    !r   O(nx,ny,nz) where O is one of M, I or Rj for mirror, inversion and j-fold rotations, respectively, and nx,ny,nz are a triplet
    !r   of indices specifying the axis of operation.   (nx,ny,nz) is one of (1,0,0), (0,1,0), (0,0,1) and (1,1,1),
    !r   it can be abbreviated as x,X, y,Y, z,Z and d,D, respectively.  Also permissible are products, eg I*R4X.
    !r   The translation is also of the form (n1,n2,n3) :
    !r  CAUTION!: 2023: we do not allowe math operations in parenthesis. Give numerical number 6digits (if you like to recover, touch ctrl2ctrltoml.py)
    implicit none
    character(*):: tin
    real(8) :: plat(3,3),g(3,3,*),h(3,3),hh(3,3),ag(3,*),vec(3)
    integer :: nt,ng,i
    logical :: flgp
    character*1:: leftp='('
    character(256):: t
    t=tin
    nt = len(t)
    ng = 0
    i = 0
    do ! Do until no more symbolic representation, do ---
       call skipbl(t,nt,i)
       i=i+1 !  write(6,*)'  psymop:start###'//trim(t(i:)),' i=',i
       if (i >= nt) return
       ng = ng+1
       call parsop(t,i,g(1,1,ng)) !  write(6,*)'  Endof parsop1 i=',i,trim(t(i:))
       if (t(i:i) == '*') then
          i = i+1
          call parsop(t,i,h)
          g(:,:,ng)=matmul(g(1:3,1:3,ng),h) 
       endif
       ag(:,ng)=0d0 
       flgp = .false. 
       if (t(i:i+1) == '::') then !translation by fractional 
          flgp = .true.
          i=i+2
       elseif (t(i:i) == ':') then !translation cartesian 
          i=i+1
       endif
       if (t(i:i) == leftp) then
          if( .NOT. parsvc(t,i,ag(1:3,ng))) call rxi('psymop: failed to parse translation ig=',ng)
          if(flgp) ag(:,ng) = matmul(plat(:,:),ag(1:3,ng)) 
       endif
    enddo
  end subroutine psymop
  subroutine parsop(t,i,a)    !- Parse string for a point group operator
    real(8) :: v(3),sp,c,s,pi2,a(3,3),ddot
    character(*) :: t
    character(8):: xn
    real(8),parameter:: e(9)=[1d0,0d0,0d0, 0d0,1d0,0d0, 0d0,0d0,1d0]
    integer :: i,j,k,nrot,iii !    write(*,*)"parsopinput=@@@"//trim(t)//"@@@",i
    pi2 = 8*datan(1d0)
!    print *,'parsop=',t(i:i)
    if (t(i:i) == 'r' .OR. t(i:i) == 'R') then !rotation
       i = i+1
       read(t(i:i),'(i1)',err=99) nrot
       i = i+1
       if( .NOT. parsvc(t,i,v)) goto 99
       v(1:3) = v(1:3)/sum(v**2)**.5
       c = dcos(pi2/nrot)
       s = dsin(pi2/nrot)
       do  k = 1, 3
          a(k,1:3) = (1-c)*v(1:3)*v(k)
          a(k,k) = a(k,k) + c
       enddo
       a(2,1) = a(2,1) + s*v(3)
       a(1,3) = a(1,3) + s*v(2)
       a(3,2) = a(3,2) + s*v(1)
       a(1,2) = a(1,2) - s*v(3)
       a(3,1) = a(3,1) - s*v(2)
       a(2,3) = a(2,3) - s*v(1)
    elseif (t(i:i) == 'm' .OR. t(i:i) == 'M') then !mirror
       i = i+1
       if( .NOT. parsvc(t,i,v)) goto 99
       sp = sum(v**2)
       do  j = 1, 3
          a(j,:) = -2d0*v(:)*v(j)/sp
          a(j,j) = a(j,j) + 1d0
       enddo
    elseif (t(i:i) == 'i' .OR. t(i:i) == 'I') then !inversion
       i = i+1
       a=-reshape(e,[3,3])
    elseif (t(i:i) == 'e' .OR. t(i:i) == 'E') then !identity
       i = i+1
       a= reshape(e,[3,3])
    else
       goto 99
    endif
    return
99  continue
    call rx('PARSOP: parse error at '//trim(xn(i))//' t(i:)='//trim(t(i:)))
  end subroutine parsop
  logical function parsvc(t,ip,v)  !Converting ascii t to vector v.  We handle only v=(num,num,num),d,x,y,z, where num is wo math operations.
    !io  ip     position in t first char.  out: position ofr last char
    !i  t       string representation of vector (see Remarks)
    !o  v       vector
    !o  parsvc  T if parse was successful; F if not.
    !r  The following shorthand notations are allowed: 'D'(1,1,1), 'X', 'Y', 'Z' for (1,0,0), (0,1,0), (0,0,1).
    !note: 2023 we removed math operation. If you need to recover, touch ctrl2ctrltoml.py.
    implicit none
    integer :: itrm,ix(3),ich,iopt,m,i,iz,id,mx,ip,mmm
    real(8) :: v(3)
    character(*) :: t
    character(1):: rkey
    v=0d0
    rkey=''
    if(len_trim(t)>=ip) rkey=t(ip:ip)  !I think this is ok(but not yet detailed check). 2024-7-26
    parsvc = .false.
    if(scan(t(ip:ip),'(XxYyZzDd')==0) return !if no translation
    if (rkey=='(') then ! we expect t(ip:)='(..., ..., ...)
       ip = ip+1
       mmm=index(t(ip:),')')
       if(mmm<=0) write(6,*)'ip=',ip,'###',trim(t),'###','rkey###',rkey,'###'
       if(mmm<=0) call rx('cannot find right parensis for vector ###'//trim(t(ip:))//'###')
       if(verify(t(ip:ip+mmm-2),'0123456789.Dde-, ')>0) call rx('trans.part of symops should be numerical w/o math operations'&
            //trim(t(ip:ip+mmm-2)))
       read(t(ip:ip+mmm-2),*) v 
       ip=ip+mmm-2+2
    else
       if(rkey=='d' .or. rkey=='D') v = [1d0,1d0,1d0]
       if(rkey=='x' .or. rkey=='X') v = [1d0,0d0,0d0]
       if(rkey=='y' .or. rkey=='Y') v = [0d0,1d0,0d0]
       if(rkey=='z' .or. rkey=='Z') v = [0d0,0d0,1d0]
       ip = ip+1 
    endif
    parsvc = .true.
  end function parsvc
  subroutine skipbl(t,nt,i)  !- Parses string for first nonblank character
    !     implicit none
    integer :: nt,i
    character(1) :: t(0:nt)
    if (i >= nt) return
99  if (t(i) /= ' ') return
    i = i+1
    if (i >= nt) return
    goto 99
  end subroutine skipbl
  subroutine symlat(platcp,ngrp,grp,isym)  !- Generates the point symmetry operations of the lattice
    !i Inputs:
    !i   platcp:lattice vectors of most compact primitive unit cell
    !o Outputs:
    !o   ngrp  :number of allowed symmetry operations
    !o   grp   :symmetry operation matrix
    !o   isym  :index to lattice type, calculated from ngrp:
    !o          ngrp   isym    name
    !o                  0     shouldn't happen
    !o            2     1     triclinic
    !o            4     2     monoclinic
    !o            8     3     orthorhombic
    !o           16     4     tetragonal
    !o           12     5     rhombohedral
    !o           24     6     hexagonal
    !o           48     7     cubic
    !r Remarks:
    !r   symlat analyzes the primitive translations of the bravais lattice in order to supply the symmetry operations of the lattice.
    !r   It gives the number ngrp of allowed operations as well as these operations themselves.
    implicit none
    integer :: ngrp,isym
    real(8) :: platcp(3,3),grp(9,*)
    integer :: i,iprint,ltmax,ll1,m,m1,m2,m3,mm
    parameter(ltmax=3,ll1=ltmax*2+1)
    real(8) :: platt(3,3),qlatcp(3,3),mat(3,3),vecg(3),vol
    logical :: lirr
    character(12),parameter:: csym1(0:7)=[character(12):: &
         'indefinite','triclinic','monoclinic','orthorhombic','tetragonal','rhombohedral','hexagonal','cubic']
    integer,parameter:: nrot(4)=[2,3,4,6],ngtab(7)=[2,4,8,16,12,24,48]
    mm(i,m) = ltmax-(mod(i,ll1**m)-mod(i,ll1**(m-1)))/ll1**(m-1)
    call dinv33(platcp,1,qlatcp,vol)
    ngrp = 2 ! --- Start out with E and I ---
    call csymop(grp(1,1),.false.,1,[0d0,0d0,0d0])
    call csymop(grp(1,2), .true.,1,[0d0,0d0,0d0])
    do  10  i = 0, (ll1**3-1)/2-1 !Find all possible rotation axes ---
       m1 = mm(i,1); m2 = mm(i,2); m3 = mm(i,3)
       if( all([((mod(m1,m)/=0.or.mod(m2,m)/=0.or.mod(m3,m)/=0),m=2,ll1)]) ) then
          vecg(:) = matmul(platcp,[m1,m2,m3]) 
          do  16  m = 1, 4 
             call csymop(mat,.false.,nrot(m),vecg) ! Matrix for this symmetry operation
             platt=matmul(mat,platcp)
             if (latvec(3,toll,qlatcp,platt)) then !       ... Add it and i*symop, if allowed
                call csymop(grp(1,ngrp+1),.false.,nrot(m),vecg)
                call csymop(grp(1,ngrp+2),.true. ,nrot(m),vecg)
                ngrp = ngrp+2
                if (m /= 1) then
                   call csymop(grp(1,ngrp+1),.false.,-nrot(m),vecg)
                   call csymop(grp(1,ngrp+2),.true. ,-nrot(m),vecg)
                   ngrp = ngrp+2
                endif
             endif
16        enddo
       endif
10  enddo
    isym = findloc(ngtab,value=ngrp,dim=1)
    if(iprint()>=30) write(stdo,ftox)' symlat: Bravais system is '//csym1(isym)//' with',ngrp,'symmetry operations.'
  end subroutine symlat
  subroutine csymop(grp,li,nrot,vecg) !Convert (nrot,vecg,li) to grp
    ! i li    :if T: inversion or rotoinversion
    ! i nrot  :rotation angle = 2*pi/nrot
    ! i vecg  :rotation axis
    ! o grp   :group operation matrix
    !r Remarks
    !r   for nrot > 2 the matrix is non-symmetric and the rotation axis can be calculated from the antisymmetric part.
    !r   For nrot = 2 this not possible.  However, the squared vector components are given by:  mat(i,i) = 2 v_i * v_i - 1.
    !r   This is used for the largest component. The others are taken from: mat(i,j) = 2 v_i * v_j for i ne j.  This way we also
    !r   get the right phases between the components.
    implicit none
    integer :: nrot,iopt, i,idamax,j,in
    real(8) :: vecg(3),grp(3,3), costbn,detop,ddet33,dnrm2,sinpb3,vfac, wk(9),sintbn,omcos,ddot
    logical :: li
    character(8):: xt
    real(8),parameter:: twopi = 8*datan(1d0)
    in = iabs(nrot)
    if(in <= 0 .OR. in == 5 .OR. in > 6)call rx('CSYMOP: abs(nrot) must 1,2,3,4 or 6, but is '//trim(xt(in)))
    if(in == 1) then
       grp=reshape([1d0,0d0,0d0,0d0,1d0,0d0,0d0,0d0,1d0],[3,3])
    else
       call rxx(dnrm2(3,vecg,1).lt.tiny, 'CSYMOP: zero rotation vector')
       sintbn = sin(twopi/nrot)
       costbn = cos(twopi/nrot)
       omcos  = 1d0-costbn
       vecg= 1d0/sum(vecg**2)**.5 *vecg 
       grp(1,1:3) = omcos*vecg(1)*vecg(:) + [costbn,         -sintbn*vecg(3),  sintbn*vecg(2)]
       grp(2,1:3) = omcos*vecg(2)*vecg(:) + [sintbn*vecg(3),          costbn, -sintbn*vecg(1)]
       grp(3,1:3) = omcos*vecg(3)*vecg(:) + [-sintbn*vecg(2), sintbn*vecg(1),  costbn]
    endif
    if(li) grp=-grp 
  end subroutine csymop
  subroutine symcry(bas,ipc,nbas,nclass,nrclas, ng,plat,qlat,g,ag,istab) ! Generates the symmetry ops of the crystal from those of the lattice
    !i Inputs:
    !i   tol:   tol for which atoms are considered to be at the same site
    !i          use 0 for symtbl to pick internal default
    !i   bas   :basis vectors (scaled by alat)
    !i   ipc   :the jth atom belongs to class ipc(j)
    !i   nbas  :number of atoms in the basis
    !i   nclass:number of classes, atoms in same class are symmetry-related
    !i   nrclas:number of atoms in the ith class
    !i   plat  :primitive lattice vectors (scaled by alat)
    !i   qlat  :primitive translation vectors in reciprocal space
    ! io Inputs/Outputs:
    ! io  ng    :number of allowed symmetry operations (see Remarks)
    ! io         on input  number of symmetry operations of the lattice
    ! io         on output number of symmetry operations of the crystal
    ! io  g     :symmetry operation matrices
    !o Outputs:
    !o   ag    :symmetry operation vector
    !o   istab :site ib is transformed into istab(ib,ig) by operation ig
    !r Remarks:
    !r   symcry finds the subset of the allowed ng point operations of the
    !r   lattice without a basis (see symlat.f) that are valid for
    !r   the crystal.
    !r
    !r   This routine is based on ATFTMT written by Worlton and Warren,  CPC 3, 88 (1972).
    ! ----------------------------------------------------------------------
    implicit none
    integer :: nbas,ng,ipc(nbas),nclass,istab(nbas,ng),nrclas(nclass)
    real(8) :: plat(3,3),qlat(3,3),bas(3,nbas),bast(3,nbas), g(3,3,*),ag(3,*)
    integer :: ibas,ic,icmin,ig,ipr,jbas,kbas,kc, m,mbas,nj,nm,ng0
    real(8) :: dbas(3)
    character(135):: sg
    real(8):: rfrac(3)
    call getpr(ipr)
    icmin = 1
    do ic = 1, nclass !Find the class with minimum number of atoms ---
       if(nrclas(ic) < nrclas(icmin) .AND. nrclas(ic) > 0) icmin = ic
    enddo
    ibas = iclbsjx(ipc,nbas, icmin,1)
    ! --- For each group op, see whether it only shifts basis by some T ---
    ng0 = ng
    ng = 0
    do  30  ig = 1, ng0 !  write(stdo,ftox)'check initial generator ig=',ig
       bast= matmul(g(:,:,ig),bas)!   ... Rotate the basis by g
       do  20  nj = 1, nrclas(icmin)
          jbas = iclbsjx(ipc,nbas, icmin,nj)
          ag(:,ng+1) = bas(:,jbas)-bast(:,ibas) ! This is a candidate for translation ag
          rfrac = matmul(ag(:,ng+1)-epsr,qlat)
          ag(:,ng+1) = matmul(plat,rfrac -nint(rfrac)+epsr)
          do  10  kbas = 1, nbas
             kc      = ipc(kbas)
             do  nm  = 1, nrclas(kc)
                mbas = iclbsjx(ipc,nbas, kc,nm)
                dbas = bas(:,mbas)-bast(:,kbas)-ag(:,ng+1)
                if (latvec(1,toll,qlat,dbas)) then
                   istab(kbas,ng+1) = mbas
                   goto 10
                endif
             enddo
             call asymop(g(:,:,ig),ag(1,ng+1),' ',sg) !write(stdo,ftox)' symcry: excluded candidate ig=',ig,' op=',trim(sg) !Candidate not valid
             goto 20
10        enddo
          ng = ng+1 !  --- Valid ag found; add g to list ---
          if (ig > ng) g(:,:,ng)=g(:,:,ig) 
          exit
20     enddo
30  enddo
    if(ipr>=30)write(stdo,ftox)' symcry: crystal invariant under',ng,'following symmetry operations for tol=',ftof(toll)
!    if (ipr >= 60 .AND. ng > 1) then
!       write(stdo,'('' -- ig group op: symcry'')')
!       do  ig = 1, ng
!          call asymop(g(:,:,ig),ag(1,ig),' ',sg)
!          write(stdo,'(i5,2x,a)') ig,trim(sg)
!       enddo
!    endif
  end subroutine symcry
  subroutine puretrans(nbas,bas,ips,qlat,plat,ntau,tau) !Pure translations of the crystal that are not lattice vectors (2026-10-02)
    ! tau(:,1:ntau), Cartesian (alat units): bas(:,j)-bas(:,1) for the sites j of the species of site 1 such that every site moved by
    ! it lands on a site of the same species (mod lattice). Lattice vectors are not counted.
    implicit none
    integer,intent(in):: nbas,ips(nbas)
    real(8),intent(in):: bas(3,nbas),qlat(3,3),plat(3,3)
    integer,intent(out):: ntau
    real(8),intent(out):: tau(3,nbas)
    integer:: j,i,k
    real(8):: v(3),d(3)
    logical:: ok,found
    ntau=0
    do j = 2, nbas
       if(ips(j)/=ips(1)) cycle
       v = bas(:,j)-bas(:,1)
       d = matmul(v,qlat); if(sum(abs(d-nint(d)))<toll) cycle !a lattice vector
       ok=.true.
       do i = 1, nbas
          found=.false.
          do k = 1, nbas
             if(ips(k)/=ips(i)) cycle
             d = matmul(bas(:,i)+v-bas(:,k),qlat)
             if(sum(abs(d-nint(d)))<toll) then; found=.true.; exit; endif
          enddo
          if(.not.found) then; ok=.false.; exit; endif
       enddo
       if(.not.ok) cycle
       do k = 1, ntau !already counted (mod lattice)?
          d = matmul(v-tau(:,k),qlat); if(sum(abs(d-nint(d)))<toll) then; ok=.false.; exit; endif
       enddo
       if(ok) then; ntau=ntau+1; tau(:,ntau)=v; endif
    enddo
  end subroutine puretrans
  logical function distinctrot(g,ng) !No two operations with the same rotation (2026-10-02)
    implicit none
    integer,intent(in):: ng
    real(8),intent(in):: g(3,3,ng)
    integer:: i,j
    distinctrot=.true.
    do i = 1, ng
       do j = i+1, ng
          if(all(abs(g(:,:,i)-g(:,:,j))<toll)) then; distinctrot=.false.; return; endif
       enddo
    enddo
  end function distinctrot
end module m_symfind
