!> The space group of the crystal. (1) symgrp = "find" (the default): spglib (symfind_spglib, the vendored C library), the
!> operations written to and read from symmetry.<sname>.json (symfind_json, write_symjson). (2) symgrp with generators (to lower
!> the symmetry on purpose, e.g. "r4z mz"): the group they generate (gensym). gens_in_group checks generators written together with
!> "find" (the old mixed form) or in symgrpaf against the group of spglib.
!> 2026-10-02 21:31: the old search of the symmetry (symlat, symcry, the choice of generators, the faithful subgroup of a supercell) was removed
!> (user: "古い探し方を全部外す"; the input forms are still accepted). It is in the git history before this date (MD/symmetry_spglib.md).
module m_symfind
  use m_lgunit,only:stdo
  use m_ftox
  use m_nvfortran,only: findloc
  use m_mpi,only: master_mpi
  use m_symop_util,only: spgcop,spgprd,spgeql,grpeql,latvec,asymop
  use m_symderive,only: symtbl,iclbsjx
  public gensym,gens_in_group,symfind_json,symfind_spglib,write_symjson,ngmx,ngnmx
  private
  real(8),parameter:: toll=1d-4,tiny=1d-4,epsr=1d-12
  integer,parameter:: ngnmx=10
  integer,parameter:: ngmx = 48
contains
  subroutine gensym(gens,nbas,plat,bas, ng,g,ag,istab,ngmxs) !The space group generated by the generators gens (symgrp without "find")
    !i gens : generators in symbolic form (psymop), e.g. "r4z mz", "r4z:(0,0,0.5)"; blank or "e" gives the identity only
    !o ng,g,ag : the group they generate (closed by sgroup); istab(ib,ig): site ib goes to istab(ib,ig) by operation ig
    implicit none
    character(*),intent(in):: gens
    integer,intent(in):: nbas,ngmxs
    real(8),intent(in):: plat(3,3),bas(3,nbas)
    integer:: ng,istab(nbas,*),ngen,igen,ig,ib
    real(8):: g(3,3,*),ag(3,*),qlat(3,3),vol,gen(3,3,ngnmx),agen(3,ngnmx)
    character(100):: sg
    character(8):: xn
    call dinv33(plat,1,qlat,vol)
    ngen = 0
    if(len_trim(gens) > 0) call psymop(trim(gens),plat,gen,agen,ngen)
    do igen = 1, ngen
       if(.NOT.latvec(3,toll,qlat,matmul(gen(:,:,igen),plat))) &
            call rx('gensym: the generator '//trim(xn(igen))//' of "'//trim(gens)//'" is not compatible with the lattice')
    enddo
    call sgroup(gen,agen,ngen, g,ag,ng, min(ngmx,ngmxs),qlat)
    call symtbl(0,nbas,bas,g,ag,ng,qlat,istab ) !also checks that each operation leaves the crystal invariant
    if(master_mpi) then
       write(stdo,"(' gensym: ',i0,' operations generated by symgrp = ""',a,'""')") ng,trim(gens)
       do ig = 1, ng
          call asymop(g(:,:,ig),ag(1,ig),':',sg)
          write(stdo,'(i5,2x,a)') ig,trim(sg)
       enddo
       write(stdo,"(a)")' gensym: site permutation table for group operations ...'
       write(stdo,"('  ib/ig:',48i3)")  [(ig,ig=1,ng)]
       do ib = 1, nbas
          write(stdo,"(i7,':',48i3)") ib,(istab(ib,ig), ig=1,ng)
       enddo
    endif
  end subroutine gensym
  subroutine gens_in_group(gens,plat,ng,g,ag,trev,want_trev,ok,why) !Are the generators gens operations of the group (g,ag)?
    ! Used for generators written with "find" (symgrp = "R4Z*I MX*I R3D find", the old mixed form) and in symgrpaf (want_trev:
    ! among the operations with time reversal, the AF ones). A generator matches an operation of the same rotation whose
    ! translation differs by a lattice vector. (2026-10-02 21:31)
    implicit none
    character(*),intent(in):: gens
    integer,intent(in):: ng
    real(8),intent(in):: plat(3,3),g(3,3,ng),ag(3,ng)
    logical,intent(in):: trev(ng),want_trev
    logical,intent(out):: ok
    character(*),intent(out):: why
    integer:: ngen,igen,ig
    real(8):: qlat(3,3),vol,gen(3,3,ngnmx),agen(3,ngnmx)
    logical:: found
    character(100):: sg
    call dinv33(plat,1,qlat,vol)
    ok = .true.; why = ' '
    ngen = 0
    call psymop(trim(gens),plat,gen,agen,ngen)
    do igen = 1, ngen
       found = .false.
       do ig = 1, ng
          if(trev(ig) .neqv. want_trev) cycle
          if(maxval(abs(g(:,:,ig)-gen(:,:,igen))) > toll) cycle
          if(latvec(1,toll,qlat,ag(:,ig)-agen(:,igen))) then; found = .true.; exit; endif
       enddo
       if(.not.found) then
          call asymop(gen(:,:,igen),agen(:,igen),':',sg)
          ok = .false.
          if(want_trev) then
             why = 'the generator '//trim(sg)//' is not an AF operation (with the spin flip) of the group found by spglib'
          else
             why = 'the generator '//trim(sg)//' is not an operation of the group found by spglib'
          endif
          return
       endif
    enddo
  end subroutine gens_in_group
  subroutine sgroup(gen,agen,ngen, g,ag,ng, ngmx,qb, overflow)  !Get space group ops for given generators (gen,agen,ngen)
    ! overflow (optional): set .true. and return, instead of stopping, when the group exceeds ngmx (2026-10-02, gensym faithful)
    !i Inputs
    !i   gen   :rotation part of generators of the group
    !i   agen  :translation part of space group generator
    !i   ngen  :number of generators
    !i   ngmx  :maximum allowed number of group operations
    !i   qb    :vectors of a microcell in the Brillouin zone
    !o Outputs
    !o   g     :point group operations
    !o   ag    :translation part of space group
    !o   ng    :number of group operations
    !r Remarks
    !r   Operations are defined as (g,a)(v):=g*v+a where g is a (3x3) matrix, a is a vector.
    !r   Always returns the identity operation as one group operation
    implicit none
    integer:: ngen,ng,ngmx
    integer:: ipr,igen,ig,itry,iord,nnow,j,ip,i,k,n2,m1,m2,is,nnew,n,m
    real(8):: gen(3,3,ngen),g(3,3,ngmx),qb(3,3),agen(3,ngen),ag(3,ngmx),h(3,3),hh(3,3),sig(3,3),asig(3),ah(3),ahh(3)
    character:: sout*80,sg*35
    real(8),parameter:: e(9)=[1d0,0d0,0d0, 0d0,1d0,0d0, 0d0,0d0,1d0],ae(3)=0d0
    character(8):: xt,xn
    logical,optional,intent(out):: overflow
    call getpr(ipr)
    sout = ' '
    ag=0d0
    g(:,:,1)=reshape(e,[3,3])
    if(present(overflow)) overflow=.false.
    ng = 1
    igenloop: do 80 igen=1, ngen
!       if(master_mpi) write(stdo,ftox)'Generator: ',igen,ftof(reshape(gen(:,:,igen),shape=[9]),3),'  ',ftof(agen(:,igen),3)
       call spgcop(gen(:,:,igen),agen(:,igen),sig,asig)
       do ig = 1, ng ! --- Extend the group by all products with sig ----
          if (spgeql(g(:,:,ig),ag(:,ig),sig,asig,qb)) then
             if (ipr > 30) write(stdo,ftox)' Generator ',igen,' already in group as element ',ig
             cycle
          endif
       enddo
       call spgcop(sig,asig,h,ah) !Determine order (= power of sig that restores unit operation)
       do  itry = 1, 100
          iord = itry
          if (spgeql(h,ah,e,ae,qb)) exit
          call spgprd(sig,asig,h,ah,h,ah)
       enddo
       nnow = ng
       do     j = 1, ng
          call spgcop(g(:,:,j),ag(:,j),h,ah)
          do ip = 1, iord-1
             call spgprd(sig,asig,h,ah,h,ah)
             do  i = 1, ng
                call spgprd(g(:,:,i),ag(:,i),h,ah,hh,ahh) ! ... Products of type  g1 sig**p g2
                if(any([(spgeql(g(:,:,k),ag(:,k),hh,ahh,qb),k=1,nnow)])) cycle
                nnow = nnow+1
                if (nnow > ngmx) goto 99
                call spgcop(hh,ahh,g(:,:,nnow),ag(:,nnow))
             enddo
          enddo
          if (j == 1) n2 = nnow
       enddo
       m1 = ng+1
       m2 = nnow
       do      is = 2, 50
          nnew = 0
          do    n = ng+1,n2
             do m = m1, m2
                call spgprd(g(:,:,n),ag(:,n),g(:,:,m),ag(:,m),h,ah) ! ... Products with more than one sandwiched sigma-factor
                if(any([(spgeql(g(:,:,k),ag(:,k),h,ah,qb),k=1,nnow)])) cycle
                nnew = nnew+1
                nnow = nnow+1
                if (nnow > ngmx) goto 99
                call spgcop(h,ah,g(:,:,nnow),ag(:,nnow))
             enddo
          enddo
          m1 = m2+1
          m2 = nnow
          if (nnew == 0) exit
       enddo
       ng = nnow
80  enddo igenloop
    if(ipr >= 30) then
       if (sout /= ' ' .AND. ipr >= 60) write(stdo,ftox)' Order of generator'//trim(sout)
       write(stdo,ftox)' sgroup: ',ng,'symmetry operations from',ngen,'generators'
       if (ipr >= 60 .AND. ng > 1) then
          write(stdo,'('' sgroup: ig op'')')
          do  ig = 1, ng
             call asymop(g(1,1,ig),ag(1,ig),':',sg)
!             write(6,*)' g=',g(:,1,ig)
!             write(6,*)'   ',g(:,2,ig)
!             write(6,*)'   ',g(:,3,ig)
!             write(6,*)'ag=',ag(:,ig)
             write(stdo,'(5x,i4,2x,a)') ig,sg
          enddo
       endif
!       stop 'qqqqqqqqqqqqqqq'
    endif
    return
99  continue
    if(present(overflow)) then
       overflow=.true.
       return
    endif
    call rx('SGROUP: ng='//trim(xn(ng))//' > '//trim(xn(ngmx))//' probably bad translation')
  end subroutine sgroup
  subroutine psymop(tin,plat, g,ag,ng) !- Get symmetry group operations(g,ag,ng) from symbolic representation t
    !i Inputs:
    !i   t     string of symmetry operations, separated by spaces
    !i   plat  lattice vectors that scale translation part ag  (if needed, i.e. if translation specified by '::')
    !o Outputs:
    !o   g,ng  group op (3x3 matrix) for each input, and number
    !r Remarks:
    !r   Symbols have two parts, first the point group part, followed by an optional translation.  The point group part has the form
    !r   O(nx,ny,nz) where O is one of M, I or Rj for mirror, inversion and j-fold rotations, respectively, and nx,ny,nz are a triplet
    !r   of indices specifying the axis of operation.   (nx,ny,nz) is one of (1,0,0), (0,1,0), (0,0,1) and (1,1,1),
    !r   it can be abbreviated as x,X, y,Y, z,Z and d,D, respectively.  Also permissible are products, eg I*R4X.
    !r   The translation is also of the form (n1,n2,n3) :
    !r  CAUTION!: 2023: we do not allowe math operations in parenthesis. Give numerical number 6digits (if you like to recover, touch ctrl2ctrltoml.py)
    implicit none
    character(*):: tin
    real(8) :: plat(3,3),g(3,3,*),h(3,3),hh(3,3),ag(3,*),vec(3)
    integer :: nt,ng,i
    logical :: flgp
    character*1:: leftp='('
    character(256):: t
    t=tin
    nt = len(t)
    ng = 0
    i = 0
    do ! Do until no more symbolic representation, do ---
       call skipbl(t,nt,i)
       i=i+1 !  write(6,*)'  psymop:start###'//trim(t(i:)),' i=',i
       if (i >= nt) return
       ng = ng+1
       call parsop(t,i,g(1,1,ng)) !  write(6,*)'  Endof parsop1 i=',i,trim(t(i:))
       if (t(i:i) == '*') then
          i = i+1
          call parsop(t,i,h)
          g(:,:,ng)=matmul(g(1:3,1:3,ng),h) 
       endif
       ag(:,ng)=0d0 
       flgp = .false. 
       if (t(i:i+1) == '::') then !translation by fractional 
          flgp = .true.
          i=i+2
       elseif (t(i:i) == ':') then !translation cartesian 
          i=i+1
       endif
       if (t(i:i) == leftp) then
          if( .NOT. parsvc(t,i,ag(1:3,ng))) call rxi('psymop: failed to parse translation ig=',ng)
          if(flgp) ag(:,ng) = matmul(plat(:,:),ag(1:3,ng)) 
       endif
    enddo
  end subroutine psymop
  subroutine parsop(t,i,a)    !- Parse string for a point group operator
    real(8) :: v(3),sp,c,s,pi2,a(3,3),ddot
    character(*) :: t
    character(8):: xn
    real(8),parameter:: e(9)=[1d0,0d0,0d0, 0d0,1d0,0d0, 0d0,0d0,1d0]
    integer :: i,j,k,nrot,iii !    write(*,*)"parsopinput=@@@"//trim(t)//"@@@",i
    pi2 = 8*datan(1d0)
!    print *,'parsop=',t(i:i)
    if (t(i:i) == 'r' .OR. t(i:i) == 'R') then !rotation
       i = i+1
       read(t(i:i),'(i1)',err=99) nrot
       i = i+1
       if( .NOT. parsvc(t,i,v)) goto 99
       v(1:3) = v(1:3)/sum(v**2)**.5
       c = dcos(pi2/nrot)
       s = dsin(pi2/nrot)
       do  k = 1, 3
          a(k,1:3) = (1-c)*v(1:3)*v(k)
          a(k,k) = a(k,k) + c
       enddo
       a(2,1) = a(2,1) + s*v(3)
       a(1,3) = a(1,3) + s*v(2)
       a(3,2) = a(3,2) + s*v(1)
       a(1,2) = a(1,2) - s*v(3)
       a(3,1) = a(3,1) - s*v(2)
       a(2,3) = a(2,3) - s*v(1)
    elseif (t(i:i) == 'm' .OR. t(i:i) == 'M') then !mirror
       i = i+1
       if( .NOT. parsvc(t,i,v)) goto 99
       sp = sum(v**2)
       do  j = 1, 3
          a(j,:) = -2d0*v(:)*v(j)/sp
          a(j,j) = a(j,j) + 1d0
       enddo
    elseif (t(i:i) == 'i' .OR. t(i:i) == 'I') then !inversion
       i = i+1
       a=-reshape(e,[3,3])
    elseif (t(i:i) == 'e' .OR. t(i:i) == 'E') then !identity
       i = i+1
       a= reshape(e,[3,3])
    else
       goto 99
    endif
    return
99  continue
    call rx('PARSOP: parse error at '//trim(xn(i))//' t(i:)='//trim(t(i:)))
  end subroutine parsop
  logical function parsvc(t,ip,v)  !Converting ascii t to vector v.  We handle only v=(num,num,num),d,x,y,z, where num is wo math operations.
    !io  ip     position in t first char.  out: position ofr last char
    !i  t       string representation of vector (see Remarks)
    !o  v       vector
    !o  parsvc  T if parse was successful; F if not.
    !r  The following shorthand notations are allowed: 'D'(1,1,1), 'X', 'Y', 'Z' for (1,0,0), (0,1,0), (0,0,1).
    !note: 2023 we removed math operation. If you need to recover, touch ctrl2ctrltoml.py.
    implicit none
    integer :: itrm,ix(3),ich,iopt,m,i,iz,id,mx,ip,mmm
    real(8) :: v(3)
    character(*) :: t
    character(1):: rkey
    v=0d0
    rkey=''
    if(len_trim(t)>=ip) rkey=t(ip:ip)  !I think this is ok(but not yet detailed check). 2024-7-26
    parsvc = .false.
    if(scan(t(ip:ip),'(XxYyZzDd')==0) return !if no translation
    if (rkey=='(') then ! we expect t(ip:)='(..., ..., ...)
       ip = ip+1
       mmm=index(t(ip:),')')
       if(mmm<=0) write(6,*)'ip=',ip,'###',trim(t),'###','rkey###',rkey,'###'
       if(mmm<=0) call rx('cannot find right parensis for vector ###'//trim(t(ip:))//'###')
       if(verify(t(ip:ip+mmm-2),'0123456789.Dde-, ')>0) call rx('trans.part of symops should be numerical w/o math operations'&
            //trim(t(ip:ip+mmm-2)))
       read(t(ip:ip+mmm-2),*) v 
       ip=ip+mmm-2+2
    else
       if(rkey=='d' .or. rkey=='D') v = [1d0,1d0,1d0]
       if(rkey=='x' .or. rkey=='X') v = [1d0,0d0,0d0]
       if(rkey=='y' .or. rkey=='Y') v = [0d0,1d0,0d0]
       if(rkey=='z' .or. rkey=='Z') v = [0d0,0d0,1d0]
       ip = ip+1 
    endif
    parsvc = .true.
  end function parsvc
  subroutine skipbl(t,nt,i)  !- Parses string for first nonblank character
    !     implicit none
    integer :: nt,i
    character(1) :: t(0:nt)
    if (i >= nt) return
99  if (t(i) /= ' ') return
    i = i+1
    if (i >= nt) return
    goto 99
  end subroutine skipbl
  subroutine symfind_json(fname,nbas,spid,afl,pos,plat,qlat,alat,ngmxj, ng,g,ag,trev,ok,why) !Space group read from symmetry.<sname>.json
    ! The file holds the operations x' = R x + t in the fractional coordinates of plat (R integer) and the structure they belong
    ! to; it is written by write_symjson (lmf, lmchk) or by symfind.py. The structure is compared with the one given here (the
    ! ctrlg): ok=.false. with the reason in why when it differs (the caller makes the operations again with spglib).
    ! Returns all operations: the Cartesian g = plat R plat^-1 and ag = plat t (alat units, r' = g r + ag), the identity first,
    ! then the rest of the group of the crystal, then (AF) those with time reversal, trev=.true., which exchange the up and down
    ! sites of the AF pairs (af = +k, -k). Pure translations (a supercell) are operations too. (2026-10-02 05:34 S3, 05:46 S4,
    ! 06:16 S5; 2026-10-02 08:27: a stale file is reported, not a stop, and trev is returned)
    use tjson_parser, only: json_load
    use tomlf, only: toml_table, toml_array, toml_value, toml_error, get_value, len
    use tomlf_type, only: cast_to_table
    implicit none
    character(*),intent(in):: fname
    integer,intent(in):: nbas,ngmxj,afl(nbas)   ! afl: the af label of each site (0, +k, -k)
    character(*),intent(in):: spid(nbas)      ! species name of each site
    real(8),intent(in):: pos(3,nbas),plat(3,3),qlat(3,3),alat ! pos Cartesian (alat); plat(:,i) the i-th lattice vector
    integer,intent(out):: ng
    real(8),intent(out):: g(3,3,ngmxj),ag(3,ngmxj)
    logical,intent(out):: trev(ngmxj),ok
    character(*),intent(out):: why
    class(toml_value),allocatable,target:: obj
    type(toml_error),allocatable:: err
    type(toml_table),pointer:: root,st,op
    type(toml_array),pointer:: arr,row,ops
    character(:),allocatable:: name
    integer:: i,j,ib,iop,nop,ival,rot(3,3)
    real(8):: alatj,platj(3,3),fracj(3),frac(3),d(3),tr(3),pinv(3,3)
    real(8),parameter:: tolst=1d-6
    ok=.false.; why=' '; ng=0
    call json_load(obj, fname, error=err)
    if(allocated(err)) then
       why='cannot read it: '//err%message; return
    endif
    root => cast_to_table(obj)
    if(.not.associated(root)) then
       why='not a JSON object'; return
    endif
    call get_value(root,'structure',st,requested=.false.)
    if(.not.associated(st)) then
       why='no structure in it'; return
    endif
    call get_value(st,'alat_bohr',alatj)
    call get_value(st,'plat_alat',arr)
    do i=1,3
       call get_value(arr,i,row)
       do j=1,3
          call get_value(row,j,platj(j,i)) ! row i = lattice vector i
       enddo
    enddo
    if(abs(alatj-alat)>tolst*alat .or. maxval(abs(platj-plat))>tolst) then
       why='alat or plat differs'; return
    endif
    call get_value(st,'species',arr)
    if(len(arr)/=nbas) then
       why='the number of sites differs'; return
    endif
    do ib=1,nbas
       call get_value(arr,ib,name)
       if(trim(name)/=trim(spid(ib))) then
          why='the species of a site differs'; return
       endif
    enddo
    call get_value(st,'af',arr,requested=.false.)
    do ib=1,nbas
       ival=0
       if(associated(arr)) call get_value(arr,ib,ival)
       if(ival/=afl(ib)) then
          why='the af label of a site differs'; return
       endif
    enddo
    call get_value(st,'frac',arr)
    do ib=1,nbas
       call get_value(arr,ib,row)
       do j=1,3
          call get_value(row,j,fracj(j))
       enddo
       frac = matmul(transpose(qlat),pos(:,ib))
       d = frac-fracj
       if(maxval(abs(d-nint(d)))>tolst) then
          why='a site position differs'; return
       endif
    enddo
    call get_value(root,'operations',ops)
    nop=len(ops)
    if(nop>ngmxj) call rx('symfind_json: more operations than ngmxj')
    pinv = transpose(qlat) ! plat^-1
    do iop=1,nop
       call get_value(ops,iop,op)
       call get_value(op,'time_reversal',trev(iop))
       call get_value(op,'rotation',arr)
       do i=1,3
          call get_value(arr,i,row)
          do j=1,3
             call get_value(row,j,ival)
             rot(i,j)=ival
          enddo
       enddo
       call get_value(op,'translation',arr)
       do j=1,3
          call get_value(arr,j,tr(j))
       enddo
       g(:,:,iop) = matmul(plat,matmul(dble(rot),pinv))
       ag(:,iop)  = matmul(plat,tr)
    enddo
    ng=nop
    if(maxval(abs(g(:,:,1)-reshape([1d0,0d0,0d0,0d0,1d0,0d0,0d0,0d0,1d0],[3,3])))>1d-10 .or. maxval(abs(ag(:,1)))>1d-10 &
         .or. trev(1)) call rx('symfind_json: the first operation of '//trim(fname)//' is not the identity')
    ok=.true.
  end subroutine symfind_json

  subroutine symfind_spglib(nbas,ityp,afl,pos,plat,qlat,alat,ngmxj, ng,rot,tr,trev,spgnum,spgsym) !Space group by spglib (C)
    ! (2026-10-02 08:27, MD/symmetry_spglib.md) The operations x' = R x + t (fractional coordinates of plat, R integer) of the crystal,
    ! ityp(ib) the species index of each site. With AF labels (afl = +k, -k on the sites of a pair) the pairs are one type with
    ! the moments +1 and -1, and spg_get_symmetry_with_site_tensors gives the magnetic group: trev=.true. for the operations
    ! with time reversal (they exchange up and down); those without must be the group of the crystal (spg_get_symmetry with
    ! the species told apart; checked). Order: the identity, the rest of the crystal group, the time-reversed ones.
    ! t is reduced to [0,1). symprec 1e-5 angstrom, as symfind.py.
    use iso_c_binding, only: c_int, c_double, c_char, c_null_char
    implicit none
    integer,intent(in):: nbas,ngmxj,ityp(nbas),afl(nbas)
    real(8),intent(in):: pos(3,nbas),plat(3,3),qlat(3,3),alat
    integer,intent(out):: ng,rot(3,3,ngmxj),spgnum
    real(8),intent(out):: tr(3,ngmxj)
    logical,intent(out):: trev(ngmxj)
    character(*),intent(out):: spgsym
    interface
       integer(c_int) function spg_get_symmetry(rotation,translation,max_size,lattice,position,types,num_atom,symprec) &
            bind(C,name='spg_get_symmetry')
         import:: c_int,c_double
         integer(c_int):: rotation(3,3,*),types(*)
         real(c_double):: translation(3,*),lattice(3,3),position(3,*)
         integer(c_int),value:: max_size,num_atom
         real(c_double),value:: symprec
       end function spg_get_symmetry
       integer(c_int) function spg_get_symmetry_with_site_tensors(rotation,translation,equivalent_atoms,primitive_lattice, &
            spin_flips,max_size,lattice,position,types,tensors,tensor_rank,num_atom,with_time_reversal,is_axial,symprec) &
            bind(C,name='spg_get_symmetry_with_site_tensors')
         import:: c_int,c_double
         integer(c_int):: rotation(3,3,*),equivalent_atoms(*),spin_flips(*),types(*)
         real(c_double):: translation(3,*),primitive_lattice(3,3),lattice(3,3),position(3,*),tensors(*)
         integer(c_int),value:: max_size,tensor_rank,num_atom,with_time_reversal,is_axial
         real(c_double),value:: symprec
       end function spg_get_symmetry_with_site_tensors
       integer(c_int) function spg_get_international(symbol,lattice,position,types,num_atom,symprec) &
            bind(C,name='spg_get_international')
         import:: c_int,c_double,c_char
         character(kind=c_char):: symbol(11)
         real(c_double):: lattice(3,3),position(3,*)
         integer(c_int):: types(*)
         integer(c_int),value:: num_atom
         real(c_double),value:: symprec
       end function spg_get_international
    end interface
    real(8),parameter:: bohr_angstrom=0.529177210903d0, symprec=1d-5
    real(c_double):: lat(3,3),frac(3,nbas),trc(3,ngmxj),primlat(3,3),spins(nbas)
    integer(c_int):: rc(3,3,ngmxj),typ(nbas),typm(nbas),equiv(nbas),flips(ngmxj),n,nc
    integer(c_int):: rcc(3,3,ngmxj)
    real(c_double):: trcc(3,ngmxj)
    character(kind=c_char):: sym(11)
    integer:: ib,jb,i,ig,jg,i0,k,order(ngmxj)
    logical:: found,anyaf
    ! C: lattice[3][3] with the lattice vectors as columns -> the Fortran array is its transpose; rotation[n][3][3] row-major
    ! -> rc(:,:,i) is the transpose of R; position[n][3] and translation[n][3] map directly.
    lat = transpose(plat*alat*bohr_angstrom)
    do ib=1,nbas
       frac(:,ib) = matmul(transpose(qlat),pos(:,ib))
    enddo
    typ = ityp
    nc = spg_get_symmetry(rcc,trcc,ngmxj,lat,frac,typ,nbas,symprec)
    if(nc<=0) call rx('symfind_spglib: spg_get_symmetry found no operation')
    spgnum = spg_get_international(sym,lat,frac,typ,nbas,symprec)
    spgsym = ' '
    do i=1,11
       if(sym(i)==c_null_char) exit
       spgsym(i:i)=sym(i)
    enddo
    anyaf = any(afl/=0)
    if(anyaf) then ! the AF pairs as one type, with the moments +-1
       typm = typ
       spins = 0d0
       do ib=1,nbas
          if(afl(ib)==0) cycle
          spins(ib) = sign(1d0,dble(afl(ib)))
          if(afl(ib)<0) then
             found=.false.
             do jb=1,nbas
                if(afl(jb)==-afl(ib)) then
                   typm(ib)=typ(jb); found=.true.; exit
                endif
             enddo
             if(.not.found) call rx('symfind_spglib: a site with af<0 has no partner with af>0')
          endif
       enddo
       n = spg_get_symmetry_with_site_tensors(rc,trc,equiv,primlat,flips,ngmxj,lat,frac,typm,spins,0,nbas,1,0,symprec)
       if(n<=0) call rx('symfind_spglib: spg_get_symmetry_with_site_tensors found no operation')
       if(count(flips(1:n)==1)/=nc) call rx('symfind_spglib: the magnetic group without time reversal is not the group of the crystal')
       do ig=1,n ! each operation without time reversal must be one of the crystal group
          if(flips(ig)/=1) cycle
          found=.false.
          do jg=1,nc
             if(all(rc(:,:,ig)==rcc(:,:,jg)) .and. sameT(trc(:,ig),trcc(:,jg))) then
                found=.true.; exit
             endif
          enddo
          if(.not.found) call rx('symfind_spglib: the magnetic group without time reversal is not the group of the crystal')
       enddo
    else
       n = nc
       rc(:,:,1:n) = rcc(:,:,1:n)
       trc(:,1:n) = trcc(:,1:n)
       flips(1:n) = 1
    endif
    ! the identity first, then the crystal group, then the time-reversed operations
    i0=0
    do ig=1,n
       if(flips(ig)==1 .and. all(rc(:,:,ig)==reshape([1,0,0,0,1,0,0,0,1],[3,3])) .and. sameT(trc(:,ig),[0d0,0d0,0d0])) then
          i0=ig; exit
       endif
    enddo
    if(i0==0) call rx('symfind_spglib: no identity')
    k=1; order(1)=i0
    do ig=1,n
       if(ig/=i0 .and. flips(ig)==1) then
          k=k+1; order(k)=ig
       endif
    enddo
    do ig=1,n
       if(flips(ig)/=1) then
          k=k+1; order(k)=ig
       endif
    enddo
    ng=n
    do i=1,n
       ig=order(i)
       rot(:,:,i) = transpose(rc(:,:,ig))
       tr(:,i) = trc(:,ig)-floor(trc(:,ig)+1d-10)          ! [0,1)
       where(abs(tr(:,i))<1d-10) tr(:,i)=0d0
       trev(i) = flips(ig)/=1
    enddo
  contains
    logical function sameT(a,b)
      real(c_double),intent(in):: a(3),b(3)
      real(8):: d(3)
      d=a-b
      sameT = maxval(abs(d-nint(d)))<1d-6
    end function sameT
  end subroutine symfind_spglib

  subroutine write_symjson(fname,nbas,spid,afl,pos,plat,qlat,alat,ng,rot,tr,trev,spgnum,spgsym,made_by) !Write symmetry.<sname>.json
    ! (2026-10-02 08:27) The format read by symfind_json and written by symfind.py ("ecalj-symmetry-1"), units named in the keys.
    implicit none
    character(*),intent(in):: fname,spid(nbas),spgsym,made_by
    integer,intent(in):: nbas,afl(nbas),ng,rot(3,3,ng),spgnum
    real(8),intent(in):: pos(3,nbas),plat(3,3),qlat(3,3),alat,tr(3,ng)
    logical,intent(in):: trev(ng)
    integer:: ifi,ib,ig,i,npure
    real(8):: frac(3)
    character(30):: d8
    character(10):: tm
    call date_and_time(date=d8,time=tm)
    npure = count([(all(rot(:,:,ig)==reshape([1,0,0,0,1,0,0,0,1],[3,3])) .and. .not.trev(ig), ig=1,ng)])
    open(newunit=ifi,file=trim(fname),status='replace')  ! rank 0 only (the caller)
    write(ifi,'(a)') '{'
    write(ifi,'(a)') ' "format": "ecalj-symmetry-1",'
    write(ifi,'(a)') ' "made_by": "'//trim(made_by)//'",'
    write(ifi,'(a)') ' "date": "'//d8(1:4)//'-'//d8(5:6)//'-'//d8(7:8)//'T'//tm(1:2)//':'//tm(3:4)//'",'
    write(ifi,'(a)') ' "structure": {'
    write(ifi,'(a)') '  "alat_bohr": '//r2s(alat)//','
    write(ifi,'(a)') '  "plat_alat": ['//v2s(plat(:,1))//', '//v2s(plat(:,2))//', '//v2s(plat(:,3))//'],'
    write(ifi,'(a)') '  "plat_unit": "rows = lattice vectors in alat (as [struc] plat)",'
    write(ifi,'(a)',advance='no') '  "species": ['
    do ib=1,nbas
       write(ifi,'(a)',advance='no') '"'//trim(spid(ib))//'"'//merge(', ','],',ib<nbas)
    enddo
    write(ifi,*)
    write(ifi,'(a)',advance='no') '  "af": ['
    do ib=1,nbas
       write(ifi,'(i0,a)',advance='no') afl(ib),merge(', ','],',ib<nbas)
    enddo
    write(ifi,*)
    write(ifi,'(a)') '  "frac": ['
    do ib=1,nbas
       frac = matmul(transpose(qlat),pos(:,ib))
       write(ifi,'(a)') '   '//v2s(frac)//merge(',',' ',ib<nbas)
    enddo
    write(ifi,'(a)') '  ],'
    write(ifi,'(a)') '  "frac_unit": "fractional coordinates of plat"'
    write(ifi,'(a)') ' },'
    write(ifi,'(a)') ' "symprec": 1e-05, "symprec_unit": "angstrom",'
    write(ifi,'(a,i0,a)') ' "spacegroup": {"number": ',spgnum,', "international": "'//trim(spgsym)//'"},'
    write(ifi,'(a,i0,a,i0,a,i0,a)') ' "n_operations": ',ng,', "n_pure_translations": ',npure,', "n_time_reversed": ',count(trev),','
    write(ifi,'(a)') ' "rotation_unit": "integer matrix in the basis of plat: x'' = R x + t, x fractional (columns of plat)",'
    write(ifi,'(a)') ' "translation_unit": "fractional coordinates of plat",'
    write(ifi,'(a)') ' "operations": ['
    do ig=1,ng
       write(ifi,'(a,3(a,i0,a,i0,a,i0,a),a)') '  {"rotation": [', &
            ('[',rot(i,1,ig),', ',rot(i,2,ig),', ',rot(i,3,ig),merge('], ',']  ',i<3), i=1,3), '], '
       write(ifi,'(a)') '   "translation": '//v2s(tr(:,ig))//', "time_reversal": '//trim(merge('true ','false',trev(ig)))// &
            '}'//merge(',',' ',ig<ng)
    enddo
    write(ifi,'(a)') ' ]'
    write(ifi,'(a)') '}'
    close(ifi)
  contains
    function r2s(x) result(s)
      real(8),intent(in):: x
      character(:),allocatable:: s
      character(30):: b
      write(b,'(es23.15e3)') x
      s=trim(adjustl(b))
    end function r2s
    function v2s(v) result(s)
      real(8),intent(in):: v(3)
      character(:),allocatable:: s
      s='['//r2s(v(1))//', '//r2s(v(2))//', '//r2s(v(3))//']'
    end function v2s
  end subroutine write_symjson
end module m_symfind
