!> Generate GWinput.toml.tmp -- a TOML template for GWinput suitable for
!  the TOML-only m_GWinput reader. User edits this file then renames to
!  GWinput.toml.
module m_gwinit
  private
  public :: gwinit_v2
contains

  subroutine gwinit_v2() bind(C)
    use m_hamindex0,only: readhamindex0,nbas,lmxax,konft, &
         lmxaa => lmxa, nindx, lindx, mnla => ndima, iat => ibasindx, &
         caption, spid, npqn, zz, pqn
    implicit none
    integer :: ifi
    integer :: ibas, lk, izz, nx, isp
    integer :: iatbk, kkk
    integer :: nocc, nunocc, noccc, nunoccc, ncinc, ncinc2
    integer, parameter :: n1q = 4, n2q = 4, n3q = 4   ! default BZ mesh
    integer, allocatable :: konf(:,:), nncx(:,:), nnvv(:,:), lcutmx(:)
    character(len=1) :: seg2
    character(len=64):: aaa

    write(6,"(a,3i5)") ' Default n1q n2q n3q = ', n1q, n2q, n3q
    call readhamindex0()

    allocate(konf(0:lmxax,nbas), nncx(0:lmxax,nbas))
    isp  = 1                  ! konf is not spin-dependent
    konf = konft(:,:,isp)
    do ibas = 1, nbas
       write(6,"(i4,f9.4,100i4)") ibas, zz(ibas), lmxaa(ibas), konf(0:lmxaa(ibas),ibas)
       do lk = 0, lmxaa(ibas)
          nncx(lk, ibas) = konf(lk, ibas) - 1 - lk   ! number of cores per (l, ibas)
       enddo
    enddo

    allocate(nnvv(0:lmxax, nbas), source = 0)
    do izz = 1, mnla
       if (nnvv(lindx(izz), iat(izz)) < nindx(izz)) &
            nnvv(lindx(izz), iat(izz)) = nindx(izz)
    enddo

    !! ===== Write GWinput.toml.tmp =====
    open(newunit=ifi, file='GWinput.toml.tmp')

    write(ifi,'(a)') '# GWinput.toml.tmp -- auto-generated by gwinit (TOML template).'
    write(ifi,'(a)') '# Edit then rename to GWinput.toml. m_GWinput consumes this file.'
    write(ifi,'(a)')

    write(ifi,'(a)') '[gw]'
    write(ifi,'(a,3(i0,a),a)') 'n1n2n3 = [', n1q, ', ', n2q, ', ', n3q, ']', '   # BZ mesh'
    write(ifi,'(a)') 'QpGcut_psi = 4.0    # |q+G| cutoff for eigenfunctions  (a.u. unless unit_2pioa=true)'
    write(ifi,'(a)') 'QpGcut_cou = 3.0    # |q+G| cutoff for Coulomb / W'
    write(ifi,'(a)') 'unit_2pioa = false  # false: a.u.; true: 2*pi/alat'
    write(ifi,'(a)') 'alpha_OffG = 1.0    # offset-Gamma auxiliary function'
    write(ifi,'(a)') '# emax_chi0 = 999.0   # (Ry) optional emax cutoff for chi0'
    write(ifi,'(a)') 'emax_sigm  = 3.0    # (Ry) emax cutoff for Sigma'
    write(ifi,'(a)')
    write(ifi,'(a)') '# ----- Frequencies -----'
    write(ifi,'(a)') 'niw           = 10      # # of frequencies along Im axis (try 6 or 12 for tests)'
    write(ifi,'(a)') 'HistBin_dw    = 1e-4    # bin width along real axis at omega=0'
    write(ifi,'(a)') 'HistBin_ratio = 1.05    # bin: frhis(iw) = (dw/(r-1))*(exp((r-1)*(iw-1)) - 1)'
    write(ifi,'(a)') '# SmearX0 = 0.01        # (Ha) Gaussian smear for X0 (metals)'
    write(ifi,'(a)') 'GaussSmear = true       # Gaussian smearing for poles of G^LDA in hsfp0'
    write(ifi,'(a)') 'deltaw = 0.02           # (a.u.) numerical-derivative mesh for Z factor'
    write(ifi,'(a)') 'esmr   = 0.003          # (Ry) hsfp0 smearing; keep < band gap for insulators'
    write(ifi,'(a)')
    write(ifi,'(a)') '# ----- Q for diagonal Sigma=GW (gw_lmfh) -----'
    write(ifi,'(a)') '# QforGWIBZ = true   # use IBZ instead of <QforGW>'
    write(ifi,'(a)') 'EMAXforGW = 15      # eV (above EFermi) bands cutoff for Sigma=GW'
    write(ifi,'(a)')
    write(ifi,'(a)') '# ----- Q for dielectric eps -----'
    write(ifi,'(a)') 'QforEPSau = true    # interpret <QforEPS> as a.u.'
    write(ifi,'(a)')
    write(ifi,'(a)') '# ----- Wannier (uncomment to use) -----'
    write(ifi,'(a)') '# wan_out_emin  = -1.05   # eV relative to EFermi'
    write(ifi,'(a)') '# wan_out_emax  =  2.4'
    write(ifi,'(a)') '# wan_maxit_1st = 300'
    write(ifi,'(a)') '# wan_conv_1st  = 1e-7'
    write(ifi,'(a)') '# wan_max_1st   = 0.1'
    write(ifi,'(a)') '# wan_maxit_2nd = 1500'
    write(ifi,'(a)') '# wan_max_2nd   = 0.3'
    write(ifi,'(a)') '# wan_conv_end  = 1e-8'
    write(ifi,'(a)')

    !! ----- [product_basis] -----
    write(ifi,'(a)') '[product_basis]'
    write(ifi,'(a)') '# Tolerance to drop linearly-dependent products. Larger gives smaller PB.'
    write(ifi,'(a)') 'tolerance = [1e-3]'
    write(ifi,'(a)')

    write(ifi,'(a)') '# lcutmx(atom): max l-cutoff for the product basis per atom.'
    write(ifi,'(a)') '# Use 4 for atoms with valence d (Ni, Ga, etc.), 6 for f.'
    allocate(lcutmx(nbas), source = 4)
    do ibas = 1, nbas
       if (zz(ibas) <  10.5d0)                          lcutmx(ibas) = 2
       if (57.001d0 < zz(ibas) .and. zz(ibas) < 71.001d0) lcutmx(ibas) = 6
       if (89.001d0 < zz(ibas))                         lcutmx(ibas) = 6
    enddo
    call write_int_vec(ifi, 'lcutmx', lcutmx)
    write(ifi,'(a)')

    write(ifi,'(a)') '# nlx: per (iatom, l) row [iatom, l, nnvv, nnc]'
    write(ifi,'(a)') 'nlx = ['
    do ibas = 1, nbas
       do lk = 0, lmxaa(ibas)
          write(ifi,'(a,4(i0,a))') '  [', ibas, ', ', lk, ', ', nnvv(lk, ibas), ', ', nncx(lk, ibas), '],'
       enddo
    enddo
    write(ifi,'(a)') ']'
    write(ifi,'(a)')

    !! valence rows
    write(ifi,'(a)') '# valence: [iatom, l, n, occ, unocc]'
    write(ifi,'(a)') 'valence = ['
    iatbk = 0
    do ibas = 1, nbas
       do lk = 0, lmxaa(ibas)
          do nx = 1, npqn
             do izz = 1, mnla
                if (iat(izz) == ibas .and. lk == lindx(izz) .and. nx == nindx(izz)) then
                   call valence_occ(zz(ibas), pqn(izz), lindx(izz), nindx(izz), nocc, nunocc)
                   write(ifi,'(a,5(i0,a),a)') '  [', iat(izz), ', ', lindx(izz), ', ', &
                        nindx(izz), ', ', nocc, ', ', nunocc, '],', '   # '//trim(caption(izz))
                   exit
                endif
             enddo
          enddo
       enddo
    enddo
    write(ifi,'(a)') ']'
    write(ifi,'(a)')

    !! core rows
    write(ifi,'(a)') '# core: [iatom, l, n, occ, unocc, forX0, forSxc]'
    write(ifi,'(a)') 'core = ['
    do ibas = 1, nbas
       do lk = 0, lmxaa(ibas)
          if (lk == 0) seg2 = 'S'
          if (lk == 1) seg2 = 'P'
          if (lk == 2) seg2 = 'D'
          if (lk == 3) seg2 = 'F'
          if (lk == 4) seg2 = 'G'
          if (lk == 5) seg2 = 'H'
          if (lk == 6) seg2 = 'I'
          do kkk = lk + 1, konf(lk, ibas) - 1
             noccc   = 0
             nunoccc = 0
             ncinc   = 0
             ncinc2  = 0
             write(ifi,'(a,7(i0,a),a)') '  [', ibas, ', ', lk, ', ', kkk - lk, ', ', &
                  noccc, ', ', nunoccc, ', ', ncinc, ', ', ncinc2, '],', &
                  '   # '//char(48 + kkk)//seg2
          enddo
       enddo
    enddo
    write(ifi,'(a)') ']'
    write(ifi,'(a)')

    !! ----- [blocks] -----
    write(ifi,'(a)') '[blocks]'
    write(ifi,'(a)') 'QforEPS = """'
    write(ifi,'(a)') ' 0 0 0.00050'
    write(ifi,'(a)') ' 0 0 0.00100'
    write(ifi,'(a)') ' 0 0 0.00200'
    write(ifi,'(a)') '"""'
    write(ifi,'(a)')
    write(ifi,'(a)') '# QforEPSL = """'
    write(ifi,'(a)') '#  0 0 0   1 0 0  20'
    write(ifi,'(a)') '# """'
    write(ifi,'(a)')

    write(ifi,'(a)') 'QforGW = """'
    write(ifi,'(a)') ' 0.0 0.0 0.0'
    write(ifi,'(a)') ' 0.1 0.0 0.0'
    write(ifi,'(a)') ' 0.2 0.0 0.0'
    write(ifi,'(a)') ' 0.3 0.0 0.0'
    write(ifi,'(a)') '"""'
    write(ifi,'(a)')

    write(ifi,'(a)') '# Worb: atomic orbitals for MLWF / MLO modelling.'
    write(ifi,'(a)') '# Each row: <iatom> <label> <lm1> <lm2> ...'
    write(ifi,'(a)') '# lm index: 1=s, 2=py, 3=pz, 4=px, 5=xy, 6=yz, 7=3z^2-1, 8=xz, 9=x^2-y^2, ... (real harmonics)'
    write(ifi,'(a)') 'Worb = """'
    do ibas = 1, nbas
       write(ifi,'(a,i0,1x,a,a)') '! ', ibas, trim(spid(ibas)), '   1 2 3 4 5 6 7 8 9'
    enddo
    write(ifi,'(a)') '"""'

    close(ifi)
    stop ' OK! GWinput.toml.tmp generated. Rename to GWinput.toml after editing.'
  end subroutine gwinit_v2


  subroutine write_int_vec(ifi, key, v)
    integer, intent(in) :: ifi, v(:)
    character(*), intent(in) :: key
    integer :: i
    write(ifi, '(a)', advance='no') key//' = ['
    do i = 1, size(v)
       if (i < size(v)) then
          write(ifi, '(i0,a)', advance='no') v(i), ', '
       else
          write(ifi, '(i0)', advance='no') v(i)
       endif
    enddo
    write(ifi, '(a)') ']'
  end subroutine write_int_vec


  !> Compute occ / unocc flags for valence rows from atomic Z and pqn / l.
  pure subroutine valence_occ(zc, pq, lx, nxx, nocc, nunocc)
    real(8),    intent(in)  :: zc
    integer,    intent(in)  :: pq, lx, nxx
    integer,    intent(out) :: nocc, nunocc
    nocc = 0
    nunocc = 1
    ! s
    if (lx == 0 .and. pq == 2 .and. zc > 1.5d0)  nocc = 1
    if (lx == 0 .and. pq == 3 .and. zc > 4.5d0)  nocc = 1
    if (lx == 0 .and. pq == 4 .and. zc > 12.5d0) nocc = 1
    if (lx == 0 .and. pq == 5 .and. zc > 30.5d0) nocc = 1
    if (lx == 0 .and. pq == 6 .and. zc > 48.5d0) nocc = 1
    if (lx == 0 .and. pq == 7 .and. zc > 80.5d0) nocc = 1
    if (lx == 0 .and. pq == 2 .and. zc > 10.5d0) nunocc = 0
    if (lx == 0 .and. pq == 3 .and. zc > 18.5d0) nunocc = 0
    if (lx == 0 .and. pq == 4 .and. zc > 36.5d0) nunocc = 0
    if (lx == 0 .and. pq == 5 .and. zc > 54.5d0) nunocc = 0
    if (lx == 0 .and. pq == 6 .and. zc > 86.5d0) nunocc = 0
    ! p
    if (lx == 1 .and. pq == 2 .and. zc > 1.5d0)  nocc = 1
    if (lx == 1 .and. pq == 3 .and. zc > 4.5d0)  nocc = 1
    if (lx == 1 .and. pq == 4 .and. zc > 12.5d0) nocc = 1
    if (lx == 1 .and. pq == 5 .and. zc > 30.5d0) nocc = 1
    if (lx == 1 .and. pq == 6 .and. zc > 48.5d0) nocc = 1
    if (lx == 1 .and. pq == 7 .and. zc > 80.5d0) nocc = 1
    if (lx == 1 .and. pq == 2 .and. zc > 10.5d0) nunocc = 0
    if (lx == 1 .and. pq == 3 .and. zc > 18.5d0) nunocc = 0
    if (lx == 1 .and. pq == 4 .and. zc > 36.5d0) nunocc = 0
    if (lx == 1 .and. pq == 5 .and. zc > 54.5d0) nunocc = 0
    if (lx == 1 .and. pq == 6 .and. zc > 86.5d0) nunocc = 0
    ! d
    if (lx == 2 .and. pq == 3 .and. zc > 20.5d0) nocc = 1
    if (lx == 2 .and. pq == 4 .and. zc > 38.5d0) nocc = 1
    if (lx == 2 .and. pq == 5 .and. zc > 56.5d0) nocc = 1
    if (lx == 2 .and. pq == 3 .and. zc > 30.5d0) nunocc = 0
    if (lx == 2 .and. pq == 4 .and. zc > 48.5d0) nunocc = 0
    ! f
    if (lx == 3 .and. pq == 4 .and. zc > 57.5d0) nocc = 1
    if (lx == 3 .and. pq == 5 .and. zc > 89.5d0) nocc = 1
    if (lx == 2 .and. pq == 4 .and. zc > 71.5d0) nunocc = 0
    ! g+
    if (lx > 3) then
       nocc   = 0
       nunocc = 0
    endif
    ! phidot skip
    if (nxx == 2) then
       nocc   = 0
       nunocc = 0
    endif
  end subroutine valence_occ

end module m_gwinit
