subroutine nwit(nvario,iter,maxit,lhf,lhk,etol,qtol,qdiff,amom,etot,sev, lsc)
  use m_lmfinit,only: nsp
  use m_lgunit,only:stdo,stdl
  use m_ext,only:      sname
  use m_ldau,only:  eorb
  use m_ftox
  !- Add to save file, determine whether to continue execution
  ! ----------------------------------------------------------------------
  !i Inputs
  !i   nvario:-99 for MD no variables.
  !i   iter  :current iteration number
  !i   maxit :maximum number of iterations
  !i   lhf   :T if result is generated by overlapped free atoms
  !i         :(only affects key character in save file)
  !i   lhk   :1, if HK energy is available
  !i         :Add 10 to use HK energy for convergence, if available
  !i   etol  :energy tolerance for convergence.  If 0, criterion not used
  !i         :Energy change from prior iteration is compared to etol.
  !i   qtol  :charge tolerance for convergence.  If 0, criterion not used
  !i   qdiff :change in charge
  !i   amom  :magnetic moment
  !i   etot  :etot(1) = HF energy; etot(2) = KS energy
  !o Outputs
  !o   lsc   :0 self-consistency achieved (diffe<=etol, qdiff<=qtol)
  !o         :1 if not self-consistent, but encountered max. no. iter.
  !o         :2 Harris energy from overlap of free atoms (iter=1 and lhf=t)
  !o         :3 otherwise
  ! ----------------------------------------------------------------------
  implicit none
  logical :: lhf
  integer :: iter,maxit,lhk,lsc,nvario
  double precision :: etol,qtol,qdiff,amom,etot(2)
  integer :: lbl
  logical :: more,letol,lqtol
  double precision :: diffe,sev
  character flg*1
  real(8),save:: ehf1=0d0,ehk1=0d0
  character*255:: formatc(903:904),lbll
  real(8):: rydberg
  character(360) :: sout
  call tcn('nwit')
  if(nvario==-99) then
     lsc=4
     goto 1010
  endif   
  lsc = 3
  more = .true.
  if(iter >= maxit) then
     lsc = 1
     more = .false.
  endif
  if (lhf) lsc = 2
  formatc(903)="(/  ' it',i4,'  of',i4,'    ehf=',f15.6:'   ehk=',f15.6)"
  formatc(904)="(/'   it',i3,'  of',i3,'    ehf=',f15.6:'   ehk=',f15.6)"
  lbl=904 !assign 904 to lbl
  if (maxit > 999 .OR. iter > 999) lbl=903 !assign 903 to lbl
  lbll=formatc(lbl)
  if (mod(lhk,10) == 1) write(stdo,trim(lbll)) iter,maxit,etot(1),etot(2)
  if (mod(lhk,10) == 0) write(stdo,trim(lbll)) iter,maxit,etot(1)
  if (iter > 1 .OR. etol == 0) then
     diffe = etot(1)-ehf1
     if (lhk == 11) diffe = etot(2)-ehk1
     letol = dabs(diffe) .le. etol .or. etol .le. 0
     lqtol = dabs(qdiff) .le. qtol .or. qtol .le. 0
     if (letol .AND. lqtol) then
        more = .false.
        lsc = 0
     endif
     if (iter > 1) then
        if (mod(lhk,10) == 1) write(stdo,905) ehf1,ehk1,diffe,qdiff,etol,qtol,more
        if (mod(lhk,10) == 0) write(stdo,906) ehf1,     diffe,qdiff,etol,qtol,more
     else
        write(stdo,907) qdiff,qtol,more
     endif
905  format(' From last iter',4x,'ehf=',f15.6,'   ehk=',f15.6, &
          /' diffe(q)=',f10.6,' (',f8.6,')','    tol=',f9.6,' (',f8.6,')','   more=',l1)
906  format(' From last iter',4x,'ehf=',f15.6,/' diffe(q)=',f10.6,' (',f8.6,')', &
          '    tol=',f9.6,' (',f8.6,')','   more=',l1)
907  format(16x,'rms dq=',f10.6,8x,'tol=',f9.6,'   more=',l1)
  endif
  ! ... Save for future iterations
  ehk1 = etot(2)
  ehf1 = etot(1)
1010 continue
  block
    integer:: ifi
    real(8):: rydberg
    character(5):: svflg='cxhiC'
    sout = svflg(lsc+1:lsc+1)
    if (nsp == 2) sout=trim(sout)//' mmom='//ftof(amom,4)
    if(eorb==0.and.etot(1)/= 0d0)sout=trim(sout)//' ehf(eV)='//ftof(etot(1)*rydberg(),6)
    if(etot(2)/=0d0) sout=trim(sout)//' ehk(eV)='//ftof(etot(2)*rydberg(),6)
    if(sev/=0) sout=trim(sout)//' sev(eV)='//ftof(sev*rydberg(),6)
    open(newunit=ifi,file='save.'//trim(sname),position='append')
    write(ifi, "(a)") trim(sout)
    close(ifi)
    write(stdo,"(a)") trim(sout)
  end block
  call tcx('nwit')
end subroutine nwit
