subroutine toksw_init(debug)
  !- Declares program-specific tokens
  !! For each program such as LMFA:,
  !!   we supply switches. For example,
  !!   If SPEC_ATOM_RSMA  exits, it means SPEC_ATOM_RSMA is required.
  !!   If SPEC_ATOM_RSMA~ exits, it means SPEC_ATOM_RSMA is optional.
  !!   If SPEC_ATOM_RSMA~ do not exit, it means SPEC_ATOM_RSMA is not used.
  use m_toksw
  !     implicit none
  character*(200):: io_sw, struc_sw
  character*(50) sscale
  character*(200):: dyn_mstat, dyn_md
  logical:: debug
  call clear_swtok(debug)
  io_sw = ' HEADER~ CONST~ CMD~ IO_SHOW~ IO_HELP~ IO_VERBOS~ '// &
       'IO_WKP~ IO_IACTIV~ IO_TIM~ OPTIONS_Q~'
  struc_sw = &
       ' STRUC STRUC_NSPEC~ STRUC_NCLASS STRUC_FILE~ STRUC_NBAS '// &
       'STRUC_PLAT STRUC_ALAT STRUC_DALAT~ STRUC_NL~ STRUC_SHEAR~ '// &
       'STRUC_ROT~ STRUC_DEFGRD~ STRUC_STRAIN~ STRUC_ALPHA~ '// &
       'STRUC_LOADV~ '
  sscale = ' SPEC_SCLWSR~ SPEC_WSRMAX~ SPEC_OMAX1~ SPEC_OMAX2~'
  dyn_mstat = ' DYN_MODE~ DYN_HESS~ '// &
       'DYN_XTOL~ DYN_GTOL~ DYN_STEP~ DYN_NKILL~ ' !DYN_MSTAT_PDEF~ '
  !dyn_md = ' DYN_MD~ DYN_MD_MODE DYN_MD_TSTEP~ DYN_MD_TEMP~ '// &
  !     'DYN_MD_TAUP~ DYN_MD_TIME DYN_MD_TAUB~ '
  ! --- LMFA switches ---
  call nswadd()
  call tkadd(" LMFA::" )
  call tkadd(" VERS_LM")
  call tkadd(trim(io_sw))
  call tkadd(trim(struc_sw))
  call tkadd(" OPTIONS~")
  call tkadd(" OPTIONS_FRZ~")
  call tkadd(" OPTIONS_HF~")
  call tkadd(" SPEC")
  call tkadd(sscale)
  call tkadd(" SPEC_ATOM")
  call tkadd(" SPEC_ATOM_A~")
  call tkadd(" SPEC_ATOM_AMASS~")
  call tkadd(" SPEC_ATOM_C-HOLE~")
  call tkadd(" SPEC_ATOM_C-HQ~")
  call tkadd(" SPEC_ATOM_CSTRMX~")
  call tkadd(" SPEC_ATOM_EH~")
  call tkadd(" SPEC_ATOM_EH2~")
  call tkadd(" SPEC_ATOM_EREF~")
  call tkadd(" SPEC_ATOM_FRZWF~")
  call tkadd(" SPEC_ATOM_IDMOD~")
  call tkadd(" SPEC_ATOM_IDU~")
  call tkadd(" SPEC_ATOM_IDXDN~")
  call tkadd(" SPEC_ATOM_ISOTOPE")
  call tkadd(" SPEC_ATOM_JH~")
  call tkadd(" SPEC_ATOM_KMXA~")
  call tkadd(" SPEC_ATOM_LFOCA~")
  call tkadd(" SPEC_ATOM_LMX~")
  call tkadd(" SPEC_ATOM_LMXA~")
  call tkadd(" SPEC_ATOM_LMXL~")
  call tkadd(" SPEC_ATOM_MMOM~")
  call tkadd(" SPEC_ATOM_NMCORE~")
  call tkadd(" SPEC_ATOM_NR~")
  call tkadd(" SPEC_ATOM_P~")
  call tkadd(" SPEC_ATOM_PZ~")
  call tkadd(" SPEC_ATOM_Q~")
  call tkadd(" SPEC_ATOM_R")
  call tkadd(" SPEC_ATOM_R/A")
  call tkadd(" SPEC_ATOM_RCFA~")
  call tkadd(" SPEC_ATOM_RFOCA~")
  call tkadd(" SPEC_ATOM_RS3~")
  call tkadd(" SPEC_ATOM_RSMA~")
  call tkadd(" SPEC_ATOM_RSMFA~")
  call tkadd(" SPEC_ATOM_RSMG~")
  call tkadd(" SPEC_ATOM_RSMH~")
  call tkadd(" SPEC_ATOM_RSMH2~")
  call tkadd(" SPEC_ATOM_R/W")
  call tkadd(" SPEC_ATOM_UH~")
  call tkadd(" SPEC_ATOM_Z")
  call tkadd(" SITE")
  call tkadd(" SITE_FILE~")
  call tkadd(" SITE_MODE~")
  call tkadd(" SITE_ATOM")
  call tkadd(" SITE_ATOM_DPOS~")
  call tkadd(" SITE_ATOM_POS")
  call tkadd(" SITE_ATOM_XPOS")
  call tkadd(" SITE_ATOM_RELAX~")
  call tkadd(" SYMGRP~")
  call tkadd(" SYMGRPAF~")
  call tkadd(" EWALD~")
  call tkadd(" EWALD_AS~")
  call tkadd(" EWALD_NKDMX~")
  call tkadd(" EWALD_RPAD~")
  call tkadd(" EWALD_TOL~")
  call tkadd(" ITER ITER_NRMIX~")
  call tkadd(" HAM~")
  call tkadd(" HAM_NSPIN~")
  call tkadd(" HAM_REL~ HAM_SO~ HAM_SOCAXIS~")
  call tkadd(" HAM_XCFUN~")

  ! This call tkadd(" SPEC_ATOM_MIX~") was missing,
  ! then the initialization of default values for mxcst are not supplied
  !   --->this results in a strange behevior!!
  ! takao Sep11-tukuba 2009
  call tkadd(" SPEC_ATOM_MIX~")

  ! --- LMFGWD switches ---
  call nswadd()
  call tkadd(" LMFGWD::" )
  call tkadd(" VERS_LM")
  call tkadd(" VERS_FP")
  call tkadd(trim(io_sw))
  call tkadd(trim(struc_sw))
  call tkadd(" OPTIONS~")
  call tkadd(" OPTIONS_FRZ~")
  call tkadd(" OPTIONS_HF~")
  call tkadd(" HAM_NSPIN~ HAM_REL~ HAM_SO~ HAM_SOCAXIS~")
  call tkadd(" SPEC")
  call tkadd(sscale)
  call tkadd(" SPEC_ATOM")
  call tkadd(" SPEC_ATOM_A~")
  call tkadd(" SPEC_ATOM_AMASS~")
  call tkadd(" SPEC_ATOM_C-HOLE~")
  call tkadd(" SPEC_ATOM_C-HQ~")
  call tkadd(" SPEC_ATOM_CSTRMX~")
  call tkadd(" SPEC_ATOM_EH")
  call tkadd(" SPEC_ATOM_EH2~")
  call tkadd(" SPEC_ATOM_EREF~")
  call tkadd(" SPEC_ATOM_FRZWF~")
  call tkadd(" SPEC_ATOM_IDMOD~")
  call tkadd(" SPEC_ATOM_IDU~")
  call tkadd(" SPEC_ATOM_IDXDN~")
  call tkadd(" SPEC_ATOM_ISOTOPE")
  call tkadd(" SPEC_ATOM_JH~")
  call tkadd(" SPEC_ATOM_KMXA~")
  call tkadd(" SPEC_ATOM_LFOCA~")
  call tkadd(" SPEC_ATOM_LMX~")
  call tkadd(" SPEC_ATOM_LMXA~")
  call tkadd(" SPEC_ATOM_LMXL~")
  call tkadd(" SPEC_ATOM_LMXPB~")
  call tkadd(" SPEC_ATOM_MMOM~")
  call tkadd(" SPEC_ATOM_NMCORE~")
  call tkadd(" SPEC_ATOM_NR~")
  call tkadd(" SPEC_ATOM_P~")
  call tkadd(" SPEC_ATOM_PBAS~")
  call tkadd(" SPEC_ATOM_PBAS2~")
  call tkadd(" SPEC_ATOM_PZ~")
  call tkadd(" SPEC_ATOM_Q~")
  call tkadd(" SPEC_ATOM_R")
  call tkadd(" SPEC_ATOM_R/A")
  call tkadd(" SPEC_ATOM_RFOCA~")
  call tkadd(" SPEC_ATOM_RS3~")
  call tkadd(" SPEC_ATOM_RSMA~")
  call tkadd(" SPEC_ATOM_RSMFA~")
  call tkadd(" SPEC_ATOM_RSMG~")
  call tkadd(" SPEC_ATOM_RSMH")
  call tkadd(" SPEC_ATOM_RSMH2~")
  call tkadd(" SPEC_ATOM_R/W")
  call tkadd(" SPEC_ATOM_UH~")
  call tkadd(" SPEC_ATOM_Z")
  call tkadd(" SITE")
  call tkadd(" SITE_FILE~")
  call tkadd(" SITE_MODE~")
  call tkadd(" SITE_ATOM")
  call tkadd(" SITE_ATOM_DPOS~")
  call tkadd(" SITE_ATOM_POS")
  call tkadd(" SITE_ATOM_XPOS")
  call tkadd(" SITE_ATOM_RELAX~")
  call tkadd(" SITE_ATOM_AF~") !may2015
  call tkadd(" SYMGRP~")
  call tkadd(" SYMGRPAF~")
  call tkadd(" GW~")
  call tkadd(" GW_DELRE~")
  call tkadd(" GW_DELTA~")
  call tkadd(" GW_DELTAW~")
  call tkadd(" GW_ECUTS~")
  call tkadd(" GW_GCUTB~")
  call tkadd(" GW_GCUTX~")
  call tkadd(" GW_GSMEAR~")
  call tkadd(" GW_MKSIG~")
  call tkadd(" GW_NBAND~")
  call tkadd(" GW_NIME~")
  call tkadd(" GW_NKABC~")
  call tkadd(" GW_PBTOL~")
  call tkadd(" GW_QOFFP~")
  call tkadd(" BZ")
  call tkadd(" BZ_BZJOB~")
  call tkadd(" BZ_DELEF~")
  call tkadd(" BZ_DMAT~")
  call tkadd(" BZ_DOS~")
  call tkadd(" BZ_DOSMAX~")
  call tkadd(" BZ_EF0~")
  call tkadd(" BZ_EFMAX~")
  call tkadd(" BZ_FSMOM~")
  call tkadd(" BZ_FSMOMMETHOD~")
  call tkadd(" BZ_GETQP~")
  !      call tkadd(" BZ_INVIT~")
  call tkadd(" BZ_METAL~")
  call tkadd(" BZ_MULL~")
  call tkadd(" BZ_N~")
  call tkadd(" BZ_NEVMX~")
  call tkadd(" BZ_NKABC~")
  call tkadd(" BZ_NOINV~")
  call tkadd(" BZ_NPTS~")
  call tkadd(" BZ_N.W~")
  call tkadd(" BZ_PUTQP~")
  call tkadd(" BZ_SAVDOS~")
  call tkadd(" BZ_TETRA~")
  call tkadd(" BZ_W~")
  call tkadd(" BZ_ZBAK~")
  call tkadd(" EWALD~")
  call tkadd(" EWALD_AS~")
  call tkadd(" EWALD_NKDMX~")
  call tkadd(" EWALD_RPAD~")
  call tkadd(" EWALD_TOL~")
  call tkadd(" HAM")
  call tkadd(" HAM_NSPIN~")
  call tkadd(" HAM_ELIND~")
  call tkadd(" HAM_EWALD~")
  call tkadd(" HAM_FORCES~")
  call tkadd(" HAM_FRZWF~")
  call tkadd(" HAM_READP~") !2022-9-5
  call tkadd(" HAM_V0FIX~") !2022-9-5
  call tkadd(" HAM_PNUFIX~") !2022-9-5
  call tkadd(" HAM_FTMESH")
  call tkadd(" HAM_GMAX")
  call tkadd(" HAM_PMAX~")
  call tkadd(" HAM_PMIN~")
  call tkadd(" HAM_PWMODE~ HAM_PWEMIN~ HAM_PWEMAX~ HAM_NPWPAD~")
  call tkadd(" HAM_REL~ HAM_SO~ HAM_SOCAXIS~")
  call tkadd(" HAM_RDSIG~")
  call tkadd(" HAM_RSRNGE~")
  call tkadd(" HAM_ScaledSigma~")
  call tkadd(" HAM_SIGP~")
  call tkadd(" HAM_TOL~")
  call tkadd(" HAM_XCFUN~")
  call tkadd(" HAM_OVEPS~") !nov2015
  
  ! --- LMF switches ---
  call nswadd()
  call tkadd(" LMF::" )
  call tkadd(" VERS_LM")
  call tkadd(" VERS_FP")
  call tkadd(trim(io_sw))
  call tkadd(trim(struc_sw))
  call tkadd(" OPTIONS~")
  call tkadd(" OPTIONS_FRZ~")
  call tkadd(" OPTIONS_HF~")
  call tkadd(" OPTIONS_PFLOAT~")
  call tkadd(" SPEC")
  call tkadd(sscale)
  call tkadd(" SPEC_ATOM")
  call tkadd(" SPEC_ATOM_A~")
  call tkadd(" SPEC_ATOM_AMASS~")
  call tkadd(" SPEC_ATOM_C-HOLE~")
  call tkadd(" SPEC_ATOM_C-HQ~")
  call tkadd(" SPEC_ATOM_CSTRMX~")
  call tkadd(" SPEC_ATOM_EH")
  call tkadd(" SPEC_ATOM_EH2~")
  call tkadd(" SPEC_ATOM_EREF~")
  call tkadd(" SPEC_ATOM_FRZWF~")
  call tkadd(" SPEC_ATOM_IDMOD~")
  call tkadd(" SPEC_ATOM_IDU~")
  call tkadd(" SPEC_ATOM_IDXDN~")
  call tkadd(" SPEC_ATOM_ISOTOPE")
  call tkadd(" SPEC_ATOM_JH~")
  call tkadd(" SPEC_ATOM_KMXA~")
  call tkadd(" SPEC_ATOM_LFOCA~")
  call tkadd(" SPEC_ATOM_LMX~")
  call tkadd(" SPEC_ATOM_LMXA~")
  call tkadd(" SPEC_ATOM_LMXL~")
  call tkadd(" SPEC_ATOM_MMOM~")
  call tkadd(" SPEC_ATOM_NMCORE~")
  call tkadd(" SPEC_ATOM_NR~")
  call tkadd(" SPEC_ATOM_P~")
  call tkadd(" SPEC_ATOM_PZ~")
  call tkadd(" SPEC_ATOM_Q~")
  call tkadd(" SPEC_ATOM_R")
  call tkadd(" SPEC_ATOM_R/A")
  call tkadd(" SPEC_ATOM_RFOCA~")
  call tkadd(" SPEC_ATOM_RS3~")
  call tkadd(" SPEC_ATOM_RSMA~")
  call tkadd(" SPEC_ATOM_RSMFA~")
  call tkadd(" SPEC_ATOM_RSMG~")
  call tkadd(" SPEC_ATOM_RSMH")
  call tkadd(" SPEC_ATOM_RSMH2~")
  call tkadd(" SPEC_ATOM_R/W")
  call tkadd(" SPEC_ATOM_UH~")
  call tkadd(" SPEC_ATOM_Z")
  ! This call tkadd(" SPEC_ATOM_MIX~") was missing,
  ! then the initialization of default values for mxcst are not supplied
  !   --->this results in a strange behevior!!
  ! takao Sep11-tukuba 2009
  call tkadd(" SPEC_ATOM_MIX~")
  ! ... for LMFRS
  call tkadd(" SPEC_ATOM_HCR~")
  call tkadd(" SPEC_ATOM_HCR/R~")
  call tkadd(" STR~")
  call tkadd(" STR_RMAX~ STR_RMAXS~")
  call tkadd(" SITE")
  call tkadd(" SITE_FILE~")
  call tkadd(" SITE_MODE~")
  call tkadd(" SITE_ATOM")
  call tkadd(" SITE_ATOM_DPOS~")
  call tkadd(" SITE_ATOM_POS")
  call tkadd(" SITE_ATOM_XPOS")
  call tkadd(" SITE_ATOM_RELAX~")
  call tkadd(" SITE_ATOM_AF~") !may2015
  call tkadd(" SYMGRP~")
  call tkadd(" SYMGRPAF~")
  call tkadd(" BZ")
  call tkadd(" BZ_BZJOB~")
  call tkadd(" BZ_DELEF~")
  call tkadd(" BZ_DMAT~")
  call tkadd(" BZ_DOS~")
  call tkadd(" BZ_DOSMAX~")
  call tkadd(" BZ_EF0~")
  call tkadd(" BZ_EFMAX~")
  call tkadd(" BZ_FSMOM~")
  call tkadd(" BZ_FSMOMMETHOD~")
  call tkadd(" BZ_GETQP~")
  call tkadd(" BZ_METAL~")
  call tkadd(" BZ_MULL~")
  call tkadd(" BZ_N~")
  call tkadd(" BZ_NEVMX~")
  call tkadd(" BZ_NKABC")
  call tkadd(" BZ_NOINV~")
  call tkadd(" BZ_NPTS~")
  call tkadd(" BZ_N.W~")
  call tkadd(" BZ_PUTQP~")
  call tkadd(" BZ_SAVDOS~")
  call tkadd(" BZ_TETRA~")
  call tkadd(" BZ_W~")
  call tkadd(" BZ_ZBAK~")
  call tkadd(" EWALD~")
  call tkadd(" EWALD_AS~")
  call tkadd(" EWALD_NKDMX~")
  call tkadd(" EWALD_RPAD~")
  call tkadd(" EWALD_TOL~")
  call tkadd(" ITER~")
  call tkadd(" ITER_CONV~")
  call tkadd(" ITER_CONVC~")
  call tkadd(" ITER_MIX~")
  call tkadd(" ITER_NITU~ ITER_TOLU~ ITER_UMIX~")
  call tkadd(" ITER_NRMIX~")
  call tkadd(" ITER_NIT~")
  call tkadd(" HAM")
  call tkadd(" HAM_NSPIN~")
  call tkadd(" HAM_ELIND~")
  call tkadd(" HAM_EWALD~")
  call tkadd(" HAM_FORCES~")
  call tkadd(" HAM_FRZWF~")
  call tkadd(" HAM_READP~") !2022-9-5
  call tkadd(" HAM_V0FIX~") !2022-9-5
  call tkadd(" HAM_PNUFIX~") !2022-9-5
  call tkadd(" HAM_FTMESH")
  call tkadd(" HAM_GMAX")
  call tkadd(" HAM_OVEPS~ HAM_STABILIZE~") !  HAM_OVNCUT~ ")
  call tkadd(" HAM_PMAX~")
  call tkadd(" HAM_PMIN~")
  call tkadd(" HAM_PWMODE~ HAM_PWEMIN~ HAM_PWEMAX~ HAM_NPWPAD~")
  call tkadd(" HAM_REL~ HAM_SO~ HAM_SOCAXIS~")
  call tkadd(" HAM_RDSIG~")
  call tkadd(" HAM_RSRNGE~")
  call tkadd(" HAM_ScaledSigma~")
  call tkadd(" HAM_SIGP~")
  call tkadd(" HAM_TOL~")
  call tkadd(" HAM_XCFUN~")
  call tkadd(" DYN~")
  call tkadd(dyn_mstat)
  !call tkadd(dyn_md)
  call tkadd(" DYN_NIT~")

  ! --- LMCHK switches ---
  call nswadd()
  call tkadd(" LMCHK::" )
  call tkadd(" VERS_LM")
  call tkadd(trim(io_sw))
  call tkadd(trim(struc_sw))
  call tkadd(" OPTIONS~")
  call tkadd(" OPTIONS_NESABC~ OPTIONS_RMAXES~ OPTIONS_RMINES~")
  call tkadd(" SPEC")
  call tkadd(sscale)
  call tkadd(" SPEC_ATOM")
  call tkadd(" SPEC_ATOM_A~")
  call tkadd(" SPEC_ATOM_CSTRMX~")
  call tkadd(" SPEC_ATOM_DV~")
  call tkadd(" SPEC_ATOM_LMX~")
  call tkadd(" SPEC_ATOM_MMOM~")
  call tkadd(" SPEC_ATOM_NMCORE~")
  call tkadd(" SPEC_ATOM_NR~")
  call tkadd(" SPEC_ATOM_P~")
  call tkadd(" SPEC_ATOM_Q~")
  call tkadd(" SPEC_ATOM_R~")
  call tkadd(" SPEC_ATOM_R/A~")
  call tkadd(" SPEC_ATOM_R/W~")
  call tkadd(" SPEC_ATOM_Z")
  call tkadd(" SITE")
  call tkadd(" SITE_FILE~")
  call tkadd(" SITE_MODE~")
  call tkadd(" SITE_ATOM")
  call tkadd(" SITE_ATOM_DPOS~")
  call tkadd(" SITE_ATOM_PL~")
  call tkadd(" SITE_ATOM_POS")
  call tkadd(" SITE_ATOM_XPOS")
  call tkadd(" SITE_ATOM_ROT~")
  call tkadd(" SITE_ATOM_AF~") !may2015
  call tkadd(" SYMGRP~")
  call tkadd(" SYMGRPAF~")
  call tkadd(" STR~")
  call tkadd(" STR_MXNBR~")
  call tkadd(" STR_RMAX~")
  call tkadd(" STR_RMAXS~")
  call tkadd(" EWALD~")
  call tkadd(" EWALD_AS~")
  call tkadd(" EWALD_NKDMX~")
  call tkadd(" EWALD_RPAD~")
  call tkadd(" EWALD_TOL~")

  call tkadd(" HAM")
  call tkadd(" HAM_NSPIN~")
  call tkadd(" HAM_NONCOL~ HAM_SS~")
  call tkadd(" HAM_XCFUN~")
  call tkadd(" HAM_SO~ HAM_SOCAXIS~")

  call tkadd(" BZ")
  call tkadd(" BZ_NOINV~")
end subroutine toksw_init
