# -*- Mode: org ; Coding: utf-8-unix -*-
#+TITLE: How to generate |MLO> orbitals (MuffinTin-oibital-based localized orbitals).
#+AUTHOR: takao kotani @ tottori university, Japan
#+email: takaokotani@gmail.com

We describe how to get MLO(muffin-tin based localized oribtals)-based Hamiltonian.
Afte we remove APW part in the 1st step, we get MLO-based Hamiltonian 
at the 3rd step via a modified Souza's procedure.


* 0th step.
Get converged results in LDA or QSGW.
Then run job_band (syml.si is generated by getsyml si).


* 1st step: Get MTP Hamiltonian from PMT Hamiltonian
Let me explain Si case. Starting from the |PMT> (APW+MTO) basis,
we remove the APW part at first, where we have to keep the eigenvalue dispersion at low energy.

This is performed by 
>ecalj/SRC/exec/job_ham si -np 4
. (core part of job_ham is in lmfham1. Look into the script job_ham.)
Then we have the Hamiltonian (and overlap matrix) for the basis the Muffintin-projected orbitals |MPO>.

At the 1st step, mlo_facw, mlo_eucutw, and mlo_eww are used in GWinput (see lmfham1.f90)
However, we usually not add them to GWinput (default values), as long as we have good results of 1st step.

As a We have bandplot.lmfham1.isp*.glt for gnuplot.
This is for the Hamiltonian of |MTP> (muffin-tin-projected basis). Generated by lmfham1


* 2nd step: Get connecting matrix between k and k+b. lmfham2 --job=0  
Set MLO orbitals in GWinput as
!----------------------------------------------------
<Worb> Site 
  1 Si   1 2 3 4 5 6 7 8 9 
  2 Si   1 2 3 4 5 6 7 8 9
</Worb>
!----------------------------------------------------
This set MTO index as seed of MLO.
See MHAM: shown at the begining of lmfham (the MTO index of MHAM is with atom index).
Then we run 
>lmfham2 --job=0
(Not yet paralellized).


* 3rd step: lmfham2 --job=1
We may have to repeat lmfham2 --job=1 until we get reasonable results.
See examples. And lmfham2.f90, where we see all settings and default values.

** Default run
At first, try 
>lmfham2 --job=1
without any additional settings. Then plot bandplot.lmfham2.isp*.glt
This superpose not only for the Hamiltonian of |MTP> (muffin-tin-projected basis) at the 2nd step, but also
the |MLO> (muffin-tin based localized oribtals) Hamiltonian.

NOTE: we use nk in ctrl file for meshing. nk can not be too small for real-space interpolation
(we do not used the interpolation in the usual self-consistency mode of lmf-MPIK).

** Inner window setting.
We may add
 mlo_EUinner 5
to GWinput if we like to add inner window at 5eV.
Our inner window is soft (not hard truncation as the original of Souza). Thus mlo_EUinner is not to be accurate so much.
When Default run show 'AUTO: isc iq eLhard ' is too low (this is a case of SrTiO3), set ELinner as well.

Larger EUinner may destroy continuity of bands and bumpy.

For Si, we may need fine tuning if we like to have high accuracy. 
I found mlo_WTseed 2500 gives slightly smoother result at CBM for Si888.

Nabla2/nMLO indicates the range of MLO Hamiltoian (I have not examined the meanings of its absolute value. 
But meaningful as indicator at least).

For tests, we may use maxit 10, however I observed cases
that 10 is too small to make band dispersion too noisy
(observe convergence on Nabla2/nMLO.)
Convergence criterion mlo_conv might be a little larger, but not tested.

** Outer window setting
We set mlo_CUouter, which is a parameter to detemine outer window.
In our method, we supply mlo_CTouter finally. 

For NiO666lda, this is mlo_CTouter 0.2 works well. But I have no definite 
idea to set it automatically.


** Other settings
In principle, use default settings. We improve algolizm to determine settings.


* TODO
** Parallellize lmfham2, speed up
** Default setting. Can we make it automatic?
** Calculate effective interaction. Plot picture of MLO. 
** PROBLEMS: (not so serious)
 The space-group symmety is slightly broken in lmfham1, which uses Gram-shmidt diagonalization. (one by one otrhogonalized from bottom).
 The Souza procedure of lmfham2 may enhance the broken symmetry.
 SmP discontinuous at K. Why?
