# -*- Mode: org ; Coding: utf-8-unix -*-
#+TITLE: How to generate |MLO> orbitals (MuffinTin-oibital-based localized orbitals). revised at 2023-08-30
#+AUTHOR: takao kotani @ tottori university, Japan
#+email: takaokotani@gmail.com

Starting from PMT Hamiltonian, we remove APW part in the 1st step, 
resulting the MTP(muffin-tin projected) Hamiltonian at the end of the 1st step.
Then we finally get MLO(muffin-tin based localized oribtals)-based Hamiltonian at the end of the 3rd step. 

* 0th step.
Get converged results in LDA or QSGW.
Then run job_band (syml.si is generated by getsyml si).

* 1st step: Get MTP Hamiltonian from PMT Hamiltonian
Let me explain Si case. Starting from the |PMT> (APW+MTO) basis,
we remove the APW part at first, where we have to keep the eigenvalue dispersion at low energy.

This is performed by 
>ecalj/SRC/exec/job_ham si -np 4
. (core part of job_ham is in lmfham1. Look into the script job_ham.)
Then we have the Hamiltonian (and overlap matrix) for the basis the Muffintin-projected orbitals |MPO>.

At the 1st step, mlo_facw, mlo_eucutw, and mlo_eww are used in GWinput (see lmfham1.f90)
However, we usually not add them to GWinput (default values), as long as we have good results of 1st step.

As a We have bandplot.lmfham1.isp*.glt for gnuplot.
This is for the Hamiltonian of |MTP> (muffin-tin-projected basis). Generated by lmfham1

* 2nd step: Get connecting matrix between k and k+b. lmfham2 --job=0  
Set MLO orbitals in GWinput as
!----------------------------------------------------
<Worb> Site 
  1 Si   1 2 3 4 5 6 7 8 9 
  2 Si   1 2 3 4 5 6 7 8 9
</Worb>
!----------------------------------------------------
This set MTO index as seeds for MLO.
See 'MHAM:' indexes shown at the begining of lmfham (the MTO index of MHAM is with atom index).
Then we run 
>lmfham2 --job=0
for prepare connecting matrix required for the next step.
(Not yet paralellized).

* 3rd step: lmfham2 --job=1
We may have to repeat lmfham2 --job=1 until we get reasonable results.
See examples. And lmfham2.f90, where we see all settings and default values.
** Settings of inner window
To set the inner window manually, we can use mlo_EUinner or mlo_CUinner.
See the Setting Table below.
But defaults worked well for Fe,Cu GdION, NiO and SrTiO3.

Lower limit of inner window is automatic now.
(I suppose it works for any case.)

*** Semiconductors. mlo_EUinner
For Si, set 
mlo_EUinner 5 
. Here 5 means that we set the upper limit of inner window at 5eV above VBM. 
We use a soft inner window. Thus we do not need to give detailed values (resolution can be ~1eV).

Larger EUinner may destroy continuity of bands and bumpy. (this is a case with default EUinner)

*** 4f case.  mlo_CUinner
For SmP, set 
mlo_CUinner 0.9
This means that we set EUinner at 90 percent point for each 4f MTO components.
When mlo_CUinner 0.5 (this is default), I found EUinner can be a little smaller for SmP.

** Run and Check results
Run
>lmfham2 --job=1
Then plot bandplot.lmfham2.isp*.glt
This superpose not only for the Hamiltonian of |MTP> (muffin-tin-projected basis) at the 2nd step, 
but also the |MLO> (muffin-tin based localized oribtals) Hamiltonian.

NOTE: we use nk in ctrl file for meshing. nk can not be too small for real-space interpolation
(we do not used the interpolation in the usual self-consistency mode of lmf-MPIK).

For tests, we may use maxit 10, however I observed cases
that 10 is too small to make band dispersion too noisy (observe convergence on Nabla2/nMLO.)
Convergence criterion mlo_conv might be a little larger, but not tested.

* 4th step: fine tuning
With changing WTseed and/or WTinner, we may make fine tuning to have better 
reproduction of PMT band structures.
In addition to EUinner/CUinner, we may change WTseed, WTband, and WTinner to get better results.
For larger WT*, the relative contribution from the nabla term become relatively smaller.
*** WTseed
Larger WTseed make bands smoother. Larger WTband may give better band structure,
although causes bumpy bands. 
Try WTseed 128, instead of default value of WTseed 64
*** WTband
Default WTband is zero.
But I found WTband 128 improve result of SrTiO3.
With larger WTband, we may destroy continuity (I saw this in the case of GaAs with WTband 64).
*** WTinner
In the case of C(diamond), we saw good match with both two cases (a) and (b).
 (a) mlo_EUinner 10 with mlo_WTinner 2048(default), 
 (b) mlo_EUinner 5  with mlo_WTinner 1024.
(b) is a little poorer than case (a).
(b) means mlo_EUinner 5 is too low to use strong inner window (=WTinner 2048).
With softer inner window (=WTinner 1024), we can take into acount high band effects 
a little more. This improves results in the case of C.
*** Outer window CUouter (may affects little)
I found CUouter 0.1 is slightly better than CUouter 0 for NiO.
But I think CUouter gives little effects usually.
CUouter can be 0,0.1,0.2 to check MLO become better or not. 

*** Other parameters
We see other parameters mlo_foobar at the begining of lmfham2.f90
Some parameters may change band structures slightly, however, we expect 
changing mlo_foobar will give little improvements.

* Samples
Hamiltonian models may be classified to
# (1) Semiconductors (spd models)
# (2) metal (spd band model)
# (3) Crystal-field model (3d,4f, and so on without hybridyzation)
# (4) Fermi surface around model (3d + Oxygen2p + metallic s band)
As for (1), we may need to set the mlo_EUinner.
As for (3) and (4), we may set mlo_CUinner or mlo_EUinner.

For trial test, you may use mlo_maxit 10. But be careful for convergence.

** Si666gwsc,Si888gwsc,GaAs
>mlo_EUinner 5
(fine tuning for Si888). A slightly better result with mlo_WTseed 128 for CBM around.
** C(dia)
>EUinner 10 
See the description for WTinner above.
Use EUinner 10 (or WTinner 1024 and EUinner 5).
** NiO666lda
Default OK.
We can do MLO with the default setting of mlo_CUinner 0.5.
This is to set EUinner by the condition that the number of occupancy >0.5 
for projections to given MTOs. If we set mlo_CUinner 0.9, 
it gives slightly too large EUinner, resulting slighly poor band structure.
** SmP
>mlo_CUinner 0.9
Set mlo_CUinner 0.9 to give larger value of EUinner.
With the default mlo_CUinner 0.5, we have a little too low EUinner, resulting
unsatisfactory band structure.
** GdNION
Default OK. 
mlo_CUinner 0.9 works as well. So, mlo_CUinner 0.9 is probably general for 4f.
** Fe,Cu
Default OK.
We observe that mlo_EUinner 5 for Cu show slightly different band structure.
** SrTiO3
Default OK.
(fine tuning) I found mlo_WTband 128 gives better band matching.

* Samples. Setting Table for mlo_* to obtain good result 
|-----------+---------------+---------+-------------+--------+--------+-----------------|
|           | Inner Setting |         | Fine Tuning |        |        |                 |
|           |       EUinner | CUinner |     WTinner | WTseed | WTband |                 |
| default   |               |      .5 |        2048 |     64 |      0 |                 |
| Si666gwsc |             5 |         |             |        |        | spd model       |
| Si888gwsc |             5 |         |             |    128 |        | spd model       |
| GaAs      |             5 |         |             |        |        |                 |
| C         |            10 |         |             |        |        |                 |
| C  case2  |             5 |         |        1024 |        |        | a little poorer |
| NiO666lda |               |         |             |        |        |                 |
| SrTiO3    |               |         |             |        |    128 |                 |
| SmP       |               |      .9 |             |        |        | 4f model        |
| GdION     |               |      .9 |             |        |        | 4f model        |
| Fe        |               |         |             |        |        | spd model       |
| Cu        |               |         |             |        |        | d model         |
| Cu case2  |             5 |         |             |        |        | d band smoother |
|-----------+---------------+---------+-------------+--------+--------+-----------------|

* TODO
** Parallellize lmfham2, speed up
** Calculate effective interaction. Plot picture of MLO. 
** PROBLEMS: (not so serious)
 The space-group symmety is slightly broken in lmfham1, which uses Gram-shmidt diagonalization. (one by one otrhogonalized from bottom).
 The Souza procedure of lmfham2 may enhance the broken symmetry.
 SmP discontinuous SmP at K Why? ==>only four-fold rotation
