# -*- Mode: org ; Coding: utf-8-unix -*-
#+TITLE: How to generate |MLO> orbitals (MuffinTin-oibital-based localized orbitals).
#+AUTHOR: takao kotani @ tottori university, Japan
#+email: takaokotani@gmail.com

* 0th step.
Get converged results in LDA or QSGW.
Then run job_band (syml.si is generated by getsyml si).

* 1st step:
Let me explain Si case.
Starting from the |PMT> (APW+MTO) basis,
we remove the APW part at first, where we have to keep the eigenvalue dispersion at low energy.
This is performed by 
>mpirun -np 4 lmfham1 si
. 
Then we have the Hamiltonian (and overlap matrix) for the basis the Muffintin-projected orbitals |MPO>.

Note that in advance to do this, we have to prepare eigenfunctions at all the k points in BZ 
(k points mesh is specified in ctrl.si) by
>mpirun -np 4 lmf-MPIK si --writeham --mkprocar --fullmesh 
. See the script ecalj/SRC/exec/job_ham in detail.

At the 1st step, only 
GWinput: mlo_facw_lmfham1 is effective (I think).
Since we use defaults value, we don't need to write it in GWinput.


* 2nd step:
Edit GWinput to run lmfham2
!----------------------------------------------------
<Worb> Site 
  1 Si   1 2 3 4 5 6 7 8 9 
  2 Si   1 2 3 4 5 6 7 8 9
</Worb>
mlo_WTband  32  !push bands lower
mlo_WTinner 256 !inner window weight For semiconductors, WTband x WTinner ~8192 (this is just a rule of thumb).
mlo_maxit 10    !try this first. So much many times is not so meaningful probably.
!mlo_EUinnerAdd 3 !inner window is at Efermi+3eV. No lower
!mlo_WTseed  0
See examples. And lmfham2.f90, where we see all settings and default values.

Then we run 
>lmfham2 --job=0
>lmfham2 --job=1
(Not yet paralellized).
You can change mlo_* and repeat lmfham2

See examples

* Check results
We have two results.
   * bandplot.lmfham1.isp*.glt
     This is for the Hamiltonian of |MPO> (muffin-tin-projected basis).Generated by lmfham1

   * bandplot.lmfham2.isp*.glt
     This is for not only for the Hamiltonian of |MLO> (muffin-tin-projected basis).

* TODO
** Parallellize lmfham2, speed up
** Test many possible cases. 
    Semiconductors, 4f, magnetic systems, transition metal oxides..., graphite... Slab
** Default setting. Can we make it automatic?
** Calculate effective interaction. Plot picture of MLO. 
** Evaluate range of Hamiltonian. 
** PROBLEMS: (not so serious)
 The space-group symmety is slightly broken in lmfham1, which uses Gram-shmidt diagonalization. (one by one otrhogonalized from bottom).
 The Souza procedure of lmfham2 may enhance the broken symmetry.
