# -*- Mode: org ; Coding: utf-8-unix -*-
#+TITLE: How to generate |MLO> orbitals (MuffinTin localized orbitals) replacing MaxLocWannier?
#+AUTHOR: takao kotani @ tottori university, Japan
#+email: takaokotani@gmail.com
#+date:  2024-06-21

Starting from PMT Hamiltonian (APW+MTO), we remove APW part at the 1st step. 
Then we have the |MLO0> (MuffinTin localized orbital zero) and the Hamiltonian of |MLO0>.
At the 2nd step, we get  |MLO>  (MuffinTin localized oribtals), and the Hamiltonian of |MLO>.

* Minimum setting for calculation.
To get MLO, we need to set MLO index such as
<Worb> Site 
  1 Si   1 2 3 4 5 6 7 8 9  
  2 Si   1 2 3 4 5 6 7 8 9
</Worb>
. 
In addiiton, we set 
In addition, mlo_EUinner 5, which sets upper limit of inner window. (this is effective for --job=1)
mlo_EUinner seems to be required for indirect semiconductors.
Except indirect semiconductors, we can use automatic setting of mlo_EUinner.

* 0th step 
Get some results in LDA or QSGW. 
Then run job_band (syml.si is generated by getsyml si).
For LDA, run lmfa, lmf, job_band successively, after generating ctrl file from ctrls

* 1st step: Get MLO0 Hamiltonian from PMT Hamiltonian. 
MLO0 is augmented MTO (no APW).
>job_ham si -np 8
We have bandplot_MLO0_isp*.glt for gnuplot.
Check that job_ham results in
>OK! end of job_ham. Run next steps above
Then you can go ahead to 2nd step
# NOTE: At the 1st step, mlo_facw, mlo_eucutw, and mlo_eww written in GWinput may be used.
# Otherwise(usually) we use default value in GWinput.

* 2nd step: Get MLO Hamiltonian from MLO0 
Set MLO orbitals in GWinput as
!----------------------------------------------------
<Worb> Site 
  1 Si   1 2 3 4 5 6 7 8 9 
  2 Si   1 2 3 4 5 6 7 8 9
</Worb>
!----------------------------------------------------
Set MTO index as the seeds for MLO. Edit GWinput.tmp to set Worb section.
Then generate connecting matrix required for the next step by
>lmfham2 --job=0 (Not yet paralellized).

Next, we run
> lmfham2 si --job=1 (not yet paralellized)
This step generates MLO and MLO-based Hamitonian. (Mufftin localized orbitals).

** NOTE for settings of inner window
We may need to set mlo_EUinner for indirect semiconductor.
For indirect band semiconductors, we may have to repeat lmfham2 --job=1 
with changing mlo_EUinner until we get reasonable results.
Rule of sum for mlo_EUinnner is a few eV more than band gap.
We have to observe CBM in detail. 
# Lower limit of inner window is automatic now. (I suppose it works for any case.)

*** Semiconductors. mlo_EUinner
For Si, set 
mlo_EUinner 5 
. Here 5 means that we set the upper limit of inner window at 5eV above VBM. 
We use a soft inner window. Thus we do not need to give detailed values (resolution can be ~1eV).

Larger EUinner may destroy continuity of bands and bumpy. (this is a case with default EUinner)

