class Keyword:
    list = []
    def __init__(self):
        self.list.append("igetss")
        self.list.append("igets")
        self.list.append("dgetss")
        self.list.append("dgets")
        self.list.append("spacks")
        self.list.append("spackv")
        self.list.append("pack1")
        self.list.append("pack2")
        self.list.append("pack3")
        self.list.append("pack4")
        self.list.append("pack5")
        self.list.append("pack")
        self.list.append("upack1")
        self.list.append("upack2")
        self.list.append("upack3")
        self.list.append("upack4")
        self.list.append("upack5")
        self.list.append("upack")
        self.list.append("lsets")
        self.list.append("lgors")
        self.list.append("lgands")

