#!/bin/csh
# --------------------------------
# self-consistent GW itteration .
#---------------------------------
set n = $0
set nfpgw = ${n:h}
echo $nfpgw

set ddd = $argv[1]
foreach spin (spin1 spin2)
echo -10,5,15,15|plbnds -fplot -ef=0 -scl=13.605 -$spin $ddd
foreach xxx ( bnd*.dat)
mv $xxx $xxx.$spin
mv $xxx.ddd $xxx.ddd.$spin
end
sed -e "s/.dat/.dat.$spin/g" plot.plbnds > plot.plbnds.$ddd.$spin

# lmf --band:fn=syml $ddd >llmf_band
#echo -10,15,15,15|plbnds -fplot -ef=0 -scl=13.605  $argv[1]

###########
cat $nfpgw/bandp.ngp >bandp_plot.$spin.ngp
sed -e "s/.dat.ddd/.dat.ddd.$spin/g" plot.ngp >> bandp_plot.$spin.ngp

fplot -f plot.plbnds.$ddd.spin1; mv ps.dat band_spin1.$ddd.ps
fplot -f plot.plbnds.$ddd.spin2; mv ps.dat band_spin2.$ddd.ps
end

#ngraph bandp_plot.ngp
