#!/usr/bin/env python3
"""Write MD/module_map.md: the module DAG of SRC and the entry of each main program.

  python3 TOOLS/module_map.py          (from the top of ecalj)

For each Fortran module of SRC/subroutines and SRC/main: its file, its level (0 = uses no ecalj module; otherwise
1 + the highest level among the modules it uses), the ecalj modules it uses, how many use it, and the first comment line
next to the module statement (as a hint of what it is). The main programs (SRC/main/*.f90) are listed with the modules and
routines they call. Cycles, if any, are reported. The map is regenerated, not edited by hand.
(2026-10-01, in place of Doxygen, which was retired: MD/past_log.md §11)
"""
import os, re, glob, collections, datetime, subprocess

TOP = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(TOP, 'SRC')
files = sorted(glob.glob(f'{SRC}/subroutines/*.[fF]90') + glob.glob(f'{SRC}/main/*.[fF]90'))

mod_re = re.compile(r'^\s*module\s+(?!procedure\b)(\w+)\s*(?:!.*)?$', re.I)
use_re = re.compile(r'^\s*use\s*(?:,\s*(?:non_)?intrinsic\s*::)?\s*(\w+)', re.I)
prog_re = re.compile(r'^\s*program\s+(\w+)', re.I)
call_re = re.compile(r'^\s*call\s+(\w+)', re.I)

mods = {}          # name -> dict(file, uses=set, hint)
progs = {}         # file -> dict(uses=[(mod, only)], calls=[...])
for f in files:
    rel = os.path.relpath(f, TOP)
    lines = open(f, errors='replace').read().splitlines()
    cur = None; prog = None
    for i, l in enumerate(lines):
        m = mod_re.match(l)
        if m and not re.match(r'^\s*end', l, re.I):
            cur = m.group(1).lower()
            hint = ''
            for k in list(range(i + 1, min(i + 4, len(lines)))) + list(range(max(i - 3, 0), i)):
                c = lines[k].strip()
                if c.startswith('!') and len(c.strip('!- =*').strip()) > 8:
                    hint = c.lstrip('!').strip()[:110]; break
            mods[cur] = dict(file=rel, uses=set(), hint=hint)
            continue
        if re.match(r'^\s*end\s+module', l, re.I): cur = None; continue
        p = prog_re.match(l)
        if p: prog = rel; progs[rel] = dict(uses=[], calls=[]); continue
        u = use_re.match(l)
        if u:
            name = u.group(1).lower()
            if cur: mods[cur]['uses'].add(name)
            elif prog:
                only = re.search(r'only\s*:\s*(.*)', l, re.I)
                progs[prog]['uses'].append((name, only.group(1).split('!')[0].strip() if only else ''))
        c = call_re.match(l)
        if c and prog and not cur: progs[prog]['calls'].append(c.group(1))

names = set(mods)
for v in mods.values(): v['uses'] = sorted(x for x in v['uses'] if x in names)
usedby = collections.Counter(x for v in mods.values() for x in v['uses'])
for p in progs.values():
    for x, _ in p['uses']: usedby[x] += 0

level = {}; cycles = []
def lev(n, stack=()):
    if n in level: return level[n]
    if n in stack: cycles.append(stack[stack.index(n):] + (n,)); return 0
    d = [lev(x, stack + (n,)) for x in mods[n]['uses'] if x != n]
    level[n] = 1 + max(d) if d else 0
    return level[n]
for n in mods: lev(n)

rev = subprocess.run(['git', '-C', TOP, 'log', '-1', '--format=%h %cs'], capture_output=True, text=True).stdout.strip()
out = []
out.append('# Module map of SRC (generated)\n')
out.append(f'Generated by `python3 TOOLS/module_map.py` on {datetime.date.today()} from `{rev}`. Do not edit by hand; regenerate.\n')
out.append('How to read: every Fortran module is a singleton (MD/ecaljclaude.md, "Fortran Singleton Pattern"). Level 0 uses no ecalj '
           'module; a module of level n uses modules of level < n only (the DAG). "hint" is the first comment line next to the '
           '`module` statement, a clue and not a specification. The programs of `SRC/main` are thin: they set up MPI and the '
           'arguments and call one routine of a module (lmf -> `m_lmf: lmf`).\n')
out.append(f'{len(mods)} modules in {len(files)} files; {len(progs)} main programs; highest level {max(level.values())}.\n')
out.append('The scan ignores `#ifdef`: the map is the union of the CPU and GPU builds (e.g. `m_gpu` uses `m_blas` only with `__GPU`).\n')
if cycles:
    out.append('**Cycles found** (a use of a module inside a contained routine counts; the levels next to a cycle are approximate): '
               + '; '.join(' -> '.join(c) for c in cycles) + '\n')

out.append('## 1. Main programs (SRC/main)\n')
out.append('| program file | modules used (only:) | calls |')
out.append('|---|---|---|')
skip = {'mpi', 'm_mpi', 'm_args', 'm_cmdpath', 'm_ext', 'm_lgunit'}
for f, p in sorted(progs.items()):
    u = '; '.join(f'`{x}`' + (f' ({o})' if o else '') for x, o in p['uses'] if x not in skip)
    c = ', '.join(dict.fromkeys(x for x in p['calls'] if x.lower() not in ('mpi_init', 'mpi_finalize', 'exit', 'mpi_comm_rank',
                                                                          'setipr', 'setcmdpath', 'm_setargs', 'm_ext_init')))
    out.append(f'| `{os.path.basename(f)}` | {u} | {c} |')
out.append('')

out.append('## 2. Modules by level\n')
bylev = collections.defaultdict(list)
for n, l in level.items(): bylev[l].append(n)
for l in sorted(bylev):
    out.append(f'- level {l} ({len(bylev[l])}): ' + ', '.join(f'`{n}`' for n in sorted(bylev[l])))
out.append('')

out.append('## 3. Modules\n')
out.append('| module | file | level | used by | uses | hint |')
out.append('|---|---|---|---|---|---|')
for n in sorted(mods, key=lambda n: (level[n], n)):
    v = mods[n]
    out.append(f"| `{n}` | {os.path.relpath(os.path.join(TOP, v['file']), SRC)} | {level[n]} | {usedby[n]} | "
               f"{', '.join(v['uses'])} | {v['hint'].replace('|', '/')} |")
out.append('')
open(os.path.join(TOP, 'MD', 'module_map.md'), 'w').write('\n'.join(out))
print(f'MD/module_map.md: {len(mods)} modules, {len(progs)} programs, max level {max(level.values())}, cycles {len(cycles)}')
