#!/bin/csh
# --------------------------------
# self-consistent GW itteration .
#---------------------------------
if(-e NoCore) then
  rm -f NoCore 
endif
if(-e QPU) then
 rm -f QP[UD]
endif

set n = $0
set nfpgw = ${n:h}
echo $nfpgw
echo $argv[1]

echo 2|$nfpgw/hsfp0_sc   >lsc
echo 0|$nfpgw/hqpe_sc    >lqpe

