#! /bin/tcsh
# NoCore case --------------------------------
#
# All the core section in the end of GWIN is neglected 
# (All the switch are treated as zero).
# We subtruct the LDA exchange-correlation contribution V(nvalence(r)).
#
# Required inputs are 
#  GWIN0  *.mas *.rst 
#  GWIN   QPNT  !Templetes of them are given as 
#               !GWIN.tmp QPNT.tmp after lbg0.
#  (EFERMI CLASS)
#---------------------------------------------
set nfpgw = $0:h
echo $nfpgw


echo $argv[1]
setenv LMJOB $argv[1]

touch NoCore
echo 0 | $nfpgw/ng0  >lng00
$nfpgw/qg4gw >lqg4gw
echo 1 | $nfpgw/ng0  >lng01
echo 2 | $nfpgw/ng0  >lng02
echo 3 | $nfpgw/ng0  >lng03
$nfpgw/nfp4gw        >lnfp4gw
$nfpgw/rdata4gw      >lrdata4gw

# get EFERMI
echo 1|$nfpgw/heftet      >leftet

#- Core exchange-----------------
#echo 3|$nfpgw/hbasfp0 >lbasC
#echo 0|$nfpgw/hvccfp0        >lvccC
#echo 3|$nfpgw/hsfp0   >lsxC
#--------------------------------

#-------------------------------
echo 0|$nfpgw/hchknw         >lchknw
echo 0|$nfpgw/hbasfp0 >lbas
echo 0|$nfpgw/hvccfp0        >lvcc	

echo 1|$nfpgw/hsfp0   >lsx
$nfpgw/hx0fp0         >lx0
echo 2|$nfpgw/hsfp0   >lsc

# this is dummy run to get SEXcore =0
echo 3|$nfpgw/hsfp0   >lsxC

echo 0|$nfpgw/hqpe    >lqpe




 
