#!/bin/csh
# --------------------------------
# Get GWIN.tmp and QPNT.tmp (QPNTforSYML.tmp if(-e SYML))
#
set n = $0
set nfpgw = ${n:h}
echo $nfpgw
echo $argv[1]

echo "== Type three integers n1 n2 n3 for Brillowin Zone meshing for GW! =="
echo -n ' n1= '
set n1 = $<
echo -n ' n2= '
set n2 = $<
echo -n ' n3= '
set n3 = $<
echo $n1 $n2 $n3 

# This is bug fix for lmto
#if( `grep -l GW ctrl.$argv[1]` != ctrl.$argv[1]) then
#  echo "GW NKABC= GCUTB= GCUTX=" >>ctrl.$argv[1]
#endif

############################################
# reserve these files.
foreach head (GWinput GWIN_V2 GWIN0 QPNT)
  if( -e $head) then
    mv $head $head.bk12456
  endif
end

################################################
#$nfpgw/gwinit   
#mv GWIN0.tmp   GWIN0


cat <<EOF >GWIN0
n1 n2 n3
 $n1 $n2 $n3
cut
 3.2 2.7 
alpha
 1
Number of bands
 999 99999.0 
 999 2.0 
EOF
echo 0 | $nfpgw/lmfgw $argv[1]     > llmfgw00
echo 1 | $nfpgw/gwinit   #This changes the <QPNT> setting.
mv GWIN_V2.tmp GWIN_V2
mv QPNT.tmp    QPNT
echo -100 |$nfpgw/qg4gw  $argv[1] > lqg4gw00 # 
mv QPNT QPNT.chk
rm GWIN_V2
mv GWIN0 GWIN0.chk
mv GWinput GWinput.tmp


############################################
# reserved files are moved to original names.
foreach head (GWinput GWIN0 GWIN_V2 QPNT)
  if( -e $head.bk12456) then
    mv $head.bk12456 $head 
  endif
end

echo 'OK! GWinpt.tmp is generated!'
 
