# -*- Mode: org ; Coding: utf-8-unix -*-
#+TITLE: ecalj: examples in ecalj/MATERIALS/
#+AUTHOR: takao kotani @ tottori university, Japan
#+email: takaokotani@gmail.com

We have some examples in ecalj/MATERIALS/
Somethings in this directory are obsolate (or just unused recently).
At least, we have following samples working.


* Extract MTO-only Hamiltonian (we have samples Si_HamMTO/ and Fe_HamMTO/).
see README_HamMTO.org
* job_materials.py :Variety of mateirals samples
(type without arguments; it shows help.)
It can perform LDA/GGA calculations in MATERIALS/Materials.ctrls.database.

 This job_materials.py works as follows for given material names.
 Step 1. Generate ctrls.* file for Materials.ctrls.database. (names are in DATASECTION:)
 Step 2. Generate ctrl by ctrlgenM1.py
 Make directtory such as Si/

* MgO_PROCAR : PROCAR generation sample
 Run jobprocar. This gives *.eps file which shows Fat band picture.
 PROCAR (vasp format) is generated and analysed by a script BandWeight.py.

* Samples_MLWF : Wannier function generator and cRPA 
  wannier90 method implemented in ecalj and cRPA. 
  (a cRPA method by Juelich group).
  See Samples_MLWF/README.

* mass_fit_test
  Effective mass calculation. See README.
